### ISSUE TITLE
[DOC] Add a synchronization example for CUDA Array Interface v3

### ISSUE THREAD

**Issue by leofang** [mpi4py/mpi4py#10]
This is a note to myself that I should update (or add) the documentation now that the v3 protocol (https://github.com/numba/numba/pull/5162) is merged and the change has been propagated to CuPy (https://github.com/cupy/cupy/pull/4357). Specifically, I would like to add an example to show how to make it work robustly with mpi4py, following our earlier conclusion https://github.com/numba/numba/pull/5162#pullrequestreview-444928215.

**Comment by leofang** [comment]
Oh, I am not a maintainer (yet?) so I can't assign myself 😂

**Comment by dalcinl** [comment]
> Oh, I am not a maintainer (yet?) so I can't assign myself

No, not here in GitHub yet. I just gave you "Owner"-level access to the org, check your email for the invitation.

**Comment by leofang** [comment]
I'm in! Thanks.
