### ISSUE TITLE
NVHPC: Unknown Compiler Flags

### ISSUE THREAD

**Issue by ax3l** [mpi4py/mpi4py#114]
Hi,

I am trying to compile `mpi4py` with [NVHPC 21.9](https://developer.nvidia.com/hpc-sdk), which is the follow-up product to the PGI compilers.

Performing a compile with the C/C++ compilers `nvc`/`nvc++` fails with unknown compiler flags being passed to those compilers.

## Error Message

```
...
  running build_clib
  MPI configuration: [mpi] from 'mpi.cfg'
  MPI C compiler:    /opt/nvidia/hpc_sdk/Linux_x86_64/21.9/comm_libs/mpi/bin/mpicc
  MPI C++ compiler:  /opt/nvidia/hpc_sdk/Linux_x86_64/21.9/comm_libs/mpi/bin/mpicxx
  MPI F compiler:    /opt/nvidia/hpc_sdk/Linux_x86_64/21.9/comm_libs/mpi/bin/mpifort
  MPI F90 compiler:  /opt/nvidia/hpc_sdk/Linux_x86_64/21.9/comm_libs/mpi/bin/mpif90
  MPI F77 compiler:  /opt/nvidia/hpc_sdk/Linux_x86_64/21.9/comm_libs/mpi/bin/mpif77
  checking for library 'lmpe' ...
  /opt/nvidia/hpc_sdk/Linux_x86_64/21.9/comm_libs/mpi/bin/mpicc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -c _configtest.c -o _configtest.o
  nvc-Error-Unknown switch: -Wno-unused-result
  nvc-Error-Unknown switch: -fwrapv
  nvc-Error-Unknown switch: -fstack-protector-strong
  nvc-Error-Unknown switch: -fwrapv
  nvc-Error-Unknown switch: -fstack-protector-strong
  nvc-Error-Unknown switch: -Wdate-time
  failure.
...
```

## Reproducer

```console
docker run -it ubuntu:20.04
```
```bash
# Install NVHPC
apt -qqq update
apt install -y \
    build-essential     \
    ca-certificates     \
    cmake               \
    environment-modules \
    gnupg               \
    pkg-config          \
    wget

wget -q https://developer.download.nvidia.com/hpc-sdk/21.9/nvhpc-21-9_21.9_amd64.deb \
        https://developer.download.nvidia.com/hpc-sdk/21.9/nvhpc-2021_21.9_amd64.deb
apt install -y ./nvhpc-21-9_21.9_amd64.deb ./nvhpc-2021_21.9_amd64.deb
rm -rf ./nvhpc-21-9_21.9_amd64.deb ./nvhpc-2021_21.9_amd64.deb
apt install -y python3 python3-pip

source /etc/profile.d/modules.sh
module load /opt/nvidia/hpc_sdk/modulefiles/nvhpc/21.9

# Compile mpi4py
export CC=$(which nvc)
export CXX=$(which nvc++)

python3 -m pip install --upgrade pip setuptools wheel
python3 -m pip install --upgrade -v mpi4py
```
Extra info:
```bash
$ which mpicc 
/opt/nvidia/hpc_sdk/Linux_x86_64/21.9/comm_libs/mpi/bin/mpicc
$ which mpicxx
/opt/nvidia/hpc_sdk/Linux_x86_64/21.9/comm_libs/mpi/bin/mpicxx

$ mpicc --showme
nvc -I/opt/nvidia/hpc_sdk/Linux_x86_64/21.9/comm_libs/openmpi/openmpi-3.1.5/include -Wl,-rpath -Wl,$ORIGIN:$ORIGIN/../../lib:$ORIGIN/../../../lib:$ORIGIN/../../../compilers/lib:$ORIGIN/../../../../compilers/lib:$ORIGIN/../../../../../compilers/lib -Wl,-rpath -Wl,/opt/nvidia/hpc_sdk/Linux_x86_64/21.9/comm_libs/openmpi/openmpi-3.1.5/lib -L/opt/nvidia/hpc_sdk/Linux_x86_64/21.9/comm_libs/openmpi/openmpi-3.1.5/lib -lmpi

$ mpicxx --showme
nvc++ -I/opt/nvidia/hpc_sdk/Linux_x86_64/21.9/comm_libs/openmpi/openmpi-3.1.5/include -Wl,-rpath -Wl,$ORIGIN:$ORIGIN/../../lib:$ORIGIN/../../../lib:$ORIGIN/../../../compilers/lib:$ORIGIN/../../../../compilers/lib:$ORIGIN/../../../../../compilers/lib -Wl,-rpath -Wl,/opt/nvidia/hpc_sdk/Linux_x86_64/21.9/comm_libs/openmpi/openmpi-3.1.5/lib -L/opt/nvidia/hpc_sdk/Linux_x86_64/21.9/comm_libs/openmpi/openmpi-3.1.5/lib -lmpi_cxx -lmpi
```
`CFLAGS` and `CXXFLAGS` are empty.

I cannot spot where those GNU-ish flags come from in the pip/setuptools build logic...

**Comment by ax3l** [comment]
Are they somehow folded in from `python3 -c "import sysconfig; print(sysconfig.get_config_vars())"`?

**Comment by leofang** [comment]
IMHO this is a compiler problem; mpi4py could work around it, but life might be easier if you just add `-noswitcherror` to CFLAGS, see https://docs.nvidia.com/hpc-sdk/archive/20.7/compilers/hpc-compilers-user-guide/#cmdln-opt-syntax.

**Comment by ax3l** [comment]
I think adding `-noswitcherror` for the NVHPC compilers is a pretty valid approach here.

Do you know where exactly those GNU flags get added in the logic? Just curious.

**Comment by leofang** [comment]
> I think adding `-noswitcherror` for the NVHPC compilers is a good work-around here. Can we add this to `mpi4py`'s build logic somehow?

@dalcinl will make the final call here, but I don't remember if we customized for any particular compiler in the build system.

> I think that fundamentally, this is a python build system problem. Using Python from a different compiler is pretty safe in the C APIs/ABIs that are used here. There is no real fundamental reason, why the exact same optimizations/flags applied to the python executable would need to be applied to all modules. Do you know where exactly those GNU flags from Python's config get introduced in the logic? Just curious.

1. I tend to agree with you on the assessment of python's build system (either distutils or setuptools). They have many annoying problems. But build systems are generally hard to deal with.
2. I think it's a common practice, when constructing a distutil compiler object, to draw Python compile-time flags from `sysconfig` to know which Python to target against. IIUC this is how those flags appear. For example, we have this line:
https://github.com/mpi4py/mpi4py/blob/98174ae85f7ffaddf252b1e5343095208e29afd0/conf/mpidistutils.py#L88
that internally sets these flags.

**Comment by dalcinl** [comment]
The only customization is to replace the compiler command with `mpicc`, but other than that, no flags are added to build the core MPI extension module (except perhaps on Windows, for the case of MSVC).

I'm working on supporting scikit-build, which uses cmake, to provide an alternative build system. No ETA, though.

**Comment by dalcinl** [comment]
> I think adding `-noswitcherror` for the NVHPC compilers is a good work-around here.

```
CFLAGS=-noswitcherror pip install mpi4py
```

**Comment by ax3l** [comment]
Yes, that's the work-around I currently use, too:
https://github.com/ECP-WarpX/WarpX/pull/2379/files

**Comment by leofang** [comment]
@dalcinl @ax3l I suggest us to close this issue given that it's a unique issue to NVC++ and can be simply worked around. Feel free to open a new issue should there be any action items that I missed.
