### ISSUE TITLE
Allowing for parallel installation of multiple MPI implementations

### ISSUE THREAD

**Issue by drew-parsons** [mpi4py/mpi4py#133]
At https://github.com/mpi4py/mpi4py/pull/131/files#r742700593 we discussed whether it would be useful to allow mpi4py to provide for parallel MPI implementations at the same time.  This could serve two purposes.  First it could give users easier choice of which implementation they want. Secondly it could facilitate testing against multiple implementations.

One part of the challenge is that the python extension MPI.cpython-39-x86_64-linux-gnu.so links to one implementation but is not identified by file name which implementation it uses one.

In principle it would be easy enough to set up an implementation specific installation. Just move everything in mpi4py/* to an implementation subdir, mpi4py/openmpi/* or mpi4py/mpich/* (or mpi4py/intelmpi/*, etc).

Then toplevel `mpi4py/__init__.py` could be written to pull in a default implementation, such that `import mpi4py` and `from mpi4py import MPI` continue to work without users noticing.

Choice of implementation could be made with an environment variable, e.g. `MPI4PY_MPI_IMPLEMENTATION=mpich python3 -c "from mpi4py import MPI"` loads the mpich implementation. Alternatively the specific implementation could be accessed directly, `from mpi4py.mpich import MPI` or similar.

I've set up an analogue of this kind of installation with the Debian/Ubuntu packaging of h5py, which enables parallel installation of both the serial and mpi builds. Toplevel `__init__.py` loads the h5py serial build by default if running as a serial process, or the mpi build if an mpi environment is detected.  cf. https://salsa.debian.org/science-team/h5py/-/blob/master/debian/wrapper_module/h5py/__init__.py

This kind of installation could address some of the concerns @dalcinl raised at https://github.com/mpi4py/mpi4py/pull/131/files#r742720963 about needing root access to change the alternative preferred MPI implementation on Debian systems. The system administrator could have both implementations installed, then the user is free to select the non-default build with mpi4py.  I guess it could also be useful for local user pip installations too, if a user want access to multiple MPI implementations with their own installation.

**Comment by dalcinl** [comment]
Sorry, but perhaps I misunderstood your proposal. 

So far, I have zero interest on "solving" the MPICH vs Open MPI issue on mpi4py side. I do not want to make the usual mistake of adding support for runtime selection of "backends" that end up in careless users writing fragile spaghetti code for a homework that escalates to production and then lead to nasty issues that I have to pay attention to in GitHub issues, mailing list, and my personal inbox.

Until the MPI forum can be convinced about standardizing on an MPI ABI, I see this issue as a packaging problem. It should be done via alternatives, or environment modules, or environment variables combined with *.pth files.

For example, in my Fedora system:
```
$ module show mpi/mpich-x86_64 2>&1 | grep MPI_PYTHON3_SITEARCH
setenv("MPI_PYTHON3_SITEARCH","/usr/lib64/python3.9/site-packages/mpich")

$ cat /usr/lib64/python3.9/site-packages/mpich.pth
import sys, os; s = os.getenv('MPI_PYTHON3_SITEARCH'); s and (s in sys.path or sys.path.append(s))
```
and then any Python package that links to MPICH goes to `MPI_PYTHON3_SITEARCH`.

**Comment by drew-parsons** [comment]
OK, good to clarify intentions at the mpi4py source level.
Your method is kind of equivalent, installing in site-packages/mpich rather than site-packages/mpi4py/mpich and redirecting via .pth rather than `__init__.py`. 

If your intention is to avoid backend profileration in the main source, then it can handled at a packaging level with the sort of patching I gave to h5py.

**Comment by dalcinl** [comment]
If you Debian guys would do follow the Fedora approach or something similar, then the same rules would apply to h5py, mpi4py, or any other MPI-enabled package. You would just need `python[3]-mpich|openmpi` packages that would install the `mpich|openmpi.pth` files, note however you may want Open MPI to be the default, regardless of the `MPI_PYTHON{2|3}_SITEARCH` variable being set or not. Afterwards, all MPI-related packages wanting to support multiple MPIs jut need to adjust their build scripts to install in the `MPI_PYTHON{2|3}_SITEARCH` corresponding to the MPI implementation. There is no need at all to patch `__init__.py` files.

**Comment by PhilipVinc** [comment]
@drew-parsons Another way to solve this is to use the recently-released [MPITrampoline](https://github.com/eschnett/MPItrampoline). 

It is a tiny package that forwards MPI calls to an actual implementation, essentially providing a stable ABI to other packages so that they do not have to be rebuilt for different MPI implementations.

I'm soon going to experiment a bit with it and if you're interested I'll report back.

**Comment by drew-parsons** [comment]
Thanks @PhilipVinc .  Sounds like it would be complicated to integrate with mpi4py, but will be interesting to hear the results of your experiment nevertheless.

**Comment by leofang** [comment]
I think at least quite a few packages should/can be addressed in the same fashion: fftw/pyfftw, hdf5/h5py, mpi4py, etc.
