### ISSUE TITLE
srun broken in SLURM script on 3.1.2

### ISSUE THREAD

**Issue by berceanu** [mpi4py/mpi4py#141]
The SLURM script below stopped working when upgrading mpi4py from 3.1.1 to 3.1.2.

```
OPAL ERROR: Unreachable in file pmix3x_client.c at line 112
--------------------------------------------------------------------------
The application appears to have been direct launched using "srun", but OMPI was not built with SLURM's PMI support and therefore cannot execute. There are several options for building PMI support under SLURM, depending upon the SLURM version you are using:

   version 16.05 or later: you can use SLURM's PMIx support. This
   requires that you configure and build SLURM --with-pmix.

   Versions earlier than 16.05: you must use either SLURM's PMI-1 or
   PMI-2 support. SLURM builds PMI-1 by default, or you can manually
   install PMI-2. You must then build Open MPI using --with-pmi pointing
   to the SLURM PMI library location.

Please configure as appropriate and try again.
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
srun: error: thor: task 0: Exited with exit code 1
===========================================
#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=31200m          
#SBATCH --gres=gpu:1                   
#SBATCH --gres-flags=enforce-binding

module use $HOME/MyModules
module load mambaforge_pic/latest

export MPICH_GPU_SUPPORT_ENABLED=1
export FBPIC_ENABLE_GPUDIRECT=1

srun -n 1 python script.py
```

Additional info:

```
slurm 19.05.2
mpi4py 3.1.2
```

**Comment by dalcinl** [comment]
mpi4py knows nothing about SLURM. Something outside of mpi4py control happened. How did you install mpi4py? If you used pip, run `pip cache remove mpi4py` and try again. Did you notice the warning you are getting? Looks like you are using Open MPI without PMI support. From where did you get Open MPI? Additionally, locate mpi4py's `MPI.cpython*.so` extension module, run the `ldd` command on it, and try to figure out it is linked against the right MPI libraries form Open MPI.

BTW, looks like you are using Open MPI, however in your batch script you are exporting an environment variable related to MPICH. That's a red flag to me, your environment looks messed up.

**Comment by berceanu** [comment]
Hi @dalcinl , thank you for the prompt reply. I will try to answer your questions below.
I installed `mpi4py` from [Mambaforge](https://github.com/conda-forge/miniforge) via `mamba install mpi4py`. 
Regarding Open PMI, I have not installed it, and in fact `mpicc` returns
```
Command 'mpicc' not found, but can be installed with:

sudo apt install lam4-dev
sudo apt install libmpich-dev
sudo apt install libopenmpi-dev
```
The machine has Ubuntu 18.04 on it btw.

Once I load the `mambaforge` environment, I get
```
mpicc -v
mpicc for MPICH version 3.4.2
```

```
:~/software/pkg/mambaforge_pic/lib/python3.9/site-packages/mpi4py$ ldd MPI.cpython-39-x86_64-linux-gnu.so
        linux-vdso.so.1 (0x00007ffe55dd1000)
        libmpi.so.12 => /data/storage/berceanu/software/pkg/mambaforge_pic/lib/python3.9/site-packages/mpi4py/./../../../libmpi.so.12 (0x00007f19d7257000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f19d6e66000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f19d6ac8000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f19d68a9000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f19d66a1000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f19d7dd0000)
```

In conclusion, afaik there is no locally installed MPI implementation, apart from MPICH pulled inside the conda environment.
The strange thing is that if I delete the conda distribution and reinstall it, pinning `mpi4py` to `3.1.1`, everything works.

**Comment by dalcinl** [comment]
OK, so it looks like your conda environment is using MPICH (you should double check running `conda list`).
However, you are running under SLURM, and then you get these messages about Open MPI. So I do not really know what's going on. You should contact the support staff of your computing facility and ask for help, I'm not in a position to debug your issue, and this is most definitely not a mpi4py issue.

Perhaps you should use a MPICH installed in your system, make sure you read https://conda-forge.org/docs/user/tipsandtricks.html#using-external-message-passing-interface-mpi-libraries.

**Comment by dalcinl** [comment]
> The strange thing is that if I delete the conda distribution and reinstall it, pinning `mpi4py` to `3.1.1`, everything works

Can you share the exact command you are using to create your environment? Are you installing the `mpich` package explicitly?

**Comment by berceanu** [comment]
No, I am doing `mamba install mpi4py` in the first case, and `mamba install mpi4py=3.1.1` in the second. I guess `mpich` is automatically pulled in as a dependency.

**Comment by dalcinl** [comment]
> I guess `mpich` is automatically pulled in as a dependency.

```
$ python -m this | grep guess
In the face of ambiguity, refuse the temptation to guess.
```

Are you completely sure the first case (i.e., no pinning) the mpich package is being pulled in?

I believe this is some sort of environment variables issue. Add `echo $PATH`, and `ldd /path/to/mpi4py/MPI.cpython*.so` in your batch script. That output may help debug the issue.

**Comment by dalcinl** [comment]
@berceanu Any update?
