### ISSUE TITLE
Infinite run with possibly deadlock when running for larger MPI ranks

### ISSUE THREAD

**Issue by samcom12** [mpi4py/mpi4py#148]
Hi,

I'm trying to run a test case from 

https://github.com/anuga-community/anuga_core

It uses mpi4py for parallel processing.
I could run the test cases for the smaller number of processes say mpi ranks like 640, 1200.
I have tried it with MPICH and Intel MPI as backend.

With MPICH it exits from simulation with some messages like-

```
File "mpi4py/MPI/Comm.pyx", line 1406, in mpi4py.MPI.Comm.send
  File "mpi4py/MPI/msgpickle.pxi", line 212, in mpi4py.MPI.PyMPI_send
mpi4py.MPI.Exception: Other MPI error, error stack:
PMPI_Send(157).......: MPI_Send(buf=0x177e5c2e0, count=2078079, MPI_BYTE, dest=1051, tag=1, MPI_COMM_WORLD) failed
MPID_Send(467).......:
MPIDI_send_unsafe(39):
(unknown)(): Other MPI error

```

While with Intel MPI it keeps on doing work without generating any output.

You can refer to the thread here- 

https://github.com/anuga-community/anuga_core/issues/10#issue-1047037190

**Comment by dalcinl** [comment]
@samcom12 What should we do with this issue? Is there any action to take on mpi4py side? Looks like the problem is in the backend MPI implementation or system, and not mpi4py.
