### ISSUE TITLE
mpi4py.futures.MPIPoolExecutor hangs at comm.Disconnect() inside client_close(comm)

### ISSUE THREAD

**Issue by KyuzoR** [mpi4py/mpi4py#15]
### Background information
mpi4py 3.0.3
PyPy 7.3.3 (Python 2.7.18)
Intel MPI Version 2019 Update 8 Build 20200624
GNU/Linux 3.10.0-1160.11.1.el7.x86_64
slurm 20.02.5

### Details of the problem
Sample code
```
from mpi4py import MPI
import mpi4py.futures as mp
import sys

def write(x):
    sys.stdout.write(x)
    sys.stdout.flush()

def fun(args):
    rank = MPI.COMM_WORLD.Get_rank()
    return rank
    
if __name__ == '__main__':
    size = MPI.COMM_WORLD.Get_size()
    rank = MPI.COMM_WORLD.Get_rank()
    for i in range(size):
        MPI.COMM_WORLD.Barrier()
        if rank == i:
            write('Parent %d\n' % rank)
            with mp.MPIPoolExecutor(2) as pool:
                write(', '.join(map(str, pool.map(fun, range(2)))) + '\n')
```
```
shell$ srun -N 16 --ntasks-per-node 2 --pty /bin/bash -l
shell$ mpirun -ppn 1 ./test_mpi.py
Parent 0
0, 1
```
It hangs here. When I traced the function calls, I found the problem at `futures/_lib.py` -> `def client_close(comm):` -> `comm.Disconnect()`
Similarly, when the `with` statement is replaced with an assignment statement and `pool.shutdown()` is called after the `for` loop, all the processes print their messages correctly but the program still hangs at `comm.Disconnect()`.
A similar C code version of this code does not produce this problem.

**Comment by dalcinl** [comment]
Are you sure that's the proper way to use `srun` for codes that use `MPI_Comm_spawn()` to spawn child MPI processes? Can you show me a trivial C code example using `MPI_Comm_disconnect()`, including the `srun` invocations you use to run it?

Your `mpirun ...` invokation is not using `python`, just the script `./test_mpi.py`. And the code in `test_mpi.py` does not start with a shebang `#!/usr/bin/env python` or something like that. So This makes me think that you example code is incomplete.
Perhaps you have good reasons for it, but the structure of your code under `if __name__ == '__main__':` is suspicious. Just in case, read mpi4py.futures documentation and how you should use it. In particular, read [this section](https://mpi4py.readthedocs.io/en/stable/mpi4py.futures.html#command-line) for ways to workaround issues with dynamic process management and batch schedulers like SLURM.

Perhaps you can try let say `mpiexec -n 1 python demo/nxtval/nxtval-dynproc.py` (this example spawns just one child process) and tell me whether it works or not?

So far, I have no indication that your issues are mpi4py's fault.

**Comment by dalcinl** [comment]
> PyPy 7.3.3 (Python 2.7.18)

Can you try your example code with CPython rather than PyPy?

**Comment by KyuzoR** [comment]
1) The compute cluster I'm using has login nodes and compute nodes. The above `srun` command is there to request an allocation of 16 nodes with 2 cores each, and an interactive shell to run commands on compute nodes. Simply put, it's just an ssh to one of the allocated compute nodes. `mpirun` can access all the allocated nodes.

2) I attached test_mpi.c [here](https://github.com/mpi4py/mpi4py/files/5845232/test_mpi.zip)
```
login-node$ srun -N 16 --ntasks-per-node 2 --pty /bin/bash -l
compute-5-1$ module load intel
compute-5-1$ mpiicc -std=gnu99 test_mpi.c -o test_impi
compute-5-1$ mpirun -ppn 1 ./test_impi
Parent 0
Child 0 of parent 0
Child 1 of parent 0
Parent 1
Child 0 of parent 1
Child 1 of parent 1
Parent 2
Child 1 of parent 2
Child 0 of parent 2
...
```
and so on, and it exits correctly.

3) I do have a shebang in my Python file, but I omitted it in the above because it has a full path to my PyPy installation in my home directory. You can assume that I have at the beginning of the file `#!/bin/pypy` with a different path, and that I ran `chmod +x test_mpi.py`.

4) To make the Python code less suspicious, what I intend to do is to `mpirun` 1 process per node `-ppn 1` then, for each of these parent processes, spawn additional processes with `MPIPoolExecutor` mapped/bound to the cores of the respective node of the parent process. I know I can do that with `mpi_info={'host': MPI.Get_processor_name().split('.', 1)[0], 'map_by': 'core', 'bind_to': 'core'}`. But this detail didn't seem to make a difference for this issue. Either way, the node/core mapping is done correctly, I checked.

5) `mpiexec -n 1 pypy nxtval-dynproc.py` on a compute node gave
```
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 40433 RUNNING AT compute-5-1
=   KILLED BY SIGNAL: 11 (Segmentation fault)
===================================================================================
```

6) I compiled CPython 2.7.18 then pip installed mpi4py. Same results for both Python codes.

**Comment by dalcinl** [comment]
OK, something fishy is going on here. The `nxtval-dynproc` should have worked, it is a trivial example using MPI process spawning. I just tried it on my workstation using mpi4py/master, PyPy 7.3.1, and MPICH 3.3.2.

Let's try first your C code. It is indeed similar, but there is a very important difference. Please replace:

```
MPI_Init(&argc, &argv);
```

with

```
int provided;
MPI_Init_thread(NULL, NULL, MPI_THREAD_MULTIPLE, &provided);
```

Additionally, you are cheating, you should disconnect the intercomm you get from Spawn as shown below:

```
MPI_Comm_spawn(argv[0], MPI_ARGV_NULL, NUM_SPAWNS, MPI_INFO_NULL, 0, MPI_COMM_SELF, &intercomm, errcodes);
...
MPI_Comm_disconnect(&intercomm);
```


Does your C code still work with these changes?

**Comment by KyuzoR** [comment]
`you are cheating`. My bad.

The C code still works with the suggested changes. I even added `MPI_Intercomm_merge()` then `MPI_Send()` the children's ranks to their respective parents, and it worked. New code [here](https://github.com/mpi4py/mpi4py/files/5852100/test_mpi.zip).

**Comment by dalcinl** [comment]
I'm running out of ideas. 

1. Can you install from a git checkout, and add a few `printt()`s around (I mean before and after) the `comm.Disconnect()` calls at both the client and server side? 

2. What happen if you run the following line `MPIPoolExecutor(2).bootup().shutdown()`? Does it work or it still blocks at `comm.Disconnect()` time?

3. If you replace `comm.Disconnect()` with `comm.Free()`, does it work?

4. Did you try using a different MPI implementation? You can even do a quick try using a throw-away Miniconda install with packages from the conda-forge channel.

Sorry I cannot be more helpful. I still believe that the issue is on the side of your MPI implementation/batch system, although I have no idea what could be wrong. I'm still surprised that the `nxtval-dynproc.py` example does not work on your side. `mpi4py.futures` test suite runs on three different platforms under many Python versions and 100% test coverage. While I cannot claim the code is bug free, I can tell you that 99.9% of the questions/issues/bug reports I've got in 15 years were not mpi4py's fault.

**Comment by KyuzoR** [comment]
About `nxtval-dynproc.py`. The `SIGSEGV` is caused by the use of `any_src = MPI.ANY_SOURCE` in `incr = parent.recv(None, any_src, any_tag, status)`. When I change `any_src` to `0`, execution proceeded only to be hang at `parent.Disconnect()`

**Comment by dalcinl** [comment]
OK, Let's try something. Start with nxtval-dynproc as a template, remove all send()/recv() calls, just leave the Spawn()/Get_parent() and Disconnect() calls, remove everything else, such that the Python code is similar to your C code, but no communication between proceses before Disconnect().  What happens then?

**Comment by KyuzoR** [comment]
After doing away with the `send()`/`recv()` calls in `nxtval-dynproc.py`, execution does not hang at `Disconnect()`.
Replacing `send()`/`recv()` with `Send()`/`Recv()` (e.g. `self.child.Send([array.array('I', [0]), 1, MPI.INT], 0, 1)`) solves the problem for `nxtval-dynproc.py` even when `any_src = MPI.ANY_SOURCE`.

P.S.: I discovered yesterday that my environment setup requires the use of
```
import mpi4py
mpi4py.rc.recv_mprobe = False
```
This might hint to something.

**Comment by KyuzoR** [comment]
About your 4 sugguestions:

2) After replacing the last 2 lines in the first Python code with
`MPIPoolExecutor(2).bootup().shutdown()`
`write('%d OK\n' % rank)`
all the OKs are printed, but the execution still hangs at the end.

3) After replacing `comm.Disconnect()` with `comm.Free()` in both `def server_close(comm):` and `def client_close(comm):` the whole issue disappears.

4) The only other MPI implementation available on the cluster is OpenMPI 4.0.4 but it has UCX issues that I previously reported to OpenMPI [here](https://github.com/open-mpi/ompi/issues/8385). And re-pip-installing mpi4py with the OpenMPI module loaded, only raised the UCX issue again.
Just for fun, I tried to install mpi4py with Miniconda and the intel module loaded. Then `from mpi4py import MPI` got `ImportError: /path-to-home-folder/.local/lib/python2.7/site-packages/mpi4py/MPI.so: undefined symbol: PyUnicodeUCS2_Compare`

1. I uninstalled mpi4py then `pypy -m pip install git+https://github.com/mpi4py/mpi4py.git`. Then I added `sys.stdout.write(string_to_print)` before and after `comm.Disconnect()` in both `def server_close(comm):` and `def client_close(comm):`. With the first Python code, with parent 0, `server_close()` is called, then `client_close()` is called and returns, then `server_close()` is called again before the first call has returned, then everything else freezes.

**Comment by dalcinl** [comment]
Oh, boy... your comments about `mpi4py.rc` remembered me of [this issue](https://software.intel.com/content/www/us/en/develop/articles/python-mpi4py-on-intel-true-scale-and-omni-path-clusters.html)
with Intel MPI.

You are setting `recv_mprobe` to False, so you are doing the right thing. However, there is a big problem. You cannot really set `recv_mprobe` in the worker processes, so all the workers processes keep using the default setting.

This lack of ability to use `mpi4py.rc` to configure the worker processes in certainly a deficiency of `mpi4py.futures`. I should probably allow changing these runtime configuration settings using environment variables.

For the time being, I recommend hot fixing `mpi4py/__init__.py` and set `recv_mprobe` to false. You can do it on a git checkout and install, or you can just do it directly in the install location. Let's see if this fix your issues. Maybe not. Otherwise, you can try using `comm.Free()` rather than `comm.Disconnect()`

**Comment by KyuzoR** [comment]
`recv_mprobe = False` in `mpi4py/__init__.py` solves the issue.

Yeah, I found out about `mpi4py.rc.recv_mprobe = False` the hard way. It and/or the link in your comment should probably be mentioned somewhere like in `README.rst` (_Known issues_ maybe?)

**Comment by samcom12** [comment]
@dalcinl  Is it documented somewhere?

**Comment by dalcinl** [comment]
@samcom12 A quick Google search for *recv_mprobe* should point you to the docs. It is documented [here](https://mpi4py.readthedocs.io/en/stable/mpi4py.html#mpi4py.mpi4py.rc.recv_mprobe) and [here](https://mpi4py.readthedocs.io/en/stable/mpi4py.html#envvar-MPI4PY_RC_RECV_MPROBE). Setting the environment variable is a quick way to workaround the issue in production, without requiring code modifications to set ` mpi4py.rc.recv_mprobe = False`.

You may think the documentation is lacking, and I would agree with that view. However, I consider this *recv-with-matched-probe* approach an internal implementation detail of mpi4py,. Users should not have to be aware of it if the backend MPI implementations did their job. As they don't, I added this runtime config parameter to disable it at the expense of thread safety.

@KyuzoR I would not care about a *Known Issues* being added in some wiki page. I just don't want to be responsible for maintaining it, it is depressing. Will anyone volunteer? Sorry if I sound harsh and impolite, but I'm a bit tired of dealing with MPI implementation bugs. In more than 15 years, and after hundreds of bug reports (and some angry emails sent in private to me), the actual bug count in mpi4py codebase is less than ten.
