### ISSUE TITLE
Warn users if mpi4py running under different MPI implementation

### ISSUE THREAD

**Issue by PhilipVinc** [mpi4py/mpi4py#155]
It does happen to unexperienced users that they run pacakges using `mpi4py` under an MPI implementation different from the one that mpi4y was built with.

MPI.jl, the analogue of mpi4py in Julia land, [tries to warn users](https://github.com/JuliaParallel/MPI.jl/blob/cafcc04330722da8c0b5f4c679eba0373cff40fb/src/environment.jl#L30) if this happens by detecting at `MPI_INIT` time if `MPI_COMM_WORLD` reports only 1 rank but the known environment variables (`MPI_LOCALNRANKS`, `OMPI_COMM_WORLD_SIZE`) suggest that there should be more than 1 rank. This happens exactly when `mpi4py` would be built with mpich but run under open-mpi.

If this condition is detected it prints a warning.

What do you think about doing this? Is it something that you would merge into mpi4py?

**Comment by dalcinl** [comment]
As a general rule, I do not like to add code that is specific to MPICH or Open MPI, unless strictly necessary to workaround bugs in the implementations. However, I understand this issue of using the wrong `mpiexec` is quite common, particularly in Ubuntu systems. I would merge something like this in mpi4py, although I think we may need a slightly better warning message than `MPI.jl` (I need to think about it, but I cannot until mid January). Also, we should figure out how this could work with workload managers like SLURM and/or PMI.

PS: This approach should be tested with `ompi/master`, they are changing mpiexec's implementation, I'm not sure things will work as with v4.x releases.

**Comment by leofang** [comment]
I think we should record the build-time MPI info as a version string or something, and try to make a comparison with the runtime info. The second step is what's hard here, as there's not much runtime query API we can use here (similar to the situation in #162).

**Comment by dalcinl** [comment]
> I think we should record the build-time MPI info

Bad move. Enforcing things this way could break the MPICH ABI initiative. In conda-forge, we may build mpi4py with a MPICH or Open MPI release that does not necessarily match the one being used at runtime.

I believe @PhilipVinc's proposed approach is better, although it may require a little more work to handle other process managers and schedulers.

**Comment by leofang** [comment]
Sure, from the packaging perspective it may be an issue if we pin the exact version, but I didn't mean to do this. First, at least during runtime checks we can just compare the major version and the ABI compatibility would be honored for known MPI implementations that support it (= excluding Open MPI). Second, there are circumstances in which people want to pin exactly, for example I would do this if I were the cluster admin that builds packages for my users. It'd be an extra safe guarding against misfired `module load` commands.

That said, I still don't know how to check the runtime info so the discussion may be moot.

I actually don't understand how the MPI.jl solution works. The env vars might be unset, or not recognized by a particular MPI implementation. Could you elaborate?

**Comment by dalcinl** [comment]
@leofang These envars are set by the `mpiexec` command in each process it executes, and then the MPI library takes over to assign a rank to `MPI_COMM_WORLD`. If mpiexec is not used (or one from a different implementation is used), then the expected environ vars are not set and the MPI library assumes a *singleton MPI_Init()* case, thus bootstrapping a sequential run (world size 1). 

If there is a mismatch between the size of `MPI_COMM_WORLD` and these environment variables, you can reasonably assume that users are messing up: the `mpiexec` command does not match the MPI library. Did I make myself clear enough or should I provide a specific example using the command line?

**Comment by leofang** [comment]
Thank you, Lisandro. I wasn't aware of this bootstrapping mechanism. But how about differentiating between MPIs from the same derivative family, ex: Open MPI vs Spectrum MPI, or MVAPICH vs MPICH? I assume they'd set the same set of env vars (idk)?

**Comment by dalcinl** [comment]
Most likely, you cannot differentiate MPIs from the same family. I expect these sibling MPIs to use the same bootstrapping mechanism. I believe the intention here is to just detect gross mismatches between `mpiexec` and `libmpi.so` when they belong to disparate implementations like MPICH and Open MPI.

**Comment by dalcinl** [comment]
@PhilipVinc After some research, I figured out that `MPI.jl` is not doing the right thing. 

The meaning of `MPI_LOCALNRANKS` in MPICH (number of MPI ranks per compute node) is not the same as `OMPI_COMM_WORLD_SIZE` in Open MPI (number of ranks in MPI_COMM_WORLD). Unfortunately, MPICH does not provide a specific environment variable telling the size of COMM_WORLD. 

MPICH does set `PMI_SIZE`, but I do not consider that variable specific enough to MPICH, as the PMI protocol is used beyond MPICH. 

Thus, I don't know how to implement your request without risking a bogus warning.

@hzhou I'd love to know you opinion in this matter.

**Comment by hzhou** [comment]
@dalcinl PMI is where MPI gets the world information, so PMI should be where to find your solution. Unfortunately, PMI was never standardized as MPI did. Everyone used adopt PMI, especially PMI-1. The trouble was MPICH kept PMI library internal as part of `libmpi`, so every third party maintained their own PMI, often based on (old) code from MPICH. We are about to release MPICH 4.1a1, and starting with this release, we will also release `libpmi`, which any third party can link and use the PMI interface to query the world environment. Slrum and HPE (Cray) already releases `libpmi`.

OpenMPI uses PMIx. It used to have a PMI (v1 and v2) compatibility layer, but are removed now (I believe starting OpenMPI 5.0). So with OpenMPI, PMIx. At some point, we probably will add an PMIx compatibility interface as well, until then...

I definitely think a unified PMI will be a boom for users. Make the demand louder :)

**Comment by hzhou** [comment]
Just read the backlog and the issue was to find out MPI implementations? We release `mpichversion` for that. Not sure whether vendors do that as well. In our test suite configure, I simply enable `MPIR_CVAR_DEBUG_SUMMARY` and then check hot words from output to check details, mainly to detect which netmod are enabled so we can test netmod specific features. Unfortunately, that CVAR is pretty new and vendors likely haven't picked it up yet.

**Comment by dalcinl** [comment]
@hzhou I believe you did not get the the issue right. The problem we are trying to address is the following: Sometimes users (particularly beginners) have messed up environments, and they end up using `mpiexec` from let say Open MPI, while the executables/libraries/py-modules they are using were built with MPICH. So what we are trying to figure out is a way to detect this mismatch at runtime and warn users about it. There are many ways to do it. One way would be to `dlopen()` and lookup for know symbols, but that's a bit intrusive and injects a reliance/dependency in dynamic loading. Another way is to look up for know and implementation-specific environment variables. Open MPI's mpiexec sets `OMPI_COMM_WORLD_SIZE`, but AFAICT, MPICH's mpiexec does not set anything specific to MPICH (and as you said, PMI had become ubiquitous, so I don't think `PMI_SIZE` is specific enough). 

A few lines of code are worth hundred words, so please look at [MPI.jl](https://github.com/JuliaParallel/MPI.jl/blob/master/src/environment.jl#L27), we are trying to do the same, but I believe using `MPI_LOCALNRANKS` is incorrect.

**Comment by hzhou** [comment]
You are making assumptions that MPICH only works with hydra. MPICH can be configured to work with Slurm, Cray's aprun, and even openmpi's mpiexec (by configuring MPICH to use `mpix`). So simply check whether `mpiexec` is from e..g `hydra` is not correct. In particular, to run MPICH on Slurm or Cray clusters are very common.

Let me try clarify the issue:
* Users built py-modules with specific MPI implementations. I believe `mpi4py` always knows which it is, right?
* `mpi4py` want know whether a process manager (`mpiexec`) will work with the linked MPI implementation. This is simply a question whether the process manager use consistent PMI as the MPI library. For this, the ("only" IMO) way is to call `PMI_Init`  (the one the MPI implementation uses) and check for returns. If `PMI_Init` succeeds, there is a high chance that both speak the same PMI. As long as they speak the same PMI, it will work. Unfortunately, there is still nuisances beyond `PMI_Init`, but that is more of a dialect issue.

**Comment by hzhou** [comment]
> A few lines of code are worth hundred words, so please look at [MPI.jl](https://github.com/JuliaParallel/MPI.jl/blob/master/src/environment.jl#L27), we are trying to do the same, but I believe using `MPI_LOCALNRANKS` is incorrect.

I guess you are worried that "seeing `MPI_LOCALNRANKS`" and rejecting an openmpi linked py-module is wrong?

**Comment by dalcinl** [comment]
> I guess you are worried that "seeing `MPI_LOCALNRANKS`" and rejecting an openmpi linked py-module is wrong?

Let me put down an explicit example. In a multinode run with only one MPI process per node, MPICH's mpiexec would set `MPI_LOCALNRANKS=1`, right? If the py-module (or a Julia module) is linked against Open MPI, then the size of `MPI_COMM_WORLD ` is also 1,  Open MPI will start in singleton mode, as it knows nothing about MPICH's mpiexec, but then the logic in `MPI.jl` that I referenced above will fail to detect the mismatch between mpiexec and the MPI library.

I'm not a big fan of supporting non-standard stuff, much less if I cannot make it work consistently in all scenarios. And there I am, wondering how could I manage to detect these runtime mismatches robustly. If MPICH's mpiexec would set an environment variable let say `MPICH_COMM_WORLD_SIZE=<n>` where `<n>` is the size of MPI_COMM_WORLD (just like Open MPI does), then things would be straightforward, but that's not the case.

**Comment by hzhou** [comment]
> > I guess you are worried that "seeing `MPI_LOCALNRANKS`" and rejecting an openmpi linked py-module is wrong?
> 
> Let me put down an explicit example. In a multinode run with only one MPI process per node, MPICH's mpiexec would set `MPI_LOCALNRANKS=1`, right? If the py-module (or a Julia module) is linked against Open MPI, then the size of `MPI_COMM_WORLD ` is also 1, Open MPI will start in singleton mode, as it knows nothing about MPICH's mpiexec, but then the logic in `MPI.jl` that I referenced above will fail to detect the mismatch between mpiexec and the MPI library.
> 

If you are not seeing `OMPI_COMM_WORLD_SIZE`, then you know you are not launched by OpenMPI's mpiexec, right? And if you are seeing `MPI_LOCALNRANKS`, you know it is not a singleton init case. What am I missing?

> I'm not a big fan of supporting non-standard stuff, much less if I cannot make it work consistently in all scenarios. And there I am, wondering how could I manage to detect these runtime mismatches robustly. If MPICH's mpiexec would set an environment variable let say `MPICH_COMM_WORLD_SIZE=<n>` where `<n>` is the size of MPI_COMM_WORLD (just like Open MPI does), then things would be straightforward, but that's not the case.

If your purpose is to check COMM_WORLD size, then `PMI_SIZE` is the correct variable to check. The world size is given by process manager, should not have direct relationship to MPI library. Today not all process manager speak to all MPI libraries is just a issue of not having standard PMI language, it is not an argument that you should tie PMI behavior to MPI libraries.

If your purpose is to check compatible process manager and MPI library, or more specifically, to detect the know mismatch cases, then checking known mismatch environment variable should work, right?

**Comment by dalcinl** [comment]
> Today not all process manager speak to all MPI libraries is just a issue of not having standard PMI language, it is not an argument that you should tie PMI behavior to MPI libraries.

I know and agree. That's the reason I did not ask for any action to be taken from any MPI implementor's side :-).

> If your purpose is to check compatible process manager and MPI library, or more specifically, to detect the know mismatch cases, then checking known mismatch environment variable should work, right?

OK, so your suggestion is to just check for the variables being set, without caring about its actual value, and use that declare mismatch between mpiexec and library. That's reasonable enough.

**Comment by dalcinl** [comment]
Open MPI can also use PMI v1 or v2. This is the reason I cannot rely on PMI environ vars without risking false positives: https://slurm.schedmd.com/mpi_guide.html#open_mpi

`MPI_LOCALNRANKS` is available in MPICH 3.3+. For older releases, looks like I do not have a robust way to perform the mpiexec sanity check we are looking for.

**Comment by dalcinl** [comment]
@hzhou I just noticed that `mpiexec.gforker` does not set `MPI_LOCAL{NRANKS|RANKID}`. I'm using MPICH 3.4.1 from Fedora 35, but the difference is probably still there in v4.0 and main?

**Comment by hzhou** [comment]
As I said, the reliable way to check PMI is through PMI. We are about to release mpich 4.1a1, which will have a separate `libpmi` package that third-party can directly use. A simple call to `PMI_Init` should reveal enough information on the PMI versions and compatibility. We haven't changed the PMI protocols ever, so it should work all the way back to old releases.
