### ISSUE TITLE
Reducev

### ISSUE THREAD

**Issue by calebwin** [mpi4py/mpi4py#156]
It would be amazing if there was a Reducev for reducing variable-sized data. This GitHub gist - https://gist.github.com/rmcgibbo/7178576 - looks like a good starting point.

**Comment by dalcinl** [comment]
You have provided absolutely zero hints about the precise semantics of the `Reducev()` function/method you are proposing. What do you mean exactly by "variable-sized" data? Is it about array-like data? Would that function make sense  in C or Fortran, or would it be something Python-specific?
 
mpi4py's lowercase `Comm.reduce()` method can reduce arbitrary Python objects using any user-defined binary function as the reduce operation. The [implementation](https://github.com/mpi4py/mpi4py/blob/master/src/mpi4py/MPI/msgpickle.pxi#L1072) uses send/recv on a binary tree, just like in the link you provided.
For example, you could pass list objects of variable lenght in each process, and then call `reduce()` passing `op=lambda a,b: a+b`, and you would get in the return the concatenation (in MPI rank order) of all the lists. Is it something like this what you are talking about?

 I'm not a big fun of adding random features outside the MPI standard to please individual needs with ad-hoc solutions.

**Comment by calebwin** [comment]
Hello @dalcinl 

I appreciate your detailed response and am sorry for not providing specifics on what I mean by "variable-sized". My question is basically - is mpi4py's `MPI.reduce` capable of handling Python objects of different sizes on different ranks? It sounds like the answer is yes looking at the [implementation](https://github.com/mpi4py/mpi4py/blob/master/src/mpi4py/MPI/msgpickle.pxi#L1072) but I just want to confirm.

And I 100% agree that mpi4py should not have anything outside the MPI standard.

Thank you for developing mpi4py and I appreciate your valuable time on this thread.

**Comment by dalcinl** [comment]
> is mpi4py's `MPI.reduce` capable of handling Python objects of different sizes on different ranks?

Yes, it is! By default the operation is `MPI.SUM`, which for Python object translates to the binary operator `+`. For example, if you `reduce()` variable-size strings, then you get the concatenated string as a result. Again, for lowercase `reduce()` you can define your own operation, a Python callable is enough, no need to define a new `MPI.Op` object.

**Comment by calebwin** [comment]
Awesome! Thank you so much
