### ISSUE TITLE
Cannot install mpi4py after latest release of setuptools: module 'setuptools._distutils.cygwinccompiler' has no attribute 'get_versions'

### ISSUE THREAD

**Issue by EnricoMi** [mpi4py/mpi4py#160]
With the latest release of setuptools (60.1.0), I cannot install mpi4py any more.

I have initially raised this issue with [setuptools](https://github.com/pypa/setuptools/issues/2969), but it looks like this fails in [conf/mpidistutils.py](https://github.com/mpi4py/mpi4py/blob/master/conf/mpidistutils.py).

```
$ pip install -v mpi4py
Using pip 21.3.1 from .../venv-mpi4py/lib/python3.8/site-packages/pip (python 3.8)
Collecting mpi4py
  Using cached mpi4py-3.1.3.tar.gz (2.5 MB)
  Running command .../venv-mpi4py/bin/python /tmp/pip-standalone-pip-fmkquq0f/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-nun8azx9/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 40.9.0' wheel
  Collecting setuptools>=40.9.0
    Using cached setuptools-60.1.0-py3-none-any.whl (952 kB)
  Collecting wheel
    Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
  Installing collected packages: wheel, setuptools
  Successfully installed setuptools-60.1.0 wheel-0.37.1
  Installing build dependencies ... done
  Running command .../venv-mpi4py/bin/python .../venv-mpi4py/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmputajppc5
  Traceback (most recent call last):
    File ".../venv-mpi4py/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File ".../venv-mpi4py/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File ".../venv-mpi4py/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-nun8azx9/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-nun8azx9/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-nun8azx9/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 462, in <module>
      from mpidistutils import setup
    File "/tmp/pip-install-k7kbt967/mpi4py_fa187d0418384267943227507227365d/conf/mpidistutils.py", line 29, in <module>
      cygcc_get_versions = cygcc.get_versions
  AttributeError: module 'setuptools._distutils.cygwinccompiler' has no attribute 'get_versions'
  Getting requirements to build wheel ... error
```

So mpi4py should restrict build dependency to `setuptools<60.1.0` or fix this issue. As it stands now, installing latest released mpi4py versions does not work.

**Comment by dalcinl** [comment]
@EnricoMi See #157 and #159. 

While #159 fix the issue, I was not planning on making a new 3.1.x release. But if I don't, people will keep reporting this problem back to me. I do not expect setuptools to do anything about it, I rather expect things to keep breaking in the future, over and over again. So I may surrender eventually, and release mpi4py 3.1.4. But that will not happen until at least mid January 2022.

**Comment by EnricoMi** [comment]
I recommend pinning one of those closed issues as I was looking for related issues, but did not look at closed ones, because the issue still persists. With pinned issues, it is easier to find those hot issues quicker, especially if they are closed. Thanks for clarifying the issue.

One thing you could do is pinning the setuptools version for your releases and upgrade to the latest working on every release. With this setuptools cannot break released versions of mpi4py anymore.

Further, is there a workaround? With virtualenv, installing a working setuptools version does not fix the issue as mpi4py installs build dependencies no matter what and breaks. Installing setuptools==60.0.4 into the system works but is not ideal for many situations.

**Comment by dalcinl** [comment]
> I recommend pinning one of those closed issues

Done

> One thing you could do is pinning the setuptools version for your releases and upgrade to the latest working on every release. With this setuptools cannot break released versions of mpi4py anymore.

I know this is the usual approach for apps, but installing mpi4py is not an "app". This approach is not future-proof regarding Python versions to come, new OS distributions, etc.

> Further, is there a workaround?

Not that I know. pip's `-c/--constraint` options does not seem to apply to build dependencies from `pyproject.toml`.

**Comment by dalcinl** [comment]
@EnricoMi This is a possible [workaround](https://github.com/mpi4py/mpi4py/issues/157#issuecomment-1001022274). Could you please double-check?

**Comment by EnricoMi** [comment]
@dalcinl works for me, thanks for sharing!

**Comment by alan-man** [comment]
Same issue here with python 3.8, ubuntu 20.04
Trying the work around...

**Comment by EnricoMi** [comment]
@dalcinl looks like that breaking change was unintentional and is going to be reverted: https://github.com/pypa/setuptools/issues/2969#issuecomment-1002186809

**Comment by dalcinl** [comment]
@EnricoMi Many thanks for your help and followup on this issue. I added my own comments. While it is true I could make a new release with the hotfix for the issue, it is also true that setuptools would not be able to install any of the older mpi4py releases, and users may have legitimate reasons to do that. So I truly believe setuptools should provide some sort of fix, even if just adding a line `def get_versions(): raise RuntimeError("no longer supported")`.
