### ISSUE TITLE
mpi4py.MPI problem

### ISSUE THREAD

**Issue by seaninho94** [mpi4py/mpi4py#175]
Hi, I'm using the CentOS system with MPICH installed and I have tried to download mpi4py using conda. Everything seems to work fine, but if I open python with my terminal I can import mpi4py but it gives me an error if I import mpi4py.MPI. The error is this: ImportError: limp.so.12: cannot open shared object file: No such file or directory. How can I solve this issue?

Thank you in advance,

Sean

**Comment by dalcinl** [comment]
Have you read the [documentation](https://conda-forge.org/docs/user/tipsandtricks.html#using-external-message-passing-interface-mpi-libraries) about how to use an external MPICH with conda-forge packages?

**Comment by dalcinl** [comment]
@seaninho94 Any updates?
