### ISSUE TITLE
KeyError with mpi4py.MPI.message_basic with explicit little endianness set

### ISSUE THREAD

**Issue by anjakefala** [mpi4py/mpi4py#177]
This was pretty time-consuming to wrap my head around, so I am posting this issue to hopefully save others some time! 
This issue is related to: https://github.com/mpi4py/mpi4py/issues/81

Thanks for all of your work on this project. =) The lab I am part of uses `mpi4py` for our distributed analyses.

I do not understand enough about the complexities of broadcasting, and computer architectures, to know if handling my issue is something that would be good for the project (i.e. if allowing numpy datastructured with explicit endian-ness set makes sense), but it would have been helpful to add some error-handling there with clearer messaging so that I could immediately understand why my numpy datastructure was failing to broadcast, and adjust things in my code.

Test Case:

```
import sys
import numpy as np
import mpi4py
from mpi4py import MPI


comm = MPI.COMM_WORLD

if comm.rank == 0:
    print("--- Info ---")
    print(f"{mpi4py.__version__=}")
    print(f"{sys.byteorder=}")
    print()
    print("--- Starting Bcast with numpy native endianness set ---")
comm.Barrier()


a = np.arange(10).astype(np.float64)
print(f"{comm.rank=}: {a.dtype=}, {a.dtype.str=}, {a.dtype.byteorder=}")
comm.Bcast(a, root=0)

comm.Barrier()
if comm.rank == 0:
    print("Success")
    print()
    print("--- Starting Bcast with explicit little endianness set ---")
comm.Barrier()

a = np.arange(10).astype(np.float64)
a = a.newbyteorder("<")
print(f"{comm.rank=}: {a.dtype=}, {a.dtype.str=}, {a.dtype.byteorder=}")
comm.Bcast(a, root=0)

comm.Barrier()
if comm.rank == 0:
    print("---")
```

Output:

```
mpirun -np 2 python testb.py
--- Info ---
mpi4py.__version__='3.1.3'
sys.byteorder='little'

--- Starting Bcast with numpy native endianness set ---
comm.rank=0: a.dtype=dtype('float64'), a.dtype.str='<f8', a.dtype.byteorder='='
comm.rank=1: a.dtype=dtype('float64'), a.dtype.str='<f8', a.dtype.byteorder='='
Success

--- Starting Bcast with explicit little endianness set ---
comm.rank=0: a.dtype=dtype('<f8'), a.dtype.str='<f8', a.dtype.byteorder='<'
comm.rank=1: a.dtype=dtype('<f8'), a.dtype.str='<f8', a.dtype.byteorder='<'
Traceback (most recent call last):
  File "/Users/richard/Projects/CHIME/quick/mpi4py_endian/testb.py", line 32, in <module>
Traceback (most recent call last):
  File "/Users/richard/Projects/CHIME/quick/mpi4py_endian/testb.py", line 32, in <module>
    comm.Bcast(a, root=0)
  File "mpi4py/MPI/Comm.pyx", line 690, in mpi4py.MPI.Comm.Bcast
    comm.Bcast(a, root=0)
  File "mpi4py/MPI/Comm.pyx", line 690, in mpi4py.MPI.Comm.Bcast
  File "mpi4py/MPI/msgbuffer.pxi", line 531, in mpi4py.MPI._p_msg_cco.for_bcast
  File "mpi4py/MPI/msgbuffer.pxi", line 534, in mpi4py.MPI._p_msg_cco.for_bcast
  File "mpi4py/MPI/msgbuffer.pxi", line 495, in mpi4py.MPI._p_msg_cco.for_cco_send
  File "mpi4py/MPI/msgbuffer.pxi", line 511, in mpi4py.MPI._p_msg_cco.for_cco_recv
  File "mpi4py/MPI/msgbuffer.pxi", line 203, in mpi4py.MPI.message_simple
  File "mpi4py/MPI/msgbuffer.pxi", line 203, in mpi4py.MPI.message_simple
  File "mpi4py/MPI/msgbuffer.pxi", line 145, in mpi4py.MPI.message_basic
KeyError: '<d'
  File "mpi4py/MPI/msgbuffer.pxi", line 145, in mpi4py.MPI.message_basic
KeyError: '<d'
```

 On every computer we use the native order is little endian, and that is distinguised in the numpy dtype as `=`. However, what seems to happen is that as HDF5 explicitly says that they are little-endian floats, the dtype byte order becomes explicitly little endian (i.e. <) for the array. mpi4py's `TypeDict` does not carry references for endian-ness, and cannot find the numpy dtype among its keys. 
 
The "workaround" is to fiddle the byte order in the array via something like: wdt = wdt.newbyteorder("="), but it is not clear if that is the best approach. The workaround in https://github.com/mpi4py/mpi4py/issues/81 also works.

**Comment by dalcinl** [comment]
> This was pretty time-consuming to wrap my head around

Sorry about the frustration. I hope you understand very few people contribute to this project, it is not easy to get all details right.

> (i.e. if allowing numpy datastructured with explicit endian-ness set makes sense)

It makes sense for basic native-order datatype to be mapped automatically to the matching MPI_Datatype. 

> but it would have been helpful to add some error-handling there with clearer messaging so that I could immediately understand why my numpy datastructure was failing to broadcast, and adjust things in my code.

Again, it is not easy to get all the details right. Byteorder is an alien/ignored concept in MPI. So far I have not been under pressure to handle this problem. At least you get an error if you feed a non-native datatype.

> The "workaround" is to fiddle the byte order in the array via something like: wdt = wdt.newbyteorder("="), but it is not clear if that is the best approach.

Well, for sure such approach is not automatic and requires more coding form user's side, but it is certainly a good workaround, at least until a new release can provide a better fix.

> The workaround in #81 also works.

Yes, it works, but it is definitely too heavy-weight of a solution. #81 is about complex, nested, struct datatypes. The issue you report is about basic datatypes.

**Comment by dalcinl** [comment]
I guess the solution is to inspect at the first character of the format string. If it is `=` or `@` ignore it. If it is `<` or `>` / `!`, check the CPU's native byteorder, and either ignore the first char or error.  On top of that, we need a better error message than the `KeyError` from the failed dict lookup. Suggestion welcome.

**Comment by anjakefala** [comment]
> Sorry about the frustration. I hope you understand very few people contribute to this project, it is not easy to get all details right.

I am sorry if I seemed cross! =( I also contribute to Open Source, and agreed it is hard to capture all of the edge-cases. If there is a better way that I could have phrased my post, please let me know! I think the aim about writing "I was frustrated" was to communicate that this is a pretty good place for an error message. I wanted the bug documented in an issue, so someone else could find it!

< Byteorder is an alien/ignored concept in MPI. So far I have not been under pressure to handle this problem.

I do not wish to pressure you either, we are coding the workaround: https://github.com/radiocosmology/caput/pull/194. Also, this bug was the first time I learned about byteorder. :sweat_smile: You are not under any time limit on our end. And again, I am grateful for all of the work on this project! 

>  If it is < or > / !, check the CPU's native byteorder, and either ignore the first char or error. 

This is basically what we are doing! 

> On top of that, we need a better error message than the KeyError

Even just `Type %s is not available in TypeMap` would have saved me time!
