### ISSUE TITLE
Spawnless MPIPoolExecutor implementation

### ISSUE THREAD

**Issue by Helveg** [mpi4py/mpi4py#18]
The `MPIPoolExecutor` provided in `mpi4py.futures` uses `MPI.Spawn`, a function which is often deliberatly disabled on MPI implementations meant for HPC (such as CrayMPI) that use job schedulers that don't properly deal with dynamic process management. Could mpi4py provide an option to tell the `MPIPoolExecutor` not to spawn any additional processes but instead use the available world?

I have my own package that does this: https://github.com/Helveg/zwembad in case you'd want to look at how I dealt with the problem. In short on each worker a loop is created that keeps waiting for new functions to execute and send back the result of. On the master each job that's submitted to the pool starts a thread and returns a future. The thread sends the data to the worker and executes a blocking read for the result. When the thread receives the result the return value of the corresponding future is set.

**Comment by dalcinl** [comment]
I guess you did not read `mpi4py.futures` documentation. There are to different ways to achieve what you need:

1. [MPICommExecutor](https://mpi4py.readthedocs.io/en/stable/mpi4py.futures.html#mpicommexecutor)
2. [`mpiexec -n 16 python -m mpi4py.futures ...`](https://mpi4py.readthedocs.io/en/stable/mpi4py.futures.html#command-line)

**Comment by Helveg** [comment]
I did not read below the `MPIPoolExecutor` documentation 😬 Well, it was a fun but ultimately pointless exercise into working with `mpi4py` then to create my own implementation (._.')

**Comment by dalcinl** [comment]
The situation with dynamic process management really pisses me off. Please note that the use of `-m mpi4py.futures` is a lame attempt to make user code work in these constrained environments without proper support for Spawn, it is not exactly equivalent to using new fresh spawned pools for each new executor.

**Comment by Helveg** [comment]
I can understand, I was quite frustrated myself that these HPC centres are OK with using MPI implementations that don't follow the spec.
