### ISSUE TITLE
mpi4py builds but has trouble linking to libslurm

### ISSUE THREAD

**Issue by mechapple** [mpi4py/mpi4py#187]
I get the following error when I submit a job to slurm that utilizes mpi4py.

```
cm/shared/apps/spack-pkgs/python/3.8.6-u7px4ssttiqjhc6q2arrww4wqceck7nk/bin/python: symbol lookup error: /cm/shared/apps/slurm/18.08.9/lib64/slurm/auth_munge.so: undefined symbol: slurm_debug
srun: error: eio_message_socket_accept: slurm_receive_msg[172.16.0.101]: Zero Bytes were transmitted or received
srun: error: C01: task 0: Exited with exit code 127
```
The error appears to be related to this: https://bugs.schedmd.com/show_bug.cgi?id=1138

Thank you for your attention. I have built mpi4py using pip as well as spack and I run into the same error.

**Comment by dalcinl** [comment]
mpi4py does not use the `slurm_debug` symbol explicitly, nor it links explicitly to `auth_munge.so`. As I do not have access to your system, it would be quite hard for me to debug the issue. Possible ways to debug the issue:

* execute `export LD_PRELOAD=/path/to/libslurm.so` and run your code.
* execute `export LDFLAGS=-lslurm` and reinstall mpi4py (run `pip cache remove mpi4py` first).

PS: You should ask your sysadmin for help to debug your issue.

**Comment by leofang** [comment]
hmmm why would mpi4py need to link to slurm? Isn't it something for `libmpi.so` to worry about?

**Comment by mechapple** [comment]
Thank you. I tried reinstalling mpi4py with LDFLAGS=-lslurm, and that did not appear to solve the issue. I used 
export LD_PRELOAD=/path/to/libslurm.so in my slurm script and that fixed the symbol lookup error. However, I run into a segmentation fault promptly after that.

SLURM FILE:
```
#!/bin/bash
#SBATCH --nodes=1
#SBATCH --tasks-per-node=12
#SBATCH --partition=compute-cpu
#SBATCH --output=log.slurm.%A
#SBATCH --error=log.slurm.%A
#SBATCH --time=00:10:00
#SBATCH --mem=512

module purge
module load slurm/18.08.9 
module load spack/python/3.8.6
module load pip-pkgs/latest

module load spack/openmpi/3.1.6
#module load spack/py-mpi4py/3.1.2
export LD_PRELOAD=/cm/shared/apps/slurm/18.08.9/lib64/libslurm.so

#srun python simple.py
srun python -c 'from mpi4py import MPI; print("Hi")' 
```

ERROR:
```
/cm/local/apps/slurm/var/spool/job27625/slurm_script: line 20: 47855 Segmentation fault      srun python -c 'from mpi4py import MPI; print("Hi")'
```
I am wondering if there is any way to debug this.

**Comment by mechapple** [comment]
I was able to resolve this.
I used `srun --mpi=pmi2 python simple.py`

**Comment by dalcinl** [comment]
I'm glad you figured it out! Looks like it was all related to a disagreement between your MPI backend and your SLURM defaults.
