### ISSUE TITLE
`memory.{__getitem__, __setitem__}` should be disabled for GPU buffers

### ISSUE THREAD

**Issue by leofang** [mpi4py/mpi4py#208]
`__getitem__` with a slice might work, but it's easier to just disable them altogether.

**Comment by dalcinl** [comment]
Perhaps it is time to revisit this `memory` type. I added it to easy supporting Python 2 and 3. The class is a striped-down version of the built-in `memoryview` type, and it is a CPU-only thing that accidentally managed to store GPU pointers when we added GPU support. mpi4py's `memory` it is not based in DLPack, thus you cannot query whether the buffer is CPU or GPU, so we cannot selectively disable methods. An alternative could be to use a subclass. Or document that these methods will segfault if used with a GPU buffer.

**Comment by leofang** [comment]
My (conflicting) thoughts:
- Maybe we could store an `is_cpu_accessible` flag in the [`internal`](https://docs.python.org/3/c-api/buffer.html#c.Py_buffer.internal) field of the buffer to check if we should disable accessing GPUs?
- While mpi4py does not talk to GPUs, the exporting objects do, so maybe in `memory`'s getter/setter we explicitly fall back to use the object's getter/setter?

**Comment by dalcinl** [comment]
> * Maybe we could store an `is_cpu_accessible` flag in the [`internal`](https://docs.python.org/3/c-api/buffer.html#c.Py_buffer.internal) field of the buffer to check if we should disable accessing GPUs?

That's an excellent idea!

> * While mpi4py does not talk to GPUs, the exporting objects do, so maybe in `memory`'s getter/setter we explicitly fall back to use the object's getter/setter?

I'm against it. mpi4py's `memory` object is so far byte-oriented, getitem/setitem/len work in terms of bytes.
