### ISSUE TITLE
MPIPoolExecutor stucks and cannot exit

### ISSUE THREAD

**Issue by ixsluo** [mpi4py/mpi4py#223]
MPIPoolExecutor cannot work with intel MPI, while MPICommExecutor works.

### To Reporduce

```
# FILE: mpi_pool.py
import os
import time
from subprocess import PIPE, Popen

from mpi4py import MPI
from mpi4py.futures import MPIPoolExecutor

comm = MPI.COMM_WORLD
size = comm.Get_size()
rank = comm.Get_rank()


def main():
    with MPIPoolExecutor() as executor:
        print('In Pool')
        res = executor.map(func, range(4))
        print(list(res))
    print('Finished')


def func(data):
    print('data %s on rank %s' % (data, rank))

    ### an advance need
    # node = os.uname().nodename
    # p = Popen(
    #     'mpirun -np 2 -host %s python -m mpi4py.bench helloworld 2>&1' % node,
    #     stdin=PIPE, stdout=PIPE, stderr=PIPE, shell=True, encoding='utf-8',
    # )
    # p.wait()
    # print('subsubprocess out on rank %d :' % rank, p.stdout.read())
    # print('subsubprocess err on rank %d :' % rank, p.stderr.read())
    # print('subsubprocess returncode: %s' % p.returncode)

    time.sleep(1)
    return f'data: {data}, rank: {rank}'


if __name__ == '__main__':
    print('My rank is ', rank, 'name is ', os.uname().nodename)
    main()
```

To execute
`mpiexec -n 1 -usize 4 python -u mpi_pool.py`

which outputs
```
My rank is 0 name is [nodename]
In Pool
['data: 0, rank: 0', 'data: 1, rank: 1', 'data: 2, rank: 2', 'data: 3, rank: 0']
*** stucks ***
```

I suppose Intel MPI version 3.1 should support dynamic process management.

### Environment

- MPI Library: Intel(R) MPI Library, Version 2021.4  Build 20210831
- MPI Version: `MPI.Get_version()` (3, 1)
- mpi4py: 3.1.3
- mpi4py installation: env MPICC=mpiicc pip install mpi4py

**Comment by dalcinl** [comment]
Dynamic process management seems to be kind of working, as your `func` function is actually executing. My suspicion is that the deadlock happens at executor shutdown time, perhaps at the (internal) `comm.Disconnect()` call that break the connection between master and worker processes. 

Just in case, could you try doing `export MPI4PY_RC_RECV_MPROBE=false` before running?

**Comment by dalcinl** [comment]
@ixsluo This is probably a duplicate of #15. In that old issue, I say that `mpi4py.rc.use_mprobe` cannot be used at worker processes. That's no longer accurate, now you can do `export MPI4PY_RC_RECV_MPROBE=false`.

**Comment by ixsluo** [comment]
@dalcinl Thank you for your advice. `export MPI4PY_RC_RECV_MPROBE=false` indeed solved this issue.

Now turns into the commented advance need, I want to run another mpirun program in each worker process, then the subsubprocess have this error output

```
My rank is  0 name is  [nodename]
In Pool
data 0 on rank 0
data 1 on rank 1
data 2 on rank 2
subsubprocess out on rank 0 : /home/luoxs/mpi
ubuntu2004-gpu-01
Error in system call pthread_mutex_destroy: Device or resource busy
    ../../src/mpi/init/init_thread_cs.c:58
Abort(1091087) on node 1 (rank 1 in comm 0): Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(170):
MPID_Init_spawn(1282):
MPIR_pmi_kvs_get(402): PMI_KVS_Get returned -1

subsubprocess err on rank 0 :
subsubprocess returncode: 15
data 3 on rank 0
*** same error on the other worker process ***
```

Is it because this need is incompatible with dynamic process management?

**Comment by dalcinl** [comment]
Some MPI implementation do not support creating new processes with let say `Popen`, and even more, they may not support recursive invocations of mpiexec (you are calling mpiexec within a program that was executed with mpiexec). This is in no way an mpi4py limitation, but a limitation of the backend MPI implementation, I hope you understand there is nothing I can do about it. Maybe Intel MPI has a way I don't know to workaround this issue.

The best thing you could try to do is to, once again, use  dynamic process management, i.e. `MPI.COMM_SELF.Spawn(...)` within the task you submit to workers.
```python
def func(*args):
    child = MPI.COMM_SELF.Spawn(
        'python',
        '-m mpi4py.bench helloworld'.split(),
        maxprocs=2,
    )
    child.Disconnect() # this should block until child finishes, use comm.Free() for non-blocking semantics.
```
One obvious problem of this approach is that you cannot pipe stdin/stdout/stderr so easily.
