### ISSUE TITLE
MPICommExecutor & MPIPoolExecutor Freeze Indefinitely

### ISSUE THREAD

**Issue by profPlum** [mpi4py/mpi4py#226]
Architecture:
Power9 (Summit Super Computer)

MPI Version:
Package: IBM Spectrum MPI
            Spectrum MPI: 10.4.0.03rtm4
Spectrum MPI repo revision: IBM_SPECTRUM_MPI_10.04.00.03_2021.01.12_RTM4
Spectrum MPI release date: Unreleased developer copy

MPI4py Version: 3.1.1

Reproduce Script:
````
from mpi4py.futures import MPICommExecutor
from mpi4py import MPI
import time
import os

comm = MPI.COMM_WORLD
size = comm.Get_size()
rank = comm.Get_rank()

# square the numbers
def apply_fun(i):
    print('running apply!', flush=True)
    return i**2*rank

print('pid:',os.getpid(), flush=True)
print('rank:', rank, flush=True)

# this *does* implement map-reduce and supposedly works on legacy systems without dynamic process management
# (I've gotten it working with `jsrun -n 1` but so far no luck with multiple processes)
# see the docs: https://mpi4py.readthedocs.io/en/stable/mpi4py.futures.html?highlight=MPICommExecutor#mpicommexecutor
with MPICommExecutor(MPI.COMM_WORLD, root=0) as executor:
    if executor is not None:
        print('Executor started from root!', flush=True)
        answer = list(executor.map(apply_fun, range(41)))
        print('pid: ',os.getpid(),'rank:',rank, answer, flush=True)
````

`jsrun python mpi_test.py` output:
````
Warning: OMP_NUM_THREADS=16 is greater than available PU's
Warning: OMP_NUM_THREADS=16 is greater than available PU's
pid: 1448946
rank: 1
pid: 1448945
rank: 0
Executor started from root!
running apply!
````

Then indefinite freeze. Btw jsrun is summit's 'custom version' of mpirun/mpiexec and it works really well in general (in contrast to mpirun & mpiexec). **Also with this exact same setup I had no problem using MPI.gather() & MPI.scatter()** it is just the Executors which don't work which troublesome because I really like the map-based API.

**Comment by dalcinl** [comment]
As I do not have access to Summit, it is almost impossible for me to figure out what's going on.
When users have problems with mpi4py, the usually come to me first, but 99.9% of the cases, the problem is in the backend MPI implementation or the runtime system, and there is absolutely nothing I can do.

Did you ask to Summit IT staff for help?

@stefanozampini Any chance you have any tips?

@profPlum Could you try setting
```
export MPI4PY_RC_THREAD_LEVEL=single
```
before running?

**Comment by profPlum** [comment]
@dalcinl Yes I've ask summit IT staff we did a very thorough investigation and I have a lot of experimental data testing what works and what doesn't that I could share.

But I get suspicious that this is _just_ a backend problem (though that could be part of it). Like I said gather() & scatter() work perfectly. And I heard MPIComExecutor was for compatibility legacy purposes right? Is there some way to implement it with gather/scatter?

**Comment by profPlum** [comment]
@dalcinl Also there was this funny situation in which I ALMOST got the MPICommExecutor working (with crazy environment variable settings). It was in fact working as long as the MPI processes were less than 27! How strange! What is up with that? I can share the details of that experiment as well.

**Comment by stefanozampini** [comment]
> As I do not have access to Summit, it is almost impossible for me to figure out what's going on. When users have problems with mpi4py, the usually come to me first, but 99.9% of the cases, the problem is in the backend MPI implementation or the runtime system, and there is absolutely nothing I can do.
> 
> Did you ask to Summit IT staff for help?
> 
> @stefanozampini Any chance you have any tips?
> 
> @profPlum Could you try setting
> 
> ```
> export MPI4PY_RC_THREAD_LEVEL=single
> ```
> 
> before running?

Without a stack trace, it is impossible to say what's going on. What did SUMMIT support say?

**Comment by dalcinl** [comment]
> And I heard MPIComExecutor was for compatibility legacy purposes right?

That's not true, not at all. 

What is kind of "compatibility support"  is using `mpiexec -n <nprocs> python -m mpi4py.futures script.py` [docs](https://mpi4py.readthedocs.io/en/stable/mpi4py.futures.html#command-line) on MPI backends that do implement MPI dynamic process management (a feature from MPI-2 that is more than 20 years old).

`MPIComExecutor` is intended to be used code that is written MPI-style, explicitly importing `from mpi4py import MPI`, that at some point need to use the master/worker approach to computation. This executor uses quite basic MPI-1 APIs to split a communicator in master and worker processes, and next basically uses `bcast()` and `send()`/`recv()`. I see no reason for it failing, other than issues in the MPI backend/runtime system/network stack.

**Comment by leofang** [comment]
If you're on Summit, Spectrum MPI isn't your only choice. IIRC you can also built against Open MPI. How about changing to another MPI backend and retrying the same code?

**Comment by profPlum** [comment]
@stefanozampini I'm not sure how to get a stack trace, because the latest problem is freezing not erroring out. That being said there is some more info to be gained from the experiments me & OLCF support did.

@stefanozampini @leofang @dalcinl: I'm attaching a pdf of the transcript of my email chain with OLCF **I've included directly though the most important part where I have my experimental results**

**Experimental Results:**
I'm getting essentially 2 different errors behaviours when I try to use mpi4py with its various call forms e.g.:
1. mpirun -n 11 python -m mpi4py.futures mpi4py_test.py --> warning: 'lsb_launch(): Server is not connected.' and freeze
2. jsrun -n 11 python -m mpi4py.futures mpi4py_test.py --> super long error which boils down to 'Signal code: Address not mapped (1)'
3. mpirun -n 1 -usize 11 python mpi4py_test.py --> same behaviour as 1
4. MPIEXEC_UNIVERSE_SIZE=11 mpiexec -n 1 python mpi4py_test.py --> same behaviour as 1 & 3
5. MPIEXEC_UNIVERSE_SIZE=11 jsrun -n 1 python mpi4py_test.py --> save behaviour as 2

**Really Strange Experiment (works for num processes<=27!!):** 
6. MPLCONFIGDIR=/tmp/matplotlib OMPI_MCA_pml=ob1 OMP_NUM_THREADS=1 jsrun mpi4py_test2.py

mpi4py_test2.py contents:
```
from mpi4py.futures import MPICommExecutor
from mpi4py import MPI
import time
import os

# square the numbers
def apply_fun(i):
    print('running apply!', flush=True)
    return i**2

comm = MPI.COMM_WORLD
size = comm.Get_size()
rank = comm.Get_rank()

print('pid:',os.getpid(), flush=True)
print('rank:', rank, flush=True)

# this *does* implement map-reduce and supposedly works on legacy systems without dynamic process management
with MPICommExecutor(MPI.COMM_WORLD, root=0) as executor:
    if executor is not None:
        print('Executor started from root!', flush=True)
        answer = list(executor.map(apply_fun, range(41)))
        print('pid: ',os.getpid(),'rank:',rank, answer, flush=True)
```
 
*Link to full transcript*: https://drive.google.com/file/d/17CqBv30bWqaErsrfRLnPGYEvpVGcLxNo/view?usp=sharing

**Comment by dalcinl** [comment]
Looks like there are some misunderstandings I should clarify.

* As you are using `MPICommExecutor`, then you SHOULD NOT use `python -m mpi4py.futures ...` to run your script. The `-m mpi4py.futures` part is a legacy mode for code that uses `MPIPoolExecutor` (which requiers MPI-2 dynamic processes features), and not `MPICommExecutor`. `MPICommExecutor` can work with good old MPI-1 APIs just fine.
* Just use `jsrun -n <nprocs> python script.py`. As you are using `MPICommExecutor`, dynamic process management is not involved. DO NOT mess with the MPI universe size, it is not required for code using `MPICommExecutor`. If the recommended way to run stuff is to use `jsrun`, then stick to it. If it does not work, there you have the problem, it should work.

At this point, either you or someone from staff has to manage to "trace" the execution and figure out where exactly the code is deadlocking. For example, look within the code to calls to `comm.Disconnect()`, try replacing them with `comm.Free()`. Also, look for calls to `comm.issend()` and `comm.Issend()` (nonblock sync mode, extra `s` in the routine name), try replacing by `comm.isend()` and `comm.Isend()` respectively (non blocking, standard mode). I suspect one of these not so-often used variants is not behaving with the right semantics.

**Comment by profPlum** [comment]
@dalcinl & @stefanozampini: also when I keyboard interrupt again (the first one doesn't kill it for some reason), this happens:
/sw/summit/open-ce/anaconda-base/envs/open-ce-1.2.0-py38-0/lib/python3.8/site-packages/mpi4py/futures/_lib.py:142: RuntimeWarning: The level of thread support in MPI should be at least MPI_THREAD_SERIALIZED
  setup_mpi_threads()
Traceback (most recent call last):
  File "mpi4py_test2.py", line 24, in <module>
    answer = list(executor.map(apply_fun, range(41)))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-1.2.0-py38-0/lib/python3.8/site-packages/mpi4py/futures/pool.py", line 221, in result_iterator
    yield futures.pop().result()
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-1.2.0-py38-0/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    self._condition.wait(timeout)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-1.2.0-py38-0/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mpi4py_test2.py", line 25, in <module>
    print('pid: ',os.getpid(),'rank:',rank, answer, flush=True)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-1.2.0-py38-0/lib/python3.8/site-packages/mpi4py/futures/pool.py", line 338, in __exit__
    executor.shutdown(wait=True)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-1.2.0-py38-0/lib/python3.8/site-packages/mpi4py/futures/pool.py", line 193, in shutdown
    self._pool.join()
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-1.2.0-py38-0/lib/python3.8/site-packages/mpi4py/futures/_lib.py", line 160, in join
    self.thread.join()
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-1.2.0-py38-0/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-1.2.0-py38-0/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
ERROR:  One or more process (first noticed rank 8) terminated with signal 2

**Comment by dalcinl** [comment]
Sending SIGINT is not enough to debug the issue. You will have to modify mpi4py's source code and add `print()` calls here and there so figure out where exactly the execution gets stuck. From the traceback you sent, I see a warning about MPI thread support, although I expect things to still work. 

At this point, either someone with local access properly debugs the issue, or you figure out how to use a different MPI implementation. I believe I NEVER tested mpi4py.futures with Spectrum MPI, so it could very well be that the implementation is broken. As Spectrum MPI free edition no longer supports  x86_64, I cannot install it quickly on my development workstation to give it a try.

**Comment by dalcinl** [comment]
@profPlum Any update on this issue? Could you manage to get some help form Summit staff?

**Comment by VictorEijkhout** [comment]
Interesting that this is an OpenMPI ticket. I have a ticket open with Intel about the PoolExecutor crashing immediately with Intel MPI (1API version), which is a completely different code base. I guess spawning is a fragile activity on the best of days.

**Comment by dalcinl** [comment]
@VictorEijkhout I've also reported a bunch of issues to Intel folks. They could reproduce [issues with spawn](https://community.intel.com/t5/Intel-oneAPI-HPC-Toolkit/Issues-running-mpi4py-testsuite-on-GitHub-Actions/m-p/1432107/highlight/true#M10081). Have you tried latest Intel MPI 2021.8?

**Comment by VictorEijkhout** [comment]
Intel is basically telling me to "go away" if it's not reproducible with OneAPI, so that's the only thing I'm trying these days. Yes, plenty of spawn problems.

**Comment by dalcinl** [comment]
> Intel is basically telling me to "go away" if it's not reproducible with OneAPI

Oh, but... isn't version 2021.8 part of oneAPI? AFAICT, that's the latest version. Can you check the version of the Intel MPI RPM packages you have installed? Or maybe the output of `MPI.Get_library_version()` from Python?

**Comment by dalcinl** [comment]
@VictorEijkhout Any updates from your side regarding this issue?

**Comment by VictorEijkhout** [comment]
Hm. My Intel ticket has disappeared. Doing something with MPIPoolExecutor with Intel 2023 runs, but later hangs. However, this can be because I don't have a python that was built with the latest compiler/mpi.

**Comment by dalcinl** [comment]
> Hm. My Intel ticket has disappeared.

LOL!

>  Doing something with MPIPoolExecutor with Intel 2023 runs, but later hangs. 

What happens if you `export MPI4PY_RC_RECV_MPROBE=0` before running? Does it still hang?

> However, this can be because I don't have a python that was built with the latest compiler/mpi.

Although possible, it is unlikely. That's more or less how I run tests on [GitHub Actions](https://github.com/mpi4py/mpi4py-testing/actions/workflows/intelmpi.yml)

**Comment by antoscha** [comment]
Open MPI has the same problem, `export MPI4PY_RC_RECV_MPROBE=0` doesn't help.

**Comment by antoscha** [comment]
...while MPICH 4.1.2 works flawlessly.

**Comment by dalcinl** [comment]
> Open MPI has the same problem, `export MPI4PY_RC_RECV_MPROBE=0` doesn't help.

@antoscha That suggestion is specific to Intel MPI. 

Regarding Open MPI, what version and installed from where? 
Can you provide a minimal reproducer script (maybe one of mpi4py's own demos) with the full command line?
Any change you could try replacing `comm.Disconnect()` -> `comm.Free()` in mpi4py.futures sources and give it a try?

**Comment by dalcinl** [comment]
OK, I can reproduce issues with Open MI 4.1.4 from Fedora 38 and mpi4py@master , there is a deadlock at a `recv()` call. The issue goes away with `export MPI4PY_RC_RECV_MPROBE=0`. This is a new kind of regression I've not seen before. Once again, Open MPI patch releases introduce regressions in code using mpi4py.

**Comment by antoscha** [comment]
Maybe it's worth to report the regression to the Open MPI project? But I don't know what exactly is to be reported...

**Comment by dalcinl** [comment]
> Maybe it's worth to report the regression to the Open MPI project?

Some time ago I decided to track testing the development branches with daily frequency and report issues as soon as they pop up, such that these nasty issues do not keep hitting users. However, I've started this approach not so long ago with branches v5.0.x and main. It is too late for me to care about branch v4.1.x and getting it production-ready, I simply do not have the time. 

> But I don't know what exactly is to be reported...

If you are interested in doing the report, just mention the Open MPI version and the fact that you are using mpi4py, and provide the reproducer script. If you can write a trivial reproducer that does not use asyncio, even better.  Maybe someone will care to pick it up and investigate, but obviously I cannot make any promises.

**Comment by dalcinl** [comment]
This issue was ultimately not mpi4py's fault but an Open MPI regression.
As a workaround, users can just  `export MPI4PY_RC_RECV_MPROBE=0`. 
The regression seems to not be there in branch openmpi/ompi@v4.1.x.
