### ISSUE TITLE
Memory limit for communicating python objects

### ISSUE THREAD

**Issue by eeopd** [mpi4py/mpi4py#23]
It seems that if objects get larger than 2GB, they trigger an error: `SystemError: Negative size passed to PyBytes_FromStringAndSize`

The issue is quite old, and is probably best explained in this post: https://stackoverflow.com/questions/20023742/how-do-i-remove-the-memory-limit-on-openmpi-processes

Is this limit easy to remove? I am unfortunately myself inexperienced with cython. For now I suppose I will just use numpy arrays, afaik, they do not suffer from this limit.

**Comment by dalcinl** [comment]
Yes, indeed that is a well-known limitation of MPI (and mpi4py inherits it) that will only be fixed for good in the upcoming MPI-4.0 standard.

If you are brave enough, I have am unpublished branch that provides some support to alleviate the issue, but it only covers point to point communication (send/recv and matched probes). Unfortutately, `irecv()` cannot possibly be supported. Collective operations should be possible to support and are not hard, reimplemented from the p2p send and recv, but I don't have the time (I have to take care of things like thread safety that perhaps you would not care about).

if the objects you are communicating take advantage of pickle protocol 5 and out-of-band buffers  (e.g. NumPy), then you will get some nice memory and CPU optimizations.

Are you willing to try my fresh and untested-in-production code? If you are, then I can publish the branch for your consideration.

**Comment by eeopd** [comment]
Ah, it seems I was a bit naive in thinking that it could be an easy fix. About that unpublished branch: that sounds quite nice, especially the pickle improvements, but I don't think I have time (or the expertise) to tinker with it. Thanks for offering though!

**Comment by dalcinl** [comment]
Please see #29.
