### ISSUE TITLE
Broadcast function definitions for MPIPoolExecutor

### ISSUE THREAD

**Issue by jan-janssen** [mpi4py/mpi4py#232]
I would like to improve the integration of mpi4py with Jupyter. The challenge is that Jupyter notebooks are typically executed in serial, while mpi4py should run in parallel. One solution to this challenge is in the Jupyter notebook create a subprocess which calls `mpiexec` and then communicate with the Jupyter notebook using `stdin` and `stdout` by pickling the corresponding python objects. An example of this implementation can be found in https://github.com/pyiron/pylammpsmpi/blob/master/pylammpsmpi/utils/lammps.py#L28 . Still this example is written for one specific Python library. Now I would like to generalize this implementation. The idea is to be able to define a function in a Jupyter notebook, pickle it, communicate it to an mpi4py parallel subprocess, unpickle it there and then distribute it to all the nodes in the given MPI allocation. Currently I struggle with the last step as I am able to communicate the function to the MPI rank 0 process but it is not broadcasted to the other ranks. 

My current example code: 
```
import subprocess
import inspect
import dill as pickle



mpisampling_str = """\
# Execute with:
# mpiexec -n 4 python -m mpi4py.futures mpisampling.py
#

import textwrap
import dill as pickle
from mpi4py.futures import MPIPoolExecutor
from tqdm import tqdm
import sys


def get_function_from_string(function_str):
    function_dedent_str = textwrap.dedent(function_str)
    exec(function_dedent_str)
    return eval(function_dedent_str.split("(")[0][4:])


def exec_funct(executor, funct, lst):
    results = executor.map(funct, lst)
    return list(tqdm(results, desc="Configs", total=len(lst)))


if __name__ == '__main__':
    with MPIPoolExecutor() as executor:
        while True:
            output = None
            if executor is not None:
                input_dict = pickle.load(sys.stdin.buffer)
                if "c" in input_dict.keys() and input_dict["c"] == "close":
                    break
                elif "f" in input_dict.keys() and "l" in input_dict.keys():
                    output = exec_funct(
                        executor=executor, 
                        funct=get_function_from_string(function_str=input_dict["f"]),
                        lst=input_dict["l"]
                    )
                if output is not None:
                    pickle.dump(output, sys.stdout.buffer)
                    sys.stdout.flush()
                    output = None
"""


with open('mpisampling.py', 'w') as file:
    file.writelines(mpisampling_str)

cores = 4

process = subprocess.Popen(
    ["mpiexec", "--oversubscribe", "-n", str(cores), "python", "-m", "mpi4py.futures", "mpisampling.py"],
    stdout=subprocess.PIPE,
    stderr=None,
    stdin=subprocess.PIPE,
    # cwd=self.working_directory,
)

def send(process, function, lst):
    pickle.dump({"f": inspect.getsource(function), "l": lst}, process.stdin)
    process.stdin.flush()

def receive(process):
    output = pickle.load(process.stdout)
    return output

def calc(i):
    return i ** 2

def close(process):
    pickle.dump({"c": "close"}, process.stdin)
    process.stdin.flush()

send(process=process, function=calc, lst=[1,2,3,4])

receive(process=process)
```

I get the following error: 
```
Traceback (most recent call last):
  File "/Users/janssen/mambaforge/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/janssen/mambaforge/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/janssen/mambaforge/lib/python3.9/site-packages/mpi4py/futures/__main__.py", line 74, in <module>
    main()
  File "/Users/janssen/mambaforge/lib/python3.9/site-packages/mpi4py/futures/__main__.py", line 62, in main
    run_command_line()
  File "/Users/janssen/mambaforge/lib/python3.9/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/Users/janssen/mambaforge/lib/python3.9/runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/janssen/mambaforge/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/janssen/mambaforge/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "mpisampling.py", line 32, in <module>
    output = exec_funct(
  File "mpisampling.py", line 20, in exec_funct
    return list(tqdm(results, desc="Configs", total=len(lst)))
  File "/Users/janssen/mambaforge/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/Users/janssen/mambaforge/lib/python3.9/site-packages/mpi4py/futures/pool.py", line 234, in result_iterator
    yield futures.pop().result()
  File "/Users/janssen/mambaforge/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/Users/janssen/mambaforge/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
_pickle.PicklingError: Can't pickle <function calc at 0x11013a670>: attribute lookup calc on __main__ failed
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

**Comment by jan-janssen** [comment]
Rather than using `inspect` to get the source code of the function, I can also try to pickle it: 

```
mpisampling_str = """\
# Execute with:
# mpiexec -n 4 python -m mpi4py.futures mpisampling.py
#

import dill as pickle
from mpi4py.futures import MPIPoolExecutor
from tqdm import tqdm
import sys


def exec_funct(executor, funct, lst):
    results = executor.map(funct, lst)
    return list(tqdm(results, desc="Configs", total=len(lst)))


def calc(i):
    with open('file_' + str(i) + '.my', 'w') as file:
        file.write(str(i))
    return i


if __name__ == '__main__':
    with MPIPoolExecutor() as executor:
        while True:
            output = None
            if executor is not None:
                input_dict = pickle.load(sys.stdin.buffer)
                if "c" in input_dict.keys() and input_dict["c"] == "close":
                    break
                elif "f" in input_dict.keys() and "l" in input_dict.keys():
                    output = exec_funct(
                        executor=executor, 
                        funct=input_dict["f"], # calc, 
                        lst=input_dict["l"]
                    )
                if output is not None:
                    pickle.dump(output, sys.stdout.buffer)
                    sys.stdout.flush()
                    output = None
"""


def send(process, function, lst):
    pickle.dump({"f": function, "l": lst}, process.stdin)
    process.stdin.flush()


def receive(process):
    output = pickle.load(process.stdout)
    return output

```

The error message is more or less the same: 
```
Traceback (most recent call last):
  File "/Users/janssen/mambaforge/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/janssen/mambaforge/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/janssen/mambaforge/lib/python3.9/site-packages/mpi4py/futures/__main__.py", line 74, in <module>
    main()
  File "/Users/janssen/mambaforge/lib/python3.9/site-packages/mpi4py/futures/__main__.py", line 62, in main
    run_command_line()
  File "/Users/janssen/mambaforge/lib/python3.9/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/Users/janssen/mambaforge/lib/python3.9/runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/janssen/mambaforge/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/janssen/mambaforge/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "mpisampling.py", line 31, in <module>
    output = exec_funct(
  File "mpisampling.py", line 13, in exec_funct
    return list(tqdm(results, desc="Configs", total=len(lst)))
  File "/Users/janssen/mambaforge/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/Users/janssen/mambaforge/lib/python3.9/site-packages/mpi4py/futures/pool.py", line 234, in result_iterator
    yield futures.pop().result()
  File "/Users/janssen/mambaforge/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/Users/janssen/mambaforge/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
_pickle.PicklingError: Can't pickle <function calc at 0x104cca5e0>: it's not the same object as __main__.calc
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

**Comment by dalcinl** [comment]
@jan-janssen I'm not 100% sure, but using `cloudpickle` may be better:

```python
import pickle
import cloudpickle
from mpi4py import MPI
MPI.pickle.__init__(
    cloudpickle.dumps, 
    pickle.loads, 
    pickle.HIGHEST_PROTOCOL,
)
```

**Comment by jan-janssen** [comment]
@dalcinl Thanks a lot - that works perfectly.

**Comment by dalcinl** [comment]
I believe you should not rely on read/write from/to stdin/out as an IPC mechanism. Such approach may fail badly if your pickled messages are large.

**Comment by jan-janssen** [comment]
It fails for `mpich` but works nicely for `openmpi`.

**Comment by dalcinl** [comment]
> It fails for `mpich` but works nicely for `openmpi`.

There you have. It depends on how `mpiexec` forwards stdin to child processes. Perhaps you should consider using Jupyter's own mechanisms to do IPC.

**Comment by jan-janssen** [comment]
I build a small package based on this idea: https://github.com/jan-janssen/pympipool 

The nice part about it, is that it feels even more like `multiprocessing`: 

```
from pympipool import Pool

def calc(i):
    import numpy as np
    return np.array(i ** 2)

with Pool(cores=2) as p:
    print(p.map(function=calc, lst=[1, 2, 3, 4]))

>>> [array(1), array(4), array(9), array(16)]
```

I agree it is still a bit hacky but it is quicker for me to write.

**Comment by dalcinl** [comment]
> I build a small package based on this idea: https://github.com/jan-janssen/pympipool
> 

You should benchmark `dill` vs `picklecloud`. I looked to dill yesterday, and I'm not sure they support the updated pickle API of Py3.8+, not to mention the use of faster C code from the builtin `_pickle` module.

> The nice part about it, is that it feels even more like `multiprocessing`:
> 

Well, that being nice is highly subjective :-) I like `concurrent.futures` much more than  `multiprocessing`...

> ```
> from pympipool import Pool
> 
> def calc(i):
>     import numpy as np
>     return np.array(i ** 2)
> 
> with Pool(cores=2) as p:
>     print(p.map(function=calc, lst=[1, 2, 3, 4]))
> 

although I grant your package require very little typing.

> I agree it is still a bit hacky but it is quicker for me to write.

The important part of what you are trying to do is to isolate even further the parallel MPI process universe and its annoyances/rigidities from the process running Jupyter. I will keep in mind this use case and your approach.

**Comment by jan-janssen** [comment]
> You should benchmark `dill` vs `picklecloud`. I looked to dill yesterday, and I'm not sure they support the updated pickle API of Py3.8+, not to mention the use of faster C code from the builtin `_pickle` module.

It took some time for me to get to this point. The great advantage of `cloudpickle` is the ability to pickle by value and not only by reference. By adding the module which calls `pympipool` to the register of modules which should be pickled by value `cloudpickle.register_pickle_by_value()` I am now able to submit the function directly without converting it to source first. This new functionality is included in the `0.1.0` release. 

> Well, that being nice is highly subjective :-) I like `concurrent.futures` much more than `multiprocessing`...

Maybe backwards compatibility to `multiprocessing` is a better phrase. I have a couple of scientists who learned about `multiprocessing` first and then search for a tool to scale beyond a single compute node. So providing them with a similar interface accelerates the migration. 

> The important part of what you are trying to do is to isolate even further the parallel MPI process universe and its annoyances/rigidities from the process running Jupyter. I will keep in mind this use case and your approach.

I would be interested to merge the changes I made in `pympipool` into `mpi4py` maybe as `mpi4py.multiprocessing.Pool()`. Then there is a backwards compatible interface for users who have previous experience with the `multiprocessing` package. Is this something you would be interested in?

**Comment by jan-janssen** [comment]
> There you have. It depends on how `mpiexec` forwards stdin to child processes. Perhaps you should consider using Jupyter's own mechanisms to do IPC.

This is also fixed in the new version, I adopted `zmq` for the communication, which is also used by the jupyter project https://ipython.readthedocs.io/en/stable/whatsnew/version0.11.html#zeromq-architecture

**Comment by dalcinl** [comment]
@jan-janssen There are many rather orthogonal points to elaborate on. Maybe we should open new threads in [Discussions/Ideas](https://github.com/mpi4py/mpi4py/discussions/categories/ideas) to proceed further.

* Improving pickle support in mpi4py to support other pickle backends is definitely in my radar. Ideally, users should be able to easily switch the default backend using the `mpi4py.rc` mechanism and the environment variable, e.g. `MPI4PY_RC_PICKLE_MODULE=pickle|dill|cloudpickle`. BTW, what you mentioned about `cloudpickle` I believe is also true about `dill`, functions are pickled by value in dill (although maybe you don't have a per-module choice). Ultimately, perhaps the pickle  backend should be an attribute attached to communicators.
* Providing users with a drop-in replacement for the `multiprocessing.pool` API is something I'm totally OK with. I'm annoyingly opinionated, but I have uttermost respect for third-party opinions. However, I would expose the `Pool` class and friends in a `mpi4py.util.pool` module. I believe the implementation can be done easily by wrapping `mpi4py.futures`. Of course, if we ever do that, the API has to be almost complete to be a true drop-in replacement for the stdlib module, and not just a half-baked solution. I'll look into this.
* Finally, regarding the inclusion of your changes to `pympipool`, I don't feel comfortable with including a dependency on an alien (from the POV of MPI) communication backend. IIRC, MPI spawn does work with Open MPI. MPICH 4.1 is out, and now the native MPI spawn mechanism should also just work (the conda-forge mpich package is not up to date, but that's probably because the conda-forge bot failed to issue the update PR, I'm looking into this).

**Comment by jan-janssen** [comment]
> Of course, if we ever do that, the API has to be almost complete to be a true drop-in replacement for the stdlib module, and not just a half-baked solution. 

I agree, currently `pympipool` only has the `map()` function, but I definitely want to add `starmap()`, `imap()` and so on. If there is anything else I can help you with on this topic feel free to reach out.

**Comment by jan-janssen** [comment]
> @jan-janssen There are many rather orthogonal points to elaborate on. Maybe we should open new threads in [Discussions/Ideas](https://github.com/mpi4py/mpi4py/discussions/categories/ideas) to proceed further.

I started the discussion in https://github.com/mpi4py/mpi4py/discussions/318
