### ISSUE TITLE
testJoin fails on IPV6-only networks

### ISSUE THREAD

**Issue by drew-parsons** [mpi4py/mpi4py#240]
Debian reports that mpi4py fails to build on IPV6-only build daemons, reported in Debian [Bug#1015912](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1015912). A build log is available at 
https://buildd.debian.org/status/fetch.php?pkg=mpi4py&arch=amd64&ver=3.1.3-2%2Bb1&stamp=1658589239&raw=0

The error message is in testJoin (test_dynproc.TestDPM):
```
ERROR: testJoin (test_dynproc.TestDPM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/test/test_dynproc.py", line 175, in testJoin
    server.bind((host, 0))
socket.gaierror: [Errno -5] No address associated with hostname

----------------------------------------------------------------------
Ran 547 tests in 17.493s

FAILED (errors=1, skipped=10)
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
```

**Comment by dalcinl** [comment]
This is expected, as the test is creating sockets using `AF_INET` rather than `AF_INET6`. I wrote these tests long ago, circa 2014, just a couple years after IPV6 debut. As I'm not an expert in networking, I don't know how to detect if a host is IPV6-only. I believe [`socket.getaddrinfo()`](https://docs.python.org/3/library/socket.html#socket.getaddrinfo) may help us.

**Comment by drew-parsons** [comment]
That's enough of a clue. I prepared a patch to access the family reported by socket.getaddrinfo().  I'll check it on Debian build daemons then push a PR.

**Comment by dalcinl** [comment]
> then push a PR.

Please make it against the `maint` branch. BTW, you may want to apply some other patches in the `maint` branch, particularly 9ccf55fb0a0218d3fcc5eb7292ed14117d781852.

**Comment by drew-parsons** [comment]
PR created. I set it up to use any socket family as reported by getaddrinfo(), but to prefer INET (IPv4) in case the order of entries is different as reported for the server process and the client process.

Thanks for the 9ccf55f recommendation, I'll apply it to Debian also.

**Comment by drew-parsons** [comment]
A testJoin error was recently reported at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1052748 :
```
----------------------------------------------------------------------

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/test/test_dynproc.py", line 172, in testJoin
    addresses = socket.getaddrinfo(host, None, 0, socket.SOCK_STREAM)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known
```
I suspect it's related to the IPV6 issue dealt with here.  I can't reproduce it though. It passes on my machine and [Debian CI tests](https://ci.debian.net/packages/m/mpi4py/) continue to pass.  So I'm not sure that it's worth opening a fresh bug if we can't reproduce it.
