### ISSUE TITLE
PyPI Wheels for Unix systems ?

### ISSUE THREAD

**Issue by neutrinoceros** [mpi4py/mpi4py#260]
I noticed that there are no wheels on PyPI for architectures other than Windows.
Building wheels for mpi4py on is costing a significant amount of time on CI for downstream projects (of the order of 1 minute for each job).
I am not familiar with the details of building this package from source, is there a technical reason why such wheels cannot be shipped ? If not, would you consider doing it ?

**Comment by dalcinl** [comment]
See issue #28 for the full story. Long story short, some users may want mpi4py with MPICH, other with Open MPI, and even some other vendor MPI implementations. Different MPI implementations are not ABI-compatible, so a single wheel file cannot work with the different MPI's out there. 

The folks form [bodo.ai](https://www.bodo.ai/) took the quick way and published mpi4py wheels using MPICH as the MPI implementation https://pypi.org/project/mpi4py-mpich/. For different reasons, I do not quite like what they did, and I have no control on it (anyone can upload a new package to PyPI with name mpi4py-whatever). One obvious problem with that approach is proper maintenance: they have not updated the package to latest mpi4py upstream release 3.1.3.

Regarding CI build times, I understand your paint, it is really annoying. However, if you define `CFLAGS=-O0` in your environment, you may be able to cut the build time by half, ~ 30 seconds on GitHub actions for an mpi4py git checkout [[link]](https://github.com/mpi4py/mpi4py-testing/actions/runs/3116776733/jobs/5054904481#step:16:11). Additionally, you could cache the built mpi4py wheel, you basically run `pip wheel mpi4py` and you get the wheel file in the working directory that you install with `pip install mpi4py-*.whl`. Then you can use let say `actions/cache` with GitHub actions to cache the `pip wheel mpi4py` step.

**Comment by neutrinoceros** [comment]
Thank you very much for this detailed reply. Sorry I missed the existing closed issue, I should have searched there too.
Thanks also for your pointers on how to reduce the build time on GHA, that should be helpful.
I guess we can close this, I understand there's not much to be done indeed.

**Comment by leofang** [comment]
Caching a prebuilt binary is indeed the way out. If you use conda in your CI, you can just do "conda install -c conda-forge mpi4py" and it'd come with an MPI binary. 

That said, @dalcinl I've been looking into this issue lately, too, but from a different perspective: Without offering a wheel, currently there's no proper way for downstream to depend on mpi4py, as installing mpi4py may require manual intervention. I wonder how many distinct ABI sets are out there to support, if we build shim layers to hide the ABI incompatibility?

**Comment by dalcinl** [comment]
> Without offering a wheel, currently there's no proper way for downstream to depend on mpi4py, 

Unfortunately, things may only get worse. I'm not willing to surrender to the new PyPI policy of forcing me to enable second-factor authentication to upload new releases.

> as installing mpi4py may require manual intervention. 

Like what? Requiring the previous installation of an MPI implementation? Solving the ABI issue will not alleviate the MPI requirement. Or are you talking about the fact that installing mpi4py from a source tarball requires a C compiler toolchain and the python-devel packages?

> I wonder how many distinct ABI sets are out there to support, if we build shim layers to hide the ABI incompatibility?

Right now, I would say we should care about `mpich31`, `mpich40`, `openmpi31`, and the still in development `openmpi40`. By `31` and `40` I refer to the major+minor version of the MPI standard.
