### ISSUE TITLE
3.1.3: sphinx fails

### ISSUE THREAD

**Issue by kloczek** [mpi4py/mpi4py#271]
I have problems with generate documentation. Any hint what it could be?
```console
+ /usr/bin/sphinx-build -j48 -n -T -b man docs/source/usrman build/sphinx/man
Running Sphinx v5.3.0
/usr/lib/python3.8/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (None)/charset_normalizer (3.0.0) doesn't match a supported version!
  warnings.warn(
making output directory... done
[pers-jacek:3312327] mca_base_component_repository_open: unable to open mca_pmix_ext3x: /usr/lib64/openmpi/mca_pmix_ext3x.so: undefined symbol: pmix_value_load (ignored)
[pers-jacek:3312327] [[17983,0],0] ORTE_ERROR_LOG: Not found in file ess_hnp_module.c at line 320
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_pmix_base_select failed
  --> Returned value Not found (-13) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
[pers-jacek:3312325] [[INVALID],INVALID] ORTE_ERROR_LOG: Unable to start a daemon on the local node in file ess_singleton_module.c at line 716
[pers-jacek:3312325] [[INVALID],INVALID] ORTE_ERROR_LOG: Unable to start a daemon on the local node in file ess_singleton_module.c at line 172
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_ess_init failed
  --> Returned value Unable to start a daemon on the local node (-127) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Unable to start a daemon on the local node" (-127) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[pers-jacek:3312325] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```

**Comment by dalcinl** [comment]
Of course, my suggestion was just a way to get docs generated. Something else may be very wrong with your environment and/or Open MPI, but that's hardly mpi4py's fault.

**Comment by kloczek** [comment]
it did not help
```console
+ export MPI4PY_RC_INITIALIZE=0
+ MPI4PY_RC_INITIALIZE=0
++ cd build
++ ls -d1 lib.linux-x86_64-cpython-38
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILD/mpi4py-3.1.3/build/lib.linux-x86_64-cpython-38
+ PBR_VERSION=3.1.3
+ PDM_PEP517_SCM_VERSION=3.1.3
+ SETUPTOOLS_SCM_PRETEND_VERSION=3.1.3
+ /usr/bin/sphinx-build -n -T -b man docs/source/usrman build/sphinx/man
Running Sphinx v5.3.0
/usr/lib/python3.8/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (None)/charset_normalizer (3.0.0) doesn't match a supported version!
  warnings.warn(
making output directory... done
[devel-g2v:3192517] mca_base_component_repository_open: unable to open mca_pmix_ext3x: /usr/lib64/openmpi/mca_pmix_ext3x.so: undefined symbol: pmix_value_load (ignored)
[devel-g2v:3192517] [[64641,0],0] ORTE_ERROR_LOG: Not found in file ess_hnp_module.c at line 320
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_pmix_base_select failed
  --> Returned value Not found (-13) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
[devel-g2v:3192515] [[INVALID],INVALID] ORTE_ERROR_LOG: Unable to start a daemon on the local node in file ess_singleton_module.c at line 716
[devel-g2v:3192515] [[INVALID],INVALID] ORTE_ERROR_LOG: Unable to start a daemon on the local node in file ess_singleton_module.c at line 172
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_ess_init failed
  --> Returned value Unable to start a daemon on the local node (-127) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Unable to start a daemon on the local node" (-127) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[devel-g2v:3192515] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```
What more I can try to do?

**Comment by kloczek** [comment]
BTW .. is it really necessary to import `mp4py` module in conf.py?
```console
[tkloczko@devel-g2v usrman]$ grep import conf.py
import os
import sys
import typing
import datetime
import importlib
    import re
autodoc_mock_imports = []
    import sphinx_rtd_theme
        import numpy as np
        import numpy.typing as npt
    from sphinx.domains import python
        from numpy.typing import __all__ as numpy_types
        from mpi4py.typing import __all__ as mpi4py_types
    from sphinx.ext import autodoc
    from sphinx.ext import autosummary
    from sphinx.ext.autosummary import generate
        from mpi4py import MPI
        autodoc_mock_imports.append('mpi4py')
    import apidoc
        mod = importlib.import_module(name)
```

**Comment by kloczek** [comment]
After disable generate documentation during rpm packjage build I found that pytest is failing without any messages
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-mpi4py-3.1.3-5.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-mpi4py-3.1.3-5.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -vv
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.14, pytest-7.1.3, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/tkloczko/rpmbuild/BUILD/mpi4py-3.1.3, configfile: setup.cfg, testpaths: test
collecting ... error: Bad exit status from /var/tmp/rpm-tmp.GPdoK2 (%check)
```

**Comment by dalcinl** [comment]
> it did not help

Oh, sorry! I forgot, there is an issue with these environment variable in latest release. 

Apply the following patch:
```
diff --git a/src/mpi4py/MPI/atimport.pxi b/src/mpi4py/MPI/atimport.pxi
index 78e18d6c..638bc97b 100644
--- a/src/mpi4py/MPI/atimport.pxi
+++ b/src/mpi4py/MPI/atimport.pxi
@@ -95,8 +95,10 @@ cdef int getOptions(Options* opts) except -1:
     except: pass
     try: errors = rc.errors
     except: pass
+    initialize   = getEnv(rc, b"initialize",   initialize)
     threads      = getEnv(rc, b"threads",      threads)
     thread_level = getEnv(rc, b"thread_level", thread_level)
+    finalize     = getEnv(rc, b"finalize",     finalize)
     fast_reduce  = getEnv(rc, b"fast_reduce",  fast_reduce)
     recv_mprobe  = getEnv(rc, b"recv_mprobe",  recv_mprobe)
     errors       = getEnv(rc, b"errors",       errors)
```

Afterwards, setting `MPI4PY_RC_INITIALIZE=0` should work as expected.


> BTW .. is it really necessary to import `mp4py` module in conf.py?

Yes, otherwise you will not get the all the full API reference.
https://mpi4py.readthedocs.io/en/3.1.3/reference/mpi4py.MPI.html
Perhaps you can use a build with MPICH to generate the docs?

> I found that pytest is failing without any messages

I do not use pytest, although I would expect it to work. 
If you look at the various CI configurations, tests are usually run with
```
mpiexec -n 1 python test/runtests.py
mpiexec -n 2 python test/runtests.py
```

Anyway, I believe you have serious issues with your backed MPI implementation. Is the Open MPI package you are used properly tested? I was told that in some Linux distros Open MPI is packaged, but no tests are run or things are very poorly tested. Then guys wanting to package mpi4py go to run all of it tests and they fail miserably, simply because the backend Open MPI package is broken.

**Comment by kloczek** [comment]
> Oh, sorry! I forgot, there is an issue with these environment variable in latest release.
> 
> Apply the following patch:
> 
> ```
> diff --git a/src/mpi4py/MPI/atimport.pxi b/src/mpi4py/MPI/atimport.pxi
> index 78e18d6c..638bc97b 100644
> --- a/src/mpi4py/MPI/atimport.pxi
> +++ b/src/mpi4py/MPI/atimport.pxi
> @@ -95,8 +95,10 @@ cdef int getOptions(Options* opts) except -1:
>      except: pass
>      try: errors = rc.errors
>      except: pass
> +    initialize   = getEnv(rc, b"initialize",   initialize)
>      threads      = getEnv(rc, b"threads",      threads)
>      thread_level = getEnv(rc, b"thread_level", thread_level)
> +    finalize     = getEnv(rc, b"finalize",     finalize)
>      fast_reduce  = getEnv(rc, b"fast_reduce",  fast_reduce)
>      recv_mprobe  = getEnv(rc, b"recv_mprobe",  recv_mprobe)
>      errors       = getEnv(rc, b"errors",       errors)
> ```
> 
> Afterwards, setting `MPI4PY_RC_INITIALIZE=0` should work as expected.

That patch fixed issue with genenerate documentation but did not with pytest.

**Comment by dalcinl** [comment]
> That patch fixed issue with genenerate documentation but did not with pytest.

You have to `unset MPI4PY_RC_INITIALIZE` before running pytest. Did you?

That being said, things may still not work:
1. The fact that you had to set `MPI4PY_RC_INITIALIZE` to generate docs signals that there is some deeper issue with your backend MPI. Documentation generation does not require any actual MPI calls to happen but just module introspection, but running test do require MPI calls, and thus MPI has to be initialized for tests to run.
2. As I said before, I do not use `pytest`. If you insist using it, please invoke with `mpiexec -n 1 python -m pytest`. You may also want to try a `mpiexec -n 2 ...` run.

**Comment by kloczek** [comment]
> You have to unset MPI4PY_RC_INITIALIZE before running pytest. Did you?

With or without that env variable effect is exactly the same.

> That being said, things may still not work:
> 
> 1. The fact that you had to set `MPI4PY_RC_INITIALIZE` to generate docs signals that there is some deeper issue with your backend MPI. Documentation generation does not require any actual MPI calls to happen but just module introspection, but running test do require MPI calls, and thus MPI has to be initialized for tests to run.
> 2. As I said before, I do not use `pytest`. If you insist using it, please invoke with `mpiexec -n 1 python -m pytest`. You may also want to try a `mpiexec -n 2 ...` run.

Did you try to reproduce reported issue?

**Comment by dalcinl** [comment]
> Did you try to reproduce reported issue?

* I tested openmpi v4.1.2 from Fedora 36 repositories with current mpi4py branch `maint` with the patch above applied.
* Running `python -c "import mpi4py.MPI"` works just fine. I'm NOT setting the `MPI4PY_RC_INITIALIZE` variable. This means that MPI is properly initialized. No warnings/errors are printed.
* Invoking`pytest` in the top level source directory seems to be working totally fine.

**Comment by dalcinl** [comment]
@kloczek Any updates? Could you get a resolution to your troubles? Can we close this issue?

**Comment by kloczek** [comment]
Sorry I'm busu a bit .. 
Will try later.

**Comment by dalcinl** [comment]
Release mpi4py-3.1.4 contains the patch for the `MPI4PY_RC_INITIALIZE` environment variable. If the backend MPI implementation continues given issues when mpi4py is imported, just `export MPI4PY_RC_INITIALIZE=0` and Sphinx should still be able to generate the documentation. Before running `pytest`, make sure you `unset MPI4PY_RC_INITIALIZE`. If Open MPI fails, then you should submit an issue upstream to the `openmpi` package maintainer for the Linux distro you are working on, there is nothing I can do about it.
