### ISSUE TITLE
MPI.cpython-38-x86_64-linux-gnu.so: undefined symbol: MPI_Aint_add

### ISSUE THREAD

**Issue by dish0304** [mpi4py/mpi4py#289]
I have problems with mpi4py. The mpi4py was installed by "conda install mpi4py".

MPI4py Version: 3.1.4
Ubuntu 18.04.6 LTS

When running "from mpi4py import MPI", a error happened:
ImportError: /root/miniconda3/envs/pytorch/lib/python3.8/site-packages/mpi4py/MPI.cpython-38-x86_64-linux-gnu.so: undefined symbol: MPI_Aint_add

I tried installing a different version(3.0.3), but the problem persisted.

**Comment by dalcinl** [comment]
Please submit this issue to [conda-forge/mpi4py-feedstock](https://github.com/conda-forge/mpi4py-feedstock). In your new issue, please inform how you created the conda environment, that is, full command line using `conda create ...`, such that others are able to reproduce the problem. The output of `conda list` would be very useful, too.
