### ISSUE TITLE
Spawn and Allocate_shared

### ISSUE THREAD

**Issue by YanyunDuan** [mpi4py/mpi4py#323]
`comm = MPI.COMM_WORLD.Spawn(sys.executable, ['spawn_slave.py'], maxprocs=2)`
spawn returns an `Intercomm`, but `Win.Allocate_shared()` wants an `Intracomm`. 

I want to share the memory from `MPI.COMM_WORLD` to `comm`. Can `comm_intra_merge = comm.Merge(False)` help me to do this? 

I meet a deadlock when running `comm.Merge()`, can anybody help me (see attachments)? 
* [spawn_master.py.log](https://github.com/mpi4py/mpi4py/files/10919556/spawn_master.py.log)
* [spawn_slave.py.log](https://github.com/mpi4py/mpi4py/files/10919557/spawn_slave.py.log)

**Comment by YanyunDuan** [comment]
# [spawn_master.py]
import ctypes
import sys
import numpy as np
from mpi4py import MPI

comm = MPI.COMM_WORLD.Spawn(sys.executable, ['spawn_slave.py'], maxprocs=2)
print("comm ", comm)
comm_intra_merge = comm.Merge(False)
print("Get_remote_group ", comm.Get_remote_group())
print("Get_remote_size ", comm.Get_remote_size())
comm.Disconnect()



# [spawn_slave.py]
import numpy as np
from mpi4py import MPI

# get the parent intercommunicator
comm = MPI.Comm.Get_parent()
print ('slave: rank %d of %d' % (comm.rank, comm.size))
comm.Disconnect()

**Comment by dalcinl** [comment]
You cannot share memory across the two groups of an `Intercomm`. However, it is possible to `Merge()` and get an `Intracomm`. But you have to call `Merge()` on both the master and the slave code!!. I would suggest to pass `Merge()` different boolean values in the master and the slave, let say use `True` in the master and `False()` in the slave.

PS: I will edit your comment above to add proper formatting to your code snippets.

**Comment by YanyunDuan** [comment]
After `Merge()`, the `comm_intra_merge` with size = 3 (it should be 1 master and 2 slaves, right?),  can I share the memory between the master and the 2 slaves (comm = comm_intra_merge)? 
I meet a deadlock when running Allocate_shared (comm = comm_intra_merge),  detailed code is shown below. 

> ```python
> # [spawn_master.py]
> import ctypes
> import sys
> import numpy as np
> from mpi4py import MPI
> 
> comm = MPI.COMM_WORLD.Spawn(sys.executable, ['spawn_slave.py'], maxprocs=2)
> comm_intra_merge = comm.Merge(True)
> print ("master: comm_intra %s" % (comm_intra_merge))
> print("comm_intra_merge_new ", comm_intra_merge.Get_size())
> 
> size = 2*2
> itemsize = MPI.DOUBLE.Get_size() 
> nbytes = size * itemsize
> win = MPI.Win.Allocate_shared(nbytes, itemsize, comm=comm_intra_merge)
> comm.Disconnect()
> ```
> 
> ```python
> # [spawn_slave.py]
> import numpy as np
> from mpi4py import MPI
> 
> comm = MPI.Comm.Get_parent()
> print ('slave: rank %d of %d' % (comm.rank, comm.size))
> comm_intra_merge = comm.Merge(False)
> print ("slave: comm_intra %s" % (comm_intra_merge))
> comm.Disconnect()
> ```

If I call `Allocate_shared` both the master and the slave code, I get an error: `mpi4py.MPI.Exception: MPI_ERR_RMA_SHARED: Memory cannot be shared`.

**Comment by dalcinl** [comment]
> If I call `Allocate_shared` both the master and the slave code,

You have to do it that way, the `Allocate_shared()` operation is collective. If you do not do it that way, you deadlock.

>  I get an error: `mpi4py.MPI.Exception: MPI_ERR_RMA_SHARED: Memory cannot be shared`.

That's because the MPI implementation is not able to figure out that all the MPI processes in the merged comm are in the same compute node and they can actually share memory. 

What backend MPI implementation are you using? Maybe MPICH?

**Comment by YanyunDuan** [comment]
> What backend MPI implementation are you using? Maybe MPICH?
>
> it's mpirun.real (OpenRTE) 4.0.5.

**Comment by dalcinl** [comment]
> it's mpirun.real (OpenRTE) 4.0.5.

Well, that means you are using Open MPI, you should really ask them  https://github.com/open-mpi/ompi/issues. Your issue has nothing to do with mpi4py, it is the backend MPI implementation that does not allow you to share memory.

**Comment by YanyunDuan** [comment]
> > Well, that means you are using Open MPI, you should really ask them https://github.com/open-mpi/ompi/issues. Your issue has nothing to do with mpi4py, it is the backend MPI implementation that does not allow you to share memory.

 I see, Thanks!

**Comment by dalcinl** [comment]
I forgot to mention something. If you ever switch use MPICH, I think you will have the same problem. The reason for this is explained pmodels/mpich#6100. Basically, when you use `Spawn()`, MPICH treats the parent and child processes as if they where in separate compute nodes, and communication between them occurs via *netmod* modules (and not shared memory channels). This is arguably something that could be certainly improved, but that may require a lot of development efforts as it would involve a redesign of MPICH internals.

@hzhou Here you have another reason (beyond performance) for somehow improving `MPI_Comm_spawn` for processes that are actually able to share memory.
