### ISSUE TITLE
An error is reported when running the tutorial code in Notebook

### ISSUE THREAD

**Issue by jian899** [mpi4py/mpi4py#336]
Hello everyone, when I run the tutorial code in jupyter lab, the following error message appears, how can I solve it, thank you!

Note:
Python 3.9.16
Part of the library that exists in the environment
` conda list mpi`
packages in environment at /home/jsaon/miniconda3/envs/fermi3ML:
Name                    Version                   Build  Channel
```
c-compiler                1.5.2                h0b41bf4_0    conda-forge
compilers                 1.5.2                ha770c72_0    conda-forge
cxx-compiler              1.5.2                hf52228f_0    conda-forge
fortran-compiler          1.5.2                hdb1a99f_0    conda-forge
mpi                       1.0                     openmpi    conda-forge
mpi4py                    3.1.4            py39h5418507_0    conda-forge
openmpi                   4.1.5              h414af15_101    conda-forge
tempita                   0.5.3dev        py39hf3d152e_1002    conda-forge
```
```
from mpi4py import MPI

comm = MPI.COMM_WORLD
rank = comm.Get_rank()

if rank == 0:
    data = {'a': 7, 'b': 3.14}
    comm.send(data, dest=1, tag=11)
elif rank == 1:
    data = comm.recv(source=0, tag=11)
```
```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[1], line 8
      6 if rank == 0:
      7     data = {'a': 7, 'b': 3.14}
----> 8     comm.send(data, dest=1, tag=11)
      9 elif rank == 1:
     10     data = comm.recv(source=0, tag=11)

File mpi4py/MPI/Comm.pyx:1406, in mpi4py.MPI.Comm.send()

File mpi4py/MPI/msgpickle.pxi:212, in mpi4py.MPI.PyMPI_send()

Exception: MPI_ERR_RANK: invalid rank
```

**Comment by dalcinl** [comment]
You are most likely running with a single MPI process, but the example requires two. What's the output of `print(MPI.COMM_WORLD.Get_size()` ? If it prints `1`, there there you have the problem, it should print `2`.

Running MPI examples on Jupyter is slightly complicated, as the Python processes running your code have to be executed with `mpiexec` (or  similar alternative mechanisms). Please read the Jupyter docs about how to setup and use an MPI cluster.

**Comment by jian899** [comment]
Ok,When I run `print(MPI.COMM_WORLD.Get_size()` in ipython, here is the result:
```
$ ipython
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.11.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: print(MPI.COMM_WORLD.Get_size()
   ...:
```
So how do I add two MPI processes?

**Comment by dalcinl** [comment]
> So how do I add two MPI processes?

In my previous comment I asked you to read the IPython or Jupyter docs about how to setup and use an MPI cluster, please do.

However, my recommendation is that you should not use interactive IPython/Jupyter. Instead, write your MPI code in some `script.py` file, and then run it in the terminal (could very well be a JupiterLab Terminal) with:
```
mpiexec -n 2 python script.py
```
This is the advice we provide [here](https://mpi4py.readthedocs.io/en/stable/tutorial.html#running-python-scripts-with-mpi).
