### ISSUE TITLE
MPIPoolExecutor in Python>3.10

### ISSUE THREAD

**Issue by antoscha** [mpi4py/mpi4py#350]
Hello,  

Since Python 3.11 it's restricted to use pool executors other that `ThreadPoolExecutor` from concurrent.futures:  
https://github.com/python/cpython/issues/87400  

What can be workaround to continue using `MPIPoolExecutor` as default in asynchronous environment?  

Anton K.

**Comment by dalcinl** [comment]
IMHO, you should ask these questions to the developers that decided to deprecated and ultimately reject executors other than thread pool. From the various related issues, looks like the argument are "asyncio internals assume that" or "processes pools are untested". *Prima facie*, it does not look like these arguments are rock solid, but they probably had good reasons to do it. Interestingly, looks like you were using the `mpi4py.futures` executor without issues. Is that correct? In that case, maybe you should raise your complaints.

Regarding workarounds, I can imagine a few. I don't have time right now to tests them, but the first one I would try is the following:

```python
class CheatingExecutor(MPIPoolExecutor, concurrent.futures.ThreadPoolExecutor):
    def _adjust_thread_count(self):  # make sure this one is never called
        raise NotImplementedError
```

**Comment by dalcinl** [comment]
Happy to know my quick hack let you move forward. IMHO, you should really raise this concern upstream. I still don't understand what's the issue Python devs are trying to solve.
