### ISSUE TITLE
Allocating shared arrays in a loop causes memory leak despite using `Win.Free()`?

### ISSUE THREAD

**Issue by rohskopf** [mpi4py/mpi4py#354]
I have an application where I would like to loop over the creation of shared arrays.

Minimal example to run with `mpirun -np 2 python example.py` :

```
from mpi4py import MPI 
import numpy as np 

comm = MPI.COMM_WORLD 

for i in range(0,100000000):

    # create a shared array of some size and type
    size = 100000 
    itemsize = MPI.DOUBLE.Get_size() 
    if comm.Get_rank() == 0: 
        nbytes = size * itemsize 
    else: 
        nbytes = 0

    
    # on rank 0, create the shared block
    # on rank 1 get a handle to it (known as a window in MPI speak)
    win = MPI.Win.Allocate_shared(nbytes, itemsize, comm=comm) 

    # create a numpy array whose data points to the shared mem
    buf, itemsize = win.Shared_query(0)
    assert itemsize == MPI.DOUBLE.Get_size() 
    ary = np.ndarray(buffer=buf, dtype='d', shape=(size,))

    win.Free()
```

Without `win.Free()` there is a definitely noticeable leak in `top`. However even with `win.Free()`, it seems like memory usage of the program is still increasing.

Is there a proper way to deallocate everything?

**Comment by rohskopf** [comment]
This might be a version problem. I tried the following script to measure a leak:

```
from mpi4py import MPI 
import numpy as np
import gc
import psutil

def rss():
    return psutil.Process().memory_info().rss
    

comm = MPI.COMM_WORLD 

initial_memory = rss()
for i in range(0,1000000000):

    
    # create a shared array
    size = int(1e9)
    itemsize = MPI.DOUBLE.Get_size() 
    if comm.Get_rank() == 0: 
        nbytes = size * itemsize 
    else: 
        nbytes = 0

    # on rank 0, create the shared block
    # on rank 1 get a handle to it (known as a window in MPI speak)
    win = MPI.Win.Allocate_shared(nbytes, itemsize, comm=comm) 

    # create a numpy array whose data points to the shared mem
    buf, itemsize = win.Shared_query(0)
    assert itemsize == MPI.DOUBLE.Get_size() 
    ary = np.ndarray(buffer=buf, dtype='d', shape=(size,))

    win.Free()

    if comm.Get_rank() == 0:
        if i % 1000 == 0:
            print(f"{i} {rss()-initial_memory}")
```

On one machine (MacOS) I observe a definite increase in memory with iterations. Using this MPI version:

```
>>> MPI.Get_library_version()
'Open MPI v2.0.4, package: Open MPI xxxxx Distribution, ident: 2.0.4, repo rev: v2.0.3-102-gdb3ffbe, Nov 07, 2017\x00'
```

On another machine (Linux) I observe an initial jump (probably cache) and then flatline in memory; this is perfectly normal I think.  Using this MPI version:

```
>>> MPI.Get_library_version()
'Open MPI v3.1.6, package: Open MPI xxxxx Distribution, ident: 3.1.6, repo rev: v3.1.6, Mar 18, 2020\x00'
```

There doesn't seem to be a leak when using the new MPI version.

**Comment by dalcinl** [comment]
mpi4py does not free MPI handles when objects are garbage collected. It is the user responsibility to call `xxx.Free()` to free resources. I know this is unpythonic, but there are many technical reasons for such behavior. If you do not call `win.Free()` explicitly, then of course you will have memory leaks.

When you execute `win.Free()`, mpi4py truly calls `MPI_Win_free` on the `MPI_Win` handle, not caching, refcounting, or smart behavior under the scenes. Therefore, any memory leaks are the fault of the backend MPI implementation you are using. You should report your issues/concerns to Open MPI developers, but I'm not sure they would really take any action, the v2 and v3 release series are retired and thus no longer supported.
