### ISSUE TITLE
CuPy MPI demo is failing for Bcast

### ISSUE THREAD

**Issue by lefarov** [mpi4py/mpi4py#36]
Description
---------------
I'm trying to run a [CuPy MPI demo](https://github.com/mpi4py/mpi4py/blob/master/demo/cuda-aware-mpi/use_cupy.py). `Allreduce` example is working but `Bcast` and p2p examples are failing with the segmentation fault error:
```
Caught signal 11 (Segmentation fault: invalid permissions for mapped object at address 0x2b15b6a00310)
```
Env
-----
1. `openmpi/4.0.1` build with CUDA support
2. `cuda/10.2.89`
3. `mpi4py/3.1.0a0`
4. `cupy-cuda102/8.5.0`

Additional
-------------
I've tried to run the example with a single GPU and with multiple GPUs (manually specifying the `Device` dependent on a rank). In both cases I'm still getting the error.

**Comment by leofang** [comment]
May I ask how did you install all these dependencies? Built from source? PyPI? Conda?

Another thing, how did you launch the code? Could you try `mpirun -n 2 --mca opal_cuda_support 1 python demo/cuda-aware-mpi/use_cupy.py` since you're using Open MPI?

**Comment by leofang** [comment]
3rd thing: Could you post the full log?

**Comment by lefarov** [comment]
> May I ask how did you install all these dependencies? Built from source? PyPI? Conda?

Sure, some for some of it I don't have complete information though.
1. `openmpi` is build from source with CUDA support by the cluster admins
2. `cuda` centrally installed by the cluster admins
3. `mpi4py` installed from PyPI
4. `cupy-cuda102` installed from the v10.2 wheel

> Another thing, how did you launch the code? Could you try `mpirun -n 2 --mca opal_cuda_support 1 python demo/cuda-aware-mpi/use_cupy.py` since you're using Open MPI?

I've run it with ` mpirun -n 2 python demo/cuda-aware-mpi/use_cupy.py`. I've also tried `opal_cuda_support 1` flag, but got the same error.

> Could you post the full error log?

```shell
Caught signal 11 (Segmentation fault)
==== backtrace ====
 2 0x00000000000690dc mxm_handle_error()  /var/tmp/OFED_topdir/BUILD/mxm-3.7.3112/src/mxm/util/debug/debug.c:641
 3 0x000000000006962c mxm_error_signal_handler()  /var/tmp/OFED_topdir/BUILD/mxm-3.7.3112/src/mxm/util/debug/debug.c:616
 4 0x000000000000f630 _L_unlock_13()  funlockfile.c:0
 5 0x000000000014cc40 __memcpy_ssse3()  :0
 6 0x0000000000022ab7 ucp_dt_pack()  ??:0
 7 0x000000000002bb55 ucp_tag_offload_unexp_eager()  ??:0
 8 0x0000000000013553 uct_mm_ep_am_bcopy()  ??:0
 9 0x000000000004083e ucp_wireup_select_sockaddr_transport()  ??:0
10 0x000000000002d0ac ucp_tag_offload_unexp_eager()  ??:0
11 0x00000000000373b5 ucp_tag_send_nb()  ??:0
12 0x0000000000004fe6 mca_pml_ucx_isend()  ??:0
13 0x000000000009bb00 ompi_coll_base_bcast_intra_generic()  ??:0
14 0x000000000009c117 ompi_coll_base_bcast_intra_binomial()  ??:0
15 0x00000000000054dc ompi_coll_tuned_bcast_intra_dec_fixed()  ??:0
16 0x0000000000065d79 MPI_Bcast()  ??:0
17 0x00000000000e6917 __pyx_pf_6mpi4py_3MPI_4Comm_82Bcast()  /home/lma7rng/projects/mpi4py/src/mpi4py.MPI.c:113896
18 0x00000000000e6917 __pyx_pf_6mpi4py_3MPI_4Comm_82Bcast()  /home/lma7rng/projects/mpi4py/src/mpi4py.MPI.c:113896
19 0x00000000000e6917 __pyx_pw_6mpi4py_3MPI_4Comm_83Bcast()  /home/lma7rng/projects/mpi4py/src/mpi4py.MPI.c:113835
20 0x0000000000165914 _PyMethodDef_RawFastCallKeywords()  /tmp/build/80754af9/python_1598874792229/work/Objects/call.c:693
21 0x000000000016c7af _PyMethodDescr_FastCallKeywords()  /tmp/build/80754af9/python_1598874792229/work/Objects/descrobject.c:288
22 0x00000000001d1c7c call_function()  /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:4593
23 0x00000000001d1c7c _PyEval_EvalFrameDefault()  /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3110
24 0x0000000000114829 _PyEval_EvalCodeWithName()  /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3930
25 0x0000000000115714 PyEval_EvalCodeEx()  /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3959
26 0x000000000011573c PyEval_EvalCode()  /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:524
27 0x000000000022cf14 run_mod()  /tmp/build/80754af9/python_1598874792229/work/Python/pythonrun.c:1035
28 0x0000000000237331 PyRun_FileExFlags()  /tmp/build/80754af9/python_1598874792229/work/Python/pythonrun.c:988
29 0x0000000000237523 PyRun_SimpleFileExFlags()  /tmp/build/80754af9/python_1598874792229/work/Python/pythonrun.c:429
30 0x0000000000238655 pymain_run_file()  /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:462
31 0x0000000000238655 pymain_run_filename()  /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:1652
32 0x0000000000238655 pymain_run_python()  /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:2913
33 0x0000000000238655 pymain_main()  /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:3460
34 0x000000000023877c _Py_UnixMain()  /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:3495
35 0x0000000000022555 __libc_start_main()  ??:0
36 0x00000000001dcff0 _start()  /home/rdonnelly/mc/conda-bld/compilers_linux-64_1534865402226/work/.build/src/glibc-2.12.2/csu/../sysdeps/x86_64/elf/start.S:103
===================
```

**Comment by leofang** [comment]
@lefarov Thanks. It looks like your Open MPI is built with UCX? Could you post the output of `ompi_info`? If so, you may need additional flags to turn on CUDA (I am not sure, can look up later).

Another check off top of my head is to make sure all these dependencies (Open MPI/UCX, CuPy) link to the same CUDA library.

**Comment by leofang** [comment]
Please also check this:

> 6. I’m running UCX with GPU memory and geting a segfault, why?
>
> Most likely UCX does not detect that the pointer is a GPU memory and tries to access it from CPU. It can happen if UCX is not compiled with GPU support, or fails to load CUDA or ROCm modules due to missing library paths or version mismatch. Please run ucx_info -d | grep cuda or ucx_info -d | grep rocm to check for UCX GPU support.

http://openucx.github.io/ucx/faq.html

**Comment by lefarov** [comment]
@leofang Thanks for looking into that. Yes, indeed `OpenMPI` is build with `UCX`. We do have a scheduled cluster maintenance right now. So I will provide the output of  `ompi_info` / `ucx_info` and try your suggestions once everything is back up again.

**Comment by leofang** [comment]
@lefarov Any update?

**Comment by leofang** [comment]
@lebedov I'm closing given the inactivity, but please feel free to reopen if it is still an issue to you.

**Comment by lebedov** [comment]
I'm not @lefarov

**Comment by leofang** [comment]
Oops sorry @lebedov, I meant to ping @lefarov but GitHub autocomplete messed up.
