### ISSUE TITLE
ERROR: Could not build wheels for mpi4py, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by LI-Yiquan** [mpi4py/mpi4py#368]
I successfully install mpi4py on June 13, but when I try to reinstall it on June 14, it gives me this error: "ERROR: Could not build wheels for mpi4py, which is required to install pyproject.toml-based projects". Could anyone help me with that? Maybe it is related to some recent updates?

**Comment by noahfranz13** [comment]
@LI-Yiquan How did you fix this? I'm getting the same error message and do not understand what I'm doing wrong!

**Comment by LI-Yiquan** [comment]
"conda install mpi4py" works on my device. Maybe you can try this command.

Noah Franz ***@***.***> 于2023年6月22日周四 11:48写道：
