### ISSUE TITLE
getting mpi4py to ignore conda's MPI

### ISSUE THREAD

**Issue by bernstei** [mpi4py/mpi4py#377]
I'm trying to get mpi4py installed on a Linux HPC where the python comes from conda, but the MPI I want to use does not. Unfortunately, this leads to the need to install mpi4py with pip, which I gather from pervious issues isn't entirely well behaved when python comes from conda (but at least the `compilers` conda package isn't installed according to `conda list`).  I tried it with just getting `mpicc` from the PATH, or specifying explicitly with `MPICC`, but in either case I end up with mixed up versioning for the mpi library. In particular, when I do 
```
ldd ~/.local/lib/python3.9/site-packages/mpi4py/MPI.cpython-39-x86_64-linux-gnu.so
```
I get (among other lines)
```
	libmpi.so.12 => /app/CSE/CSE.20220624/Release/anaconda3-2022.05/lib/libmpi.so.12 (0x00007f2417676000)
```
instead of the path that's consistent with my `mpicc`, which is 
```
/app/openmpi/platforms/openmpi-3.1.3/gcc-8.2.0/lib/....
```
Is there any obvious way to figure out why it's linking to the wrong mpi library? If I run anyway I get a missing symbol at runtime, which isn't particular surprising if it built with the system openmpi but is running with the conda one, or vice versa.

**Comment by bernstei** [comment]
And I checked that the desired MPI's path is ahead of conda's in `LD_LIBRARY_PATH`.  However, when I pip install with -v I see the following link command
```
  /app/openmpi/platforms/openmpi-3.1.3/gcc-8.2.0/bin/mpicc -shared -Wl,-rpath,/app/CSE/CSE.20220624/Release/anaconda3-2022.05/lib -Wl,-rpath-link,/app/CSE/CSE.20220624/Release/anaconda3-2022.05/lib -L/app/CSE/CSE.20220624/Release/anaconda3-2022.05/lib -L/app/CSE/CSE.20220624/Release/anaconda3-2022.05/lib -Wl,-rpath,/app/CSE/CSE.20220624/Release/anaconda3-2022.05/lib -Wl,-rpath-link,/app/CSE/CSE.20220624/Release/anaconda3-2022.05/lib -L/app/CSE/CSE.20220624/Release/anaconda3-2022.05/lib build/temp.linux-x86_64-cpython-39/src/MPI.o -Lbuild/temp.linux-x86_64-cpython-39 -ldl -o build/lib.linux-x86_64-cpython-39/mpi4py/MPI.cpython-39-x86_64-linux-gnu.so
```
Could the issue be that the conda path is explicitly added by the `mpicc` link command?

**Comment by leofang** [comment]
Sorry, I am not sure what you're trying to achieve. Let me ask this: Have you tried the "external MPI" trick that conda-forge designed to support HPC clusters? 
https://conda-forge.org/docs/user/tipsandtricks.html#using-external-message-passing-interface-mpi-libraries
Basically, if you are using MPICH/Open MPI (or their ABI-compatible variants), you can install an empty MPI package from conda-forge, but with real mpi4py & co installed. Then, you just need to ensure your own MPI implementation is supplied and locatable by the dynamic linker. No need to rebuild anything.

**Comment by bernstei** [comment]
I'm trying to get an mpi4py that uses the centrally installed MPI instead of the one that's installed as part of conda. Sounds like that trick you linked to should do exactly what I want, if I can get it to work (and I worry because the conda environment already installed at the HPC has "real" conda mpi packages installed).  However, it's not working. I get
```
(pymatnext) [noamb@mustang09 ~ ]$ conda install "mpich=x.y.z=external_*"
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - mpich==x.y.z[build=external_*]

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
```
Are those "x.y.z" placeholders, or are they meant to be used literally, like I tried?

**Comment by leofang** [comment]
x.y.z should not be taken literally, it should be the version you need, for example replace it with 3.* to get MPICH 3 (`mpich=3.*=external_*`).

**Comment by dalcinl** [comment]
@leofang Maybe we should convert this issue on a discussion under the Q&A category?
