### ISSUE TITLE
mpi4py.futures unable to resolve imports of other modules in same package as main script 

### ISSUE THREAD

**Issue by adriaanpardoel** [mpi4py/mpi4py#38]
I'm trying to use the MPIPoolExecutor on a Beowulf HPC cluster running Maui and Torque. I have a Python project consisting of multiple files (so a package containing multiple modules). The project structure is basically like this:

```
my_project
  - __init__.py
  - my_main_script.py
  - my_other_module.py
```

Using the MPIPoolExecutor in the main script works fine until I want to import another module inside the same package.

This simple code inside `my_main_script.py` works without problems:
```
from mpi4py.futures import MPIPoolExecutor


def f(x):
    return x ** 2


if __name__ == '__main__':
    with MPIPoolExecutor() as executor:
        print(list(executor.map(f, range(10))))
```

To run the code, I used this command: `mpiexec -n 4 -rf my_rank_file python -m mpi4py.futures my_main_script.py`

However, let's say that the function `f` is imported from another file in the same folder, `my_other_module.py`. Then `my_main_script.py` looks like this:
```
from mpi4py.futures import MPIPoolExecutor
from my_other_module import f


if __name__ == '__main__':
    with MPIPoolExecutor() as executor:
        print(list(executor.map(f, range(10))))
```

When I run this with the same command, I get the following error: `ModuleNotFoundError: No module named 'my_other_module'`

The error only seems to occur on worker nodes, not on the master node.

I'm using Open MPI 1.8.8, mpi4py 3.0.3, and Python 3.8.7.

**Comment by dalcinl** [comment]
This is likely as `sys.path` issue. I cannot reproduce the problem on my workstation. But you are running in a cluster, so things are definitely different. Please submit a function that prints `sys.path`, that is

```python
def f():
    import sys
    print(sys.path)
```

BTW, are you sure that the `my_project` directory is accesible in the compute nodes?

**Comment by adriaanpardoel** [comment]
Thank you for pointing me in the right direction! It was indeed a `sys.path` issue. The project structure is slightly more complicated than I explained above and the Python script is usually ran from one level higher than the script itself. Normally the script path is always present in `sys.path`, but for some reason it's not when I run the code using the mpi4py.futures module, though in that case the working directory is present in `sys.path`. Not sure what's causing this but I could work around it by adding the following code to the beginning of my script:

```
import os, sys
sys.path.append(os.path.dirname(__file__))
```

**Comment by dalcinl** [comment]
@adriaanpardoel Could you please try applying the following patch to mpi4py sources? The diff is from the master branch, but It should likely apply to latest release tarball. 

This fix is definitely valid for Python 3. There are a few technical issues with Python 2 that would require some extra thinking.

```diff
diff --git a/src/mpi4py/futures/_lib.py b/src/mpi4py/futures/_lib.py
index 5ced66b..b76e9ab 100644
--- a/src/mpi4py/futures/_lib.py
+++ b/src/mpi4py/futures/_lib.py
@@ -728,6 +728,8 @@ def import_main(mod_name, mod_path, init_globals, run_name):
         if mod_name:  # pragma: no cover
             runpy.run_module(mod_name, run_name=run_name, alter_sys=True)
         elif mod_path:  # pragma: no branch
+            if not getattr(sys.flags, 'isolated', 0):  # pragma: no branch
+                sys.path[0] = os.path.realpath(os.path.dirname(mod_path))
             runpy.run_path(mod_path, run_name=run_name)
         sys.modules['__main__'] = sys.modules[run_name] = module
     except:  # pragma: no cover
```

**Comment by adriaanpardoel** [comment]
The patch above fixes the issue for me, now my code works without the need for the extra two lines that I posted a couple days ago
