### ISSUE TITLE
Build fails with Cython 3.0

### ISSUE THREAD

**Issue by limburgher** [mpi4py/mpi4py#383]
Build of 3.1.4 fails with Python 3.12 and Cython 3. 

[build-3.1.4-5.fc39.log](https://github.com/mpi4py/mpi4py/files/12220431/build-3.1.4-5.fc39.log)

**Comment by dalcinl** [comment]
The current tarball release of mpi4py cannot use Cython 3.

If I understand correctly, Fedora 39 has Cython 0.29.x. 

* Add Cython to your BuildRequires in the spec file.

* Before the ``%py3_build`` command, run the following in the source tree to regenerate the C sources, 
```
/usr/bin/python3 conf/cythonize.py
```

* Continue as usual with the `%py3_build` command

PS: See this file https://github.com/conda-forge/mpi4py-feedstock/blob/main/recipe/meta.yaml#L16 for an example of my proposed workaround.

**Comment by dalcinl** [comment]
Next major release mpi4py 4.0.0 will require Cython >= 3.0.0.

**Comment by dalcinl** [comment]
@limburgher The latest patch release 3.1.5 tarball should work with Cython 3.0.x, albeit with warnings related to deprecated syntax. As the Cython-generated C sources are included in the tarball, Cython is not strictly required to build, although that will change for next major 4.0.0 release. I have not tested things thoroughly, though.

**Comment by limburgher** [comment]
It does when I update the Python build macros I use for the RPM, since the old macros still use setup.py wihch requires cython<3.0.  However now it results in the python3-mpi4py-openmpi RPM requiring libmpi.so.12(), rather than the libmpi.so.40() provided by openmpi. Do you know why that might be?

**Comment by dalcinl** [comment]
`libmpi.so.12` corresponds to MPICH, not Open MPI, so my guess is that the code in the mp4py.spec file is perhaps loading the wrong MPI module. I the spec file available online somewhere to take a look?

**Comment by limburgher** [comment]
The previous spec is here:

My current working copy is here: https://fedorapeople.org/~limb/mpi4py.spec
https://src.fedoraproject.org/rpms/mpi4py/tree/rawhide

**Comment by dalcinl** [comment]
@limburgher  The manipulation with `src/mpi4py/__init__.py` seems unnecessary, although that is for sure unrelated to your issue. Looks like the problem is that the required updates to the spec files have to be deeper of what you did so far.

You  are switching to use the new pyproject-based macros, so I bet the issue is related to the fact that now things work differently. If you invoke `%pyproject_wheel` to build a wheel file, then maybe the second time overwrites the first time, and then when you `%install`, you actually install twice the wheel that was built second, that is the MPICH one. That would explain the behavior you are seeing. All these lines with `mv build mpich/openmpi` anv viceversa are most likely obsolete and irrelevant to the `%pyproject_xxx` macros, and you should remove them.

I'm not an expert fo the RPM build infrastructure, but I believe all you have to do is to figure out where the `%pyproject_wheel` macro  stores the intermediate wheel file, and then move it to a mpich/openmpi directory for each mpich/openmpi build. After `%build`, you can move things around back to execute `%pyproject_install`, and you should be things working.

According to the [docs](https://src.fedoraproject.org/rpms/pyproject-rpm-macros/) 
> %pyproject_install installs all wheels in pyproject-wheeldir/ located in the root of the source tree.
So maybe there you have the answer to your problems, you have to :

```
%build
%pyproject_wheel
mv pyproject-wheeldir pyproject-wheeldir-openmpi
...
%pyproject_wheel
mv pyproject-wheeldir pyproject-wheeldir-mpich
...
```

and

```
%install
mv pyproject-wheeldir-openmpi pyproject-wheeldir
%pyproject_install
mv pyproject-wheeldir pyproject-wheeldir-openmpi
...
mv pyproject-wheeldir-mpich pyproject-wheeldir
%pyproject_install
mv pyproject-wheeldir pyproject-wheeldir-mpich
...
```

**Comment by limburgher** [comment]
I've been experimenting with this, and I noticed that the build succeeds but ends with:

RPM build warnings:
    Duplicate build-ids /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib64/python3.12/site-packages/openmpi/mpi4py/MPI.cpython-312-x86_64-linux-gnu.so and /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib64/python3.12/site-packages/mpich/mpi4py/MPI.cpython-312-x86_64-linux-gnu.so
    Duplicate build-ids /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib64/python3.12/site-packages/openmpi/mpi4py/dl.cpython-312-x86_64-linux-gnu.so and /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib64/python3.12/site-packages/mpich/mpi4py/dl.cpython-312-x86_64-linux-gnu.so
    Duplicate build-ids /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib64/python3.12/site-packages/openmpi/mpi4py/lib-pmpi/libmpe.so and /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib64/python3.12/site-packages/mpich/mpi4py/lib-pmpi/libmpe.so
    Duplicate build-ids /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib64/python3.12/site-packages/openmpi/mpi4py/lib-pmpi/libvt-hyb.so and /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib64/python3.12/site-packages/mpich/mpi4py/lib-pmpi/libvt-hyb.so
    Duplicate build-ids /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib64/python3.12/site-packages/openmpi/mpi4py/lib-pmpi/libvt-mpi.so and /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib64/python3.12/site-packages/mpich/mpi4py/lib-pmpi/libvt-mpi.so
    Duplicate build-ids /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib64/python3.12/site-packages/openmpi/mpi4py/lib-pmpi/libvt.so and /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib64/python3.12/site-packages/mpich/mpi4py/lib-pmpi/libvt.so
    Duplicate build-ids /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib/debug/usr/lib64/python3.12/site-packages/openmpi/mpi4py/MPI.cpython-312-x86_64-linux-gnu.so-3.1.5-1.fc40.x86_64.debug and /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib/debug/usr/lib64/python3.12/site-packages/mpich/mpi4py/MPI.cpython-312-x86_64-linux-gnu.so-3.1.5-1.fc40.x86_64.debug
    Duplicate build-ids /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib/debug/usr/lib64/python3.12/site-packages/openmpi/mpi4py/dl.cpython-312-x86_64-linux-gnu.so-3.1.5-1.fc40.x86_64.debug and /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib/debug/usr/lib64/python3.12/site-packages/mpich/mpi4py/dl.cpython-312-x86_64-linux-gnu.so-3.1.5-1.fc40.x86_64.debug
    Duplicate build-ids /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib/debug/usr/lib64/python3.12/site-packages/openmpi/mpi4py/lib-pmpi/libmpe.so-3.1.5-1.fc40.x86_64.debug and /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib/debug/usr/lib64/python3.12/site-packages/mpich/mpi4py/lib-pmpi/libmpe.so-3.1.5-1.fc40.x86_64.debug
    Duplicate build-ids /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib/debug/usr/lib64/python3.12/site-packages/openmpi/mpi4py/lib-pmpi/libvt-hyb.so-3.1.5-1.fc40.x86_64.debug and /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib/debug/usr/lib64/python3.12/site-packages/mpich/mpi4py/lib-pmpi/libvt-hyb.so-3.1.5-1.fc40.x86_64.debug
    Duplicate build-ids /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib/debug/usr/lib64/python3.12/site-packages/openmpi/mpi4py/lib-pmpi/libvt-mpi.so-3.1.5-1.fc40.x86_64.debug and /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib/debug/usr/lib64/python3.12/site-packages/mpich/mpi4py/lib-pmpi/libvt-mpi.so-3.1.5-1.fc40.x86_64.debug
    Duplicate build-ids /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib/debug/usr/lib64/python3.12/site-packages/openmpi/mpi4py/lib-pmpi/libvt.so-3.1.5-1.fc40.x86_64.debug and /home/gwyn/rpmbuild/BUILDROOT/mpi4py-3.1.5-1.fc40.x86_64/usr/lib/debug/usr/lib64/python3.12/site-packages/mpich/mpi4py/lib-pmpi/libvt.so-3.1.5-1.fc40.x86_64.debug

This only occurs if the contents are identical. This would suggest to me that the openmpi version is being build with mpich support.

**Comment by dalcinl** [comment]
Looking at the source of the macros, looks like you should use `%{_pyproject_wheeldir}` and not just `pyproject-wheeldir` as I suggested above. 

> This only occurs if the contents are identical. This would suggest to me that the openmpi version is being build with mpich support.

Of because you are overwriting the intermediate wheel file, or perhaps installing the wrong one. I'm  a long time user of Fedora, but I have not used `rpmbuild` for ages, so I'm not sure how to reproduce the issue myself.

**Comment by limburgher** [comment]
I've temporarily resolved the issue by reverting to using the old macros and patching the cython requirement ceiling out of setup.py. I'll revisit this with the next mpi4py release.
