### ISSUE TITLE
blocking in the neighbor collective communication 

### ISSUE THREAD

**Issue by bluebluecard** [mpi4py/mpi4py#388]
Hello, I tried to run a gather operation in the Distributed communicator, and I run the following command:

mpirun -n 2 python3 script_name.py

and there is no output from this command, it seems that there is a blocking in the process. 
Do you know how to modify the following code such that it can output the desired result?

PS: if I remove this code: recv = dist_comm.neighbor_allgather(rank), it runs normally. 

    from mpi4py import MPI
    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()
    if rank == 0:
	    dist_comm = comm.Create_dist_graph_adjacent([0],[1])
    else:
	    dist_comm = comm.Create_dist_graph_adjacent([1],[0])
    neigh = dist_comm.Get_dist_neighbors()
    recv = dist_comm.neighbor_allgather(rank)

    print(rank,neigh,recv)

**Comment by dalcinl** [comment]
I cannot make sense of the `sources` and `destinations` argument value in this example of yours. 

Maybe you meant to do:

```python
if rank == 0:
    dist_comm = comm.Create_dist_graph_adjacent([1],[1])
else:
    dist_comm = comm.Create_dist_graph_adjacent([0],[0])
```

**Comment by bluebluecard** [comment]
OK, I just checked the manual for the MPI 4.0, I understand their meaning. Thanks a lot.
