### ISSUE TITLE
Segmentation fault originating from `MPI/msgpickle.pxi`

### ISSUE THREAD

**Issue by IshaanDesai** [mpi4py/mpi4py#389]
Hi,
I am using mpi4py version `3.13.3` on Ubuntu 20.04. I have written up code for asynchronous p2p communication in [my python package](https://github.com/precice/micro-manager/blob/develop/micro_manager/adaptivity/global_adaptivity.py#L264-L321). While running simulations using 8 processes, at about 60% of the simulation time I see the following:

```bash
  File "/home/desaiin/.local/lib/python3.8/site-packages/micro_manager/adaptivity/global_adaptivity.py", line 234, in _update_inactive_sims
    state, global_id = req.wait()
  File "mpi4py/MPI/Request.pyx", line 266, in mpi4py.MPI.Request.wait
  File "mpi4py/MPI/msgpickle.pxi", line 450, in mpi4py.MPI.PyMPI_wait
mpi4py.MPI.Exception: MPI_ERR_TRUNCATE: message truncated
[ipvs-epyc1:84079] *** Process received signal ***
[ipvs-epyc1:84079] Signal: Segmentation fault (11)
[ipvs-epyc1:84079] Signal code:  (128)
[ipvs-epyc1:84079] Failing at address: (nil)
```

I understand that it is probably hard to say what is going wrong by just looking at this output. I am looking for clues to start investigating parts of my implementation, like is this a memory issue or am I using requests in a wrong way? Can I get more error output? Any clue would be of great help.

**Comment by dalcinl** [comment]
Your code is using the lowercase method `Comm.irecv()`. Given the semantics of `MPI_Irecv()`, mpi4py cannot possible know the length in bytes of the incoming pickled message. Therefore, mpi4py allocates a temporary buffer of uses a 32 KiB to receive the incoming pickled stream. This works well as long as the messages are small. That's obviously not your case, therefore MPI errors with `MPI_ERR_TRUNCATE`.

There are two possible workarounds

1. You ask mpi4py to use a larger upper bound for the internally-allocated buffer to receive the message.
2. You provide mpi4py with a buffer where to store the pickled stream until the request is completed.

* Example of (1)
```python
bufsize = 1 << 30 # allocate and use a temporary 1 MiB buffer size
request = comm.irecv(bufsize, source=..., tag=...)
```

* Example of (2)
```
buf = bytearray(1 << 30)  # user-provided 1 MiB buffer
request = comm.irecv(buf, source=..., tag=...)
```

Before you make the obvious observation/request: I'm very well aware that mpi4py is poorly documented. Things have improved lately, but with most of the enhancements coming from a single source, things are not going particularly fast.

Besides documentation, mpi4py should provide a more convenient way to specify the buffer size at runtime to tune things according to the specific needs of applications. For example, an `mpi4py.rc.irecv_bufsize` and corresponding environment variable `MPI4PY_RC_IRECV_BUFSIZE`.

**Comment by IshaanDesai** [comment]
Thanks for the informative response @dalcinl 

I tried the first solution and it worked! I will keep the solutions in mind in the future.

> Before you make the obvious observation/request: I'm very well aware that mpi4py is poorly documented. Things have improved lately, but with most of the enhancements coming from a single source, things are not going particularly fast.

I am also a developer in an open-source project (https://github.com/precice) so I understand the challenges you are facing in documentation and maintenance. I've been using mpi4py a lot in my projects and I want to thank you for creating and maintaining it :pray: 

> Besides documentation, mpi4py should provide a more convenient way to specify the buffer size at runtime to tune things according to the specific needs of applications. For example, an `mpi4py.rc.irecv_bufsize` and corresponding environment variable `MPI4PY_RC_IRECV_BUFSIZE`.

I am happy to open more issues or help with documenting this in any way possible.
