### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by darrenenq** [mpi4py/mpi4py#393]
Hi, I'm on Pop!_OS 20.04 (Ubuntu) and I've installed 

sudo apt install openmpi-bin openmpi-common

but I get these errors installing mpi4py

/usr/bin/ld: cannot find -llmpe: No such file or directory
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lvt-mpi: No such file or directory
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lvt.mpi: No such file or directory
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lvt-mpi: No such file or directory
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lvt.mpi: No such file or directory
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lvt-hyb: No such file or directory
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lvt.ompi: No such file or directory
collect2: error: ld returned 1 exit status

**Comment by dalcinl** [comment]
The error lines you pasted are not the full output.

You likely need `openmpi-bin` and `libopenmpi-dev` to build mpi4py, as shown [here](https://github.com/mpi4py/setup-mpi/blob/master/setup-mpi.sh#L78).

**Comment by radiantone** [comment]
Please close
