### ISSUE TITLE
ImportError: libgfortran.so.3: cannot open shared object file

### ISSUE THREAD

**Issue by pcubillos** [mpi4py/mpi4py#396]
Hi,
I'm getting this error after trying to import the module with `from mpi4py import MPI`:
```python
ImportError: libgfortran.so.3: cannot open shared object file: No such file or directory
```

I'm working on a RHEL machine, with python 3.8.5 installed with miniconda. I'm installing mpi4py with `pip install mpi4py`.  This is the library I have on my system:
```shell
$ whereis libgfortran.so.3
libgfortran.so: /usr/lib64/libgfortran.so.5
```
I don't really know how these things work on installation. Maybe it is not finding the right library? is there a way to configure the installation to point it to libgfortran.so.5?

**Comment by dalcinl** [comment]
Do you really need to install mpi4py with pip? Isn't `conda install -c conda-forge mpi4py` enough for you? Have you read the conda-forge documentation about using an external, system-provided MPI library (if that's what are trying to do)?

The libgfortran dependency comes from the MPI library. I cannot tell exactly what's going on with so little information. You should provide exact instructions that would reproduce the problem (e.g. the full command line you used to create the miniconda environment).

**Comment by dalcinl** [comment]
@pcubillos Any update on your side? Can we close this issue?

**Comment by dalcinl** [comment]
Closing as the OP is unresponsive.
