### ISSUE TITLE
error: Cannot compile MPI programs. Check your configuration!!!

### ISSUE THREAD

**Issue by YarShev** [mpi4py/mpi4py#407]
Hi there,

when installing mpi4py from PyPI (`pip install mpi4py`) users get the error `error: Cannot compile MPI programs. Check your configuration!!!` if they do not have a working MPI implementaion installed. There is no any warning or note both on README and on mpi4py's PyPI page as to the required prerequisites. I was wondering if we could add a note/warning regarging installation of mpi4py from PyPI, which says something like `you have to have a working MPI implementation before installing mpi4py`.

**Comment by dalcinl** [comment]
> I was wondering if we could add a note/warning regarging installation of mpi4py from PyPI, 

Adding messages on failure is trivial. The hard thing is to add meaningful and succinct information, useful enough for the novices, and not annoying enough for the specialist. Pleasing novices and beginners are not my priority, and I have reasons for it (I'll not elaborate further because it is off-topic). 

> which says something like `you have to have a working MPI implementation before installing mpi4py`.

And such message may mean nothing to novices/beginners. And then some will complain in the future about the terseness of the error message, just as you are complaining now.

> Ideally, it would be great if mpi4py from PyPI is shipped with a working MPI implementation right away 

You cannot ship mpi4py with a working MPI implementation straight away, because there are multiple competing ones, and professionals/specialists (those folks I do care) will be alienated my choice. You are also completely ignoring the ABI compatibility issues, and how careful you have to be to produce a binary that can work across different Linux distributions.

> like we have the things in conda-forge. However, due to certain constraints we can't do this now I assume.

I would hope everyone using Python would understand that PyPI and conda-forge are quite different things. conda was created precisely to address issues that PyPI (as a package server for a particular programming language) cannot/should not deal with.

I've spent quite a bit of time during the last two months trying to come up with a binary wheels for mpi4py that can be installed right away and can work on a variety of OSs, processor architectures, and the two most popular MPI implementations (MPICH and Open MPI) and its derivatives (Intel MPI, MVAPICH, Microsoft MPI). 
I've made a lot of progress, wheel packages are already available, but I have not yet advertised this stuff, I don't have bandwidth for the potential flood of issues I may get from users. The key and trickiest aspects of these wheel packages is that they do not ship with an MPI implementation. Rather, after installation, mpi4py will use the MPI you have in your system. But there are tons of caveats: Linux users may need to set LD_LIBRARY_PATH, particularly if they are using a custom MPI in a cluster or supercomputer. Ubuntu broke the MPICH ABI initiative, a shared library symlink is missing, therefore running in Ubuntu requires workarounds[^1]. macOS works, but the MPI libraries have to be installed in some specific places (`/usr/local`, `/opt/homebrew` (Homebrew prefix), '/opt/local' (MacPorts prefix)).

More information here: https://github.com/mpi4py/mpi4py-publish 

[^1]: Ubuntu workaround: `sudo ln -sr /usr/lib/$(arch)-linux-gnu/libmpi{ch,}.so.12`

**Comment by dalcinl** [comment]
> > which says something like `you have to have a working MPI implementation before installing mpi4py`.
> 
> And such message may mean nothing to novices/beginners. And then some will complain in the future about the terseness of the error message, just as you are complaining now.

BTW, I'm not opposed to adding a better error message. I'm just  saying here that yours is still not good enough, IMHO.

**Comment by YarShev** [comment]
> BTW, I'm not opposed to adding a better error message. I'm just saying here that yours is still not good enough, IMHO.

What do you think about this one?

```
error: Cannot compile MPI programs. Make sure you have a working MPI implementation installed and check your configuration!!!
```

I was also saying about adding a note on the README and on mpi4py's PyPI page as to the required prerequisites. I think it would be valuable for users to have such a note.

With respect to binary wheels for mpi4py, that is a great work. I didn't realize that there are a lot of such caveats. The most frustrating thing to me is that most people using python install packages mainly from PyPI. If a package that is quite popular starts to depend on mpi4py, further installations of that package will be failing due to missing prerequisites. The simplest thing of what we could do for now is to improve documentation of packages depending on mpi4py and mpi4py's documentation itself.

**Comment by dalcinl** [comment]
> What do you think about this one?
> 
> ```
> error: Cannot compile MPI programs. Make sure you have a working MPI implementation installed and check your con
> ```

Slightly better. Perhaps a check for `Python.h` should be added as well, in case python-dev/python-devel package is missing.

> I was also saying about adding a note on the README and on mpi4py's PyPI page as to the required prerequisites. I think it would be valuable for users to have such a note.

* PyPI page literally says *Installing from source requires compilers and a working MPI implementation* in the [Install](https://pypi.org/project/mpi4py/) section.

* GitHub's README literally says an MPI implementation is a requirement in the [Dependencies](https://github.com/mpi4py/mpi4py#dependencies) section.

> With respect to binary wheels for mpi4py, that is a great work. I didn't realize that there are a lot of such caveats. The most frustrating thing to me is that most people using python install packages mainly from PyPI. If a package that is quite popular starts to depend on mpi4py, further installations of that package will be failing due to missing prerequisites. 

Well, mpi4py is close to be 20 years old by now. If you feel frustrated now, imagine how much frustration I had experienced over all these years. Developing and maintaining and open source project is an endless source of complaints. Sometimes people even write to your personal email with angry comments in a very entitled tone as if they were paying customers. And the most offending thing: 99% of the time, the complains are not about mpi4py bugs, but rather issues in the backend MPI implementation or users that completely mess up their development environments.

Look to what you just did: You opened this issue dumping a small rant together with some lecturing about how things should be done regarding binary distributions, and you also said that READMEs do not mention requisites, which is IMHO not factually true. Of course, you were very polite, and I have no hard feelings about any of your comments, but you have to grant me that that your rant about binary packages was uninformed, and again, I believe that READMEs do say what is needed to install mpi4py (although you may consider it not enough, that's open to debate). Complains will keep arriving, I'll have to keep making the same explanations over and over again, if you write the stuff down and put it somewhere people simply don't RTFM, and the only viable approach is to learn to cope with frustration. 

> The simplest thing of what we could do for now is to improve documentation of packages depending on mpi4py and mpi4py's documentation itself.

We can definitely improve the error message with Python.h and/or mpi.h are not found. Regarding READMEs in GitHub and PyPI, I don't really know what else should we add. Can you elaborate?

**Comment by leofang** [comment]
btw it's also mentioned in the documentation that a working MPI is required: 
https://mpi4py.readthedocs.io/en/stable/install.html#requirements

**Comment by dalcinl** [comment]
> btw it's also mentioned in the documentation that a working MPI is required:
> https://mpi4py.readthedocs.io/en/stable/install.html#requirements

Yes, because PyPI's description and the documentation include the `INSTALL.rst` file at the top level.

**Comment by YarShev** [comment]
> PyPI page literally says Installing from source requires compilers and a working MPI implementation in the [Install](https://pypi.org/project/mpi4py/) section.

Do you assume that source distribution and PyPI distribution are the same things? Shouldn't we keep these things separately and mention that installing from PyPI also requires compilers and a working MPI implementation?

> GitHub's README literally says an MPI implementation is a requirement in the [Dependencies](https://github.com/mpi4py/mpi4py#dependencies) section.

Doesn't it seem to you as if those dependencies may come with mpi4py when installing it? Maybe we should rename `Dependencies` to `Prerequisites`?

> Well, mpi4py is close to be 20 years old by now. If you feel frustrated now, imagine how much frustration I had experienced over all these years. Developing and maintaining and open source project is an endless source of complaints. Sometimes people even write to your personal email with angry comments in a very entitled tone as if they were paying customers. And the most offending thing: 99% of the time, the complains are not about mpi4py bugs, but rather issues in the backend MPI implementation or users that completely mess up their development environments.

I understand. I can only imagine how much you had experienced over all these years.

> Look to what you just did: You opened this issue dumping a small rant together with some lecturing about how things should be done regarding binary distributions, and you also said that READMEs do not mention requisites, which is IMHO not factually true. Of course, you were very polite, and I have no hard feelings about any of your comments, but you have to grant me that that your rant about binary packages was uninformed, and again, I believe that READMEs do say what is needed to install mpi4py (although you may consider it not enough, that's open to debate). Complains will keep arriving, I'll have to keep making the same explanations over and over again, if you write the stuff down and put it somewhere people simply don't RTFM, and the only viable approach is to learn to cope with frustration.

I am really sorry that my message looks like a rant. I don't want to be impolite. I am just saying about my concerns and concerns people may have. What we can do for now is probably just improve the error message and documentation.

**Comment by dalcinl** [comment]
> > PyPI page literally says Installing from source requires compilers and a working MPI implementation in the [Install](https://pypi.org/project/mpi4py/) section.
> 
> Do you assume that source distribution and PyPI distribution are the same things? 

Well, PyPI only hosts (so far) source distributions for mpi4py, that is, a `tar.gz` file.
The term "source distribution" is very well defined https://packaging.python.org/en/latest/specifications/source-distribution-format/

> Shouldn't we keep these things separately and mention that installing from PyPI also requires compilers and a working MPI implementation?

I'm not sure what do you mean. Keep what separated of what else? "Source distribution" literally means "the tarball uploaded to PyPI", as per the link above. And this is very close to installing from a git checkout. Users that does not know/understand that, well, sorry, they may just need to spend a bit more of time reading and learning stuff.

> I am really sorry that my message looks like a rant. I don't want to be impolite. I am just saying about my concerns and concerns people may have. What we can do for now is probably just improve the error message and documentation.

Maybe rant was too strong of a word, sorry. You where not impolite, not at all. Still, I could sense your frustration. And it does not feel good that others gets frustrated at your work. Anyways, facts trump over feelings: I have zero obligations to anyone for my open source work, therefore I ultimately should not care for what others might feel.

**Comment by YarShev** [comment]
> I'm not sure what do you mean. Keep what separated of what else? "Source distribution" literally means "the tarball uploaded to PyPI", as per the link above. And this is very close to installing from a git checkout. Users that does not know/understand that, well, sorry, they may just need to spend a bit more of time reading and learning stuff.

This probably makes sense. Those users should be aware of what PyPI itself is and what it hosts. What about renaming `Dependencies` to `Prerequisites` on README?

> Maybe rant was too strong of a word, sorry. You where not impolite, not at all. Still, I could sense your frustration. And it does not feel good that others gets frustrated at your work. Anyways, facts trump over feelings: I have zero obligations to anyone for my open source work, therefore I ultimately should not care for what others might feel.

I totally understand you but some users (I would say a lot of users) want things working out of the box. Since we can't do this right now, clear documentation of mpi4py and depending on it packages is a way to improve user experience.

**Comment by dalcinl** [comment]
Let's continue in #410.
