### ISSUE TITLE
MPIPoolExecutor doesn't read hostfile

### ISSUE THREAD

**Issue by j-emils** [mpi4py/mpi4py#411]
I'm trying to use MPIPoolExecutor together with LSF. From LSF I create a hostfile on the format:

server1 slots=n
server2 slots=m

However. When I try to add the hostfile to the MPIPoolExecutor then it seems like it simply doesn't read it. I'm using OpenMPI as the backend.

This is my test code:

```python
import os

from mpi4py.futures import MPIPoolExecutor

def func(num):
    return num**2

nums = range(48)

hostfile = os.path.join(os.getcwd(), "worker_hosts")
with open(hostfile, 'w') as fid:
    fid.write("cs1-0007 slots=24\n")
    fid.write("cs1-0008 slots=24")

mpi_info = {"add-hostfile": hostfile}

if __name__ == "__main__":
    with MPIPoolExecutor(mpi_info=mpi_info, max_workers=48) as executor:
        futures = executor.map(func, nums)
        results = [future.result() for future in futures]
```

I get this error:

\--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 48
slots that were requested by the application:

  /home/user/pythonenv/bin/python

Either request fewer slots for your application, or make more slots
available for use.

A "slot" is the Open MPI term for an allocatable unit where we can
launch a process.  The number of slots available are defined by the
environment in which Open MPI processes are run:

  1. Hostfile, via "slots=N" clauses (N defaults to number of
     processor cores if not provided)
  2. The --host command line parameter, via a ":N" suffix on the
     hostname (N defaults to 1 if not provided)
  3. Resource manager (e.g., SLURM, PBS/Torque, LSF, etc.)
  4. If none of a hostfile, the --host command line parameter, or an
     RM is present, Open MPI defaults to the number of processor cores

In all the above cases, if you want Open MPI to default to the number
of hardware threads instead of the number of processor cores, use the
--use-hwthread-cpus option.

Alternatively, you can use the --oversubscribe option to ignore the
number of available slots when deciding the number of processes to
launch.
\--------------------------------------------------------------------------
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/user/pythonenv/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/user/pythonenv/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/pythonenv/lib/python3.7/site-packages/mpi4py/futures/_lib.py", line 290, in _manager_spawn
    comm = serialized(client_spawn)(pyexe, pyargs, nprocs, info)
  File "/home/user/pythonenv/lib/python3.7/site-packages/mpi4py/futures/_lib.py", line 901, in client_spawn
    comm = MPI.COMM_SELF.Spawn(python_exe, args, max_workers, info)
  File "mpi4py/MPI/Comm.pyx", line 1931, in mpi4py.MPI.Intracomm.Spawn
mpi4py.MPI.Exception: MPI_ERR_SPAWN: could not spawn processes

**Comment by j-emils** [comment]
I'm using Open MPI 4.1.4 and mpi4py 3.1.3

**Comment by dalcinl** [comment]
Unless you have specific evidence pointing to the contrary, this is most likely an Open MPI issue, and there is nothing mpi4py can do about it. This has always been the case with every other Open MPI-related issue report I've got over the last 15 years.

I'll reiterate what I said in open-mpi/ompi#12004: MPI Spawn in Open MPI v.4 series is unreliable. Upcoming v5.0.0 will improve things, but I have not tested it myself in production. I can only point you to the obvious: ask Open MPI folks.

PS: I have your same Open MPI version installed from Fedora 38 repos.  Your code is simply not working, the execution hangs. After switching to MPICH (and fixing the info key as appropriate ), things work flawlessly. 
Minor nit: I had to hotfix your reproducer as `results = list(executor.map(func, nums))`

**Comment by j-emils** [comment]
I changed to MPICH and as you said it works without issues. The only difference is that I can't execute my python code directly but must run it using a terminal and then callling mpiexec -n 1 myscript.py. I know that this method is stated in the docs as the recommended method. However, in my case I'm trying to build the functionality into a python module. Howvever, with all that said, thank you this module and especially the futures functionality. It has been very helpful.

**Comment by dalcinl** [comment]
> The only difference is that I can't execute my python code directly but ...

What MPICH version are you running? Since version v4.1.0, you should not need `mpiexec`. Although that version is pretty recent and has not hit Linux distributions just yet, it is already available in `conda-forge`.

Additionally, take a look here: http://github.com/mpi4py/mpi4py-publish
If you follow the note about using Intel MPI installed with `pip` in a virtual environment, you should get it working straight away. The only minor caveat is that the `/<venv-directory>/bin` directory has to be in your `$PATH` (e.g. by running `source /<venv-directory>/bin/activate` to activate the environment) such that the `mpiexec` command can be found, but otherwise you do not have to explicitly launch `python` with `mpiexec`. Installations performed with `pip install --user ...` should work, too, as long as the local user directory `~/.local/bin` is in your $PATH.

DISCLAIMER: All this stuff is still in-development work and has not been tested thoroughly. Nonetheless, it may make your software infrastructure much easier to deploy in production.

**Comment by j-emils** [comment]
HYDRA build details:
    Version:                                 4.0.3
    Release Date:                            Tue Nov  8 09:51:06 CST 2022

I'm running this version, which then matches what you're saying since this is an older version. I will try to use a later version and see if it works.
