### ISSUE TITLE
Failed to install with gcc-10.2.0 and openmpi-4.1.0

### ISSUE THREAD

**Issue by seraphzl** [mpi4py/mpi4py#42]
Hi,

I tried to install mpi4py using the command: pip install mpi4py, and failed with errors as:

Processing ./mpi4py-3.0.3.tar.gz
Installing collected packages: mpi4py
  Running setup.py install for mpi4py ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-ysbgioyo-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-rrwi0q_a-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_src
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/mpi4py
    copying src/mpi4py/__init__.py -> build/lib.linux-x86_64-3.6/mpi4py
    copying src/mpi4py/bench.py -> build/lib.linux-x86_64-3.6/mpi4py
    copying src/mpi4py/__main__.py -> build/lib.linux-x86_64-3.6/mpi4py
    copying src/mpi4py/run.py -> build/lib.linux-x86_64-3.6/mpi4py
    creating build/lib.linux-x86_64-3.6/mpi4py/futures
    copying src/mpi4py/futures/aplus.py -> build/lib.linux-x86_64-3.6/mpi4py/futures
    copying src/mpi4py/futures/__init__.py -> build/lib.linux-x86_64-3.6/mpi4py/futures
    copying src/mpi4py/futures/_lib.py -> build/lib.linux-x86_64-3.6/mpi4py/futures
    copying src/mpi4py/futures/pool.py -> build/lib.linux-x86_64-3.6/mpi4py/futures
    copying src/mpi4py/futures/server.py -> build/lib.linux-x86_64-3.6/mpi4py/futures
    copying src/mpi4py/futures/_base.py -> build/lib.linux-x86_64-3.6/mpi4py/futures
    copying src/mpi4py/futures/__main__.py -> build/lib.linux-x86_64-3.6/mpi4py/futures
    copying src/mpi4py/libmpi.pxd -> build/lib.linux-x86_64-3.6/mpi4py
    copying src/mpi4py/__init__.pxd -> build/lib.linux-x86_64-3.6/mpi4py
    copying src/mpi4py/MPI.pxd -> build/lib.linux-x86_64-3.6/mpi4py
    creating build/lib.linux-x86_64-3.6/mpi4py/include
    creating build/lib.linux-x86_64-3.6/mpi4py/include/mpi4py
    copying src/mpi4py/include/mpi4py/mpi4py.h -> build/lib.linux-x86_64-3.6/mpi4py/include/mpi4py
    copying src/mpi4py/include/mpi4py/mpi4py.MPI.h -> build/lib.linux-x86_64-3.6/mpi4py/include/mpi4py
    copying src/mpi4py/include/mpi4py/mpi4py.MPI_api.h -> build/lib.linux-x86_64-3.6/mpi4py/include/mpi4py
    copying src/mpi4py/include/mpi4py/mpi4py.i -> build/lib.linux-x86_64-3.6/mpi4py/include/mpi4py
    copying src/mpi4py/include/mpi4py/mpi.pxi -> build/lib.linux-x86_64-3.6/mpi4py/include/mpi4py
    running build_clib
    MPI configuration: [mpi] from 'mpi.cfg'
    MPI C compiler:    /opt/openmpi-4.1.0-gcc1020/bin/mpicc
    MPI C++ compiler:  /opt/openmpi-4.1.0-gcc1020/bin/mpicxx
    MPI F compiler:    /opt/openmpi-4.1.0-gcc1020/bin/mpifort
    MPI F90 compiler:  /opt/openmpi-4.1.0-gcc1020/bin/mpif90
    MPI F77 compiler:  /opt/openmpi-4.1.0-gcc1020/bin/mpif77
    checking for library 'lmpe' ...
    /opt/openmpi-4.1.0-gcc1020/bin/mpicc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -c _configtest.c -o _configtest.o
    cc1: fatal error: inaccessible plugin file /opt/gcc-10.2.0/lib/gcc/x86_64-pc-linux-gnu/10.2.0/plugin/annobin.so expanded from short plugin name annobin: No such file or directory
    compilation terminated.
    failure.
    removing: _configtest.c _configtest.o
    building 'mpe' dylib library
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    creating build/temp.linux-x86_64-3.6/src/lib-pmpi
    /opt/openmpi-4.1.0-gcc1020/bin/mpicc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -c src/lib-pmpi/mpe.c -o build/temp.linux-x86_64-3.6/src/lib-pmpi/mpe.o
    cc1: fatal error: inaccessible plugin file /opt/gcc-10.2.0/lib/gcc/x86_64-pc-linux-gnu/10.2.0/plugin/annobin.so expanded from short plugin name annobin: No such file or directory
    compilation terminated.
    warning: build_clib: command '/opt/openmpi-4.1.0-gcc1020/bin/mpicc' failed with exit status 1
    
    warning: build_clib: building optional library "mpe" failed
    
    checking for library 'vt-mpi' ...
    /opt/openmpi-4.1.0-gcc1020/bin/mpicc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -c _configtest.c -o _configtest.o
    cc1: fatal error: inaccessible plugin file /opt/gcc-10.2.0/lib/gcc/x86_64-pc-linux-gnu/10.2.0/plugin/annobin.so expanded from short plugin name annobin: No such file or directory
    compilation terminated.
    failure.
    removing: _configtest.c _configtest.o
    checking for library 'vt.mpi' ...
    /opt/openmpi-4.1.0-gcc1020/bin/mpicc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -c _configtest.c -o _configtest.o
    cc1: fatal error: inaccessible plugin file /opt/gcc-10.2.0/lib/gcc/x86_64-pc-linux-gnu/10.2.0/plugin/annobin.so expanded from short plugin name annobin: No such file or directory
    compilation terminated.
    failure.
    removing: _configtest.c _configtest.o
    building 'vt' dylib library
    /opt/openmpi-4.1.0-gcc1020/bin/mpicc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -c src/lib-pmpi/vt.c -o build/temp.linux-x86_64-3.6/src/lib-pmpi/vt.o
    cc1: fatal error: inaccessible plugin file /opt/gcc-10.2.0/lib/gcc/x86_64-pc-linux-gnu/10.2.0/plugin/annobin.so expanded from short plugin name annobin: No such file or directory
    compilation terminated.
    warning: build_clib: command '/opt/openmpi-4.1.0-gcc1020/bin/mpicc' failed with exit status 1
    
    warning: build_clib: building optional library "vt" failed
    
    checking for library 'vt-mpi' ...
    /opt/openmpi-4.1.0-gcc1020/bin/mpicc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -c _configtest.c -o _configtest.o
    cc1: fatal error: inaccessible plugin file /opt/gcc-10.2.0/lib/gcc/x86_64-pc-linux-gnu/10.2.0/plugin/annobin.so expanded from short plugin name annobin: No such file or directory
    compilation terminated.
    failure.
    removing: _configtest.c _configtest.o
    checking for library 'vt.mpi' ...
    /opt/openmpi-4.1.0-gcc1020/bin/mpicc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -c _configtest.c -o _configtest.o
    cc1: fatal error: inaccessible plugin file /opt/gcc-10.2.0/lib/gcc/x86_64-pc-linux-gnu/10.2.0/plugin/annobin.so expanded from short plugin name annobin: No such file or directory
    compilation terminated.
    failure.
    removing: _configtest.c _configtest.o
    building 'vt-mpi' dylib library
    /opt/openmpi-4.1.0-gcc1020/bin/mpicc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -c src/lib-pmpi/vt-mpi.c -o build/temp.linux-x86_64-3.6/src/lib-pmpi/vt-mpi.o
    cc1: fatal error: inaccessible plugin file /opt/gcc-10.2.0/lib/gcc/x86_64-pc-linux-gnu/10.2.0/plugin/annobin.so expanded from short plugin name annobin: No such file or directory
    compilation terminated.
    warning: build_clib: command '/opt/openmpi-4.1.0-gcc1020/bin/mpicc' failed with exit status 1
    
    warning: build_clib: building optional library "vt-mpi" failed
    
    checking for library 'vt-hyb' ...
    /opt/openmpi-4.1.0-gcc1020/bin/mpicc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -c _configtest.c -o _configtest.o
    cc1: fatal error: inaccessible plugin file /opt/gcc-10.2.0/lib/gcc/x86_64-pc-linux-gnu/10.2.0/plugin/annobin.so expanded from short plugin name annobin: No such file or directory
    compilation terminated.
    failure.
    removing: _configtest.c _configtest.o
    checking for library 'vt.ompi' ...
    /opt/openmpi-4.1.0-gcc1020/bin/mpicc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -c _configtest.c -o _configtest.o
    cc1: fatal error: inaccessible plugin file /opt/gcc-10.2.0/lib/gcc/x86_64-pc-linux-gnu/10.2.0/plugin/annobin.so expanded from short plugin name annobin: No such file or directory
    compilation terminated.
    failure.
    removing: _configtest.c _configtest.o
    building 'vt-hyb' dylib library
    /opt/openmpi-4.1.0-gcc1020/bin/mpicc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -c src/lib-pmpi/vt-hyb.c -o build/temp.linux-x86_64-3.6/src/lib-pmpi/vt-hyb.o
    cc1: fatal error: inaccessible plugin file /opt/gcc-10.2.0/lib/gcc/x86_64-pc-linux-gnu/10.2.0/plugin/annobin.so expanded from short plugin name annobin: No such file or directory
    compilation terminated.
    warning: build_clib: command '/opt/openmpi-4.1.0-gcc1020/bin/mpicc' failed with exit status 1
    
    warning: build_clib: building optional library "vt-hyb" failed
    
    running build_ext
    MPI configuration: [mpi] from 'mpi.cfg'
    MPI C compiler:    /opt/openmpi-4.1.0-gcc1020/bin/mpicc
    MPI C++ compiler:  /opt/openmpi-4.1.0-gcc1020/bin/mpicxx
    MPI F compiler:    /opt/openmpi-4.1.0-gcc1020/bin/mpifort
    MPI F90 compiler:  /opt/openmpi-4.1.0-gcc1020/bin/mpif90
    MPI F77 compiler:  /opt/openmpi-4.1.0-gcc1020/bin/mpif77
    checking for dlopen() availability ...
    checking for header 'dlfcn.h' ...
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c _configtest.c -o _configtest.o
    cc1: fatal error: inaccessible plugin file /opt/gcc-10.2.0/lib/gcc/x86_64-pc-linux-gnu/10.2.0/plugin/annobin.so expanded from short plugin name annobin: No such file or directory
    compilation terminated.
    failure.
    removing: _configtest.c _configtest.o
    failure.
    checking for library 'dl' ...
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c _configtest.c -o _configtest.o
    cc1: fatal error: inaccessible plugin file /opt/gcc-10.2.0/lib/gcc/x86_64-pc-linux-gnu/10.2.0/plugin/annobin.so expanded from short plugin name annobin: No such file or directory
    compilation terminated.
    failure.
    removing: _configtest.c _configtest.o
    checking for function 'dlopen' ...
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c _configtest.c -o _configtest.o
    cc1: fatal error: inaccessible plugin file /opt/gcc-10.2.0/lib/gcc/x86_64-pc-linux-gnu/10.2.0/plugin/annobin.so expanded from short plugin name annobin: No such file or directory
    compilation terminated.
    failure.
    removing: _configtest.c _configtest.o
    building 'mpi4py.dl' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c src/dynload.c -o build/temp.linux-x86_64-3.6/src/dynload.o
    cc1: fatal error: inaccessible plugin file /opt/gcc-10.2.0/lib/gcc/x86_64-pc-linux-gnu/10.2.0/plugin/annobin.so expanded from short plugin name annobin: No such file or directory
    compilation terminated.
    warning: build_ext: command 'gcc' failed with exit status 1
    
    warning: build_ext: building optional extension "mpi4py.dl" failed
    
    checking for MPI compile and link ...
    /opt/openmpi-4.1.0-gcc1020/bin/mpicc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c _configtest.c -o _configtest.o
    cc1: fatal error: inaccessible plugin file /opt/gcc-10.2.0/lib/gcc/x86_64-pc-linux-gnu/10.2.0/plugin/annobin.so expanded from short plugin name annobin: No such file or directory
    compilation terminated.
    failure.
    removing: _configtest.c _configtest.o
    error: Cannot compile MPI programs. Check your configuration!!!
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-ysbgioyo-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-rrwi0q_a-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-ysbgioyo-build/

How to solve this issue? Thanks in advance.

**Comment by dalcinl** [comment]
This is hardly mpi4py's fault. 

1) Looks like you are using a custom GCC build installed in `/opt`
2) But you are probably using system Python, and distutils is passing -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1. This flags most likely asks GCC to load a plugin
3) And then your GCC build does not have the plugin /opt/gcc-10.2.0/lib/gcc/x86_64-pc-linux-gnu/10.2.0/plugin/annobin.so

**Comment by dalcinl** [comment]
Try the following:
```shell
export CFLAGS=-fno-use-annobin
python -m pip install mpi4py
```

**Comment by seraphzl** [comment]
> Try the following:
> 
> ```shell
> export CFLAGS=-fno-use-annobin
> python -m pip install mpi4py
> ```

@dalcinl Using this CFLAGS did not help.
```shell
gcc -pthread -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fno-use-annobin -fPIC -c _configtest.c -o _configtest.o
    cc1: error: unrecognized command-line option ‘-fno-use-annobin’
```

I will try to compile the annobin plugin with custom-built gcc-10.2.0.

**Comment by dalcinl** [comment]
> I will try to compile the annobin plugin with custom-built gcc-10.2.0.

I believe it is the best course of action for you. You will have the same problems with other Python packages.

PS: There is another way, it involves copying `_sysconfigdata_*_linux_x86_64-linux-gnu.py` with some other name, let say, `mysysconfigdata.py`, then edit it to remove any offending compiler/linker flags (the `-spec` flags that run annobin on), then place the file in a directory location than you have to add to `PYTHONPATH`, and finally  `export _PYTHON_SYSCONFIGDATA_NAME=mysysconfigdata`. If you are a sysadmin and have some experience with the distutils mess, you may want to learn these tricks.
