### ISSUE TITLE
Questions/Suggestions about Fujitsu MPI

### ISSUE THREAD

**Issue by nariba-fj** [mpi4py/mpi4py#43]
@dalcinl 
I created this issue because I heard that there are some questions/suggestions about Fujitsu MPI.

**Comment by dalcinl** [comment]
Hi, @nariba-fj, thanks for contacting us.

My primary question is the following: Is there any way to distinguish Fujitsu MPI (and its version?) at **compile time** such that I could extend the following code:

https://github.com/mpi4py/mpi4py/blob/master/src/pympivendor.h

Ideally, I'm looking for macros like the following (just an example)
```c
#define FUJITSU_MPI_MAJOR_VERSION 1
#define FUJITSU_MPI_MINOR_VERSION 2
```
to be available after `#include <mpi.h>`.

The purpose of this question/request is twofold. 

1. First, mpi4py can easily implement our `mpi4py.MPI.get_vendor()` function, which so far relies on compile-time macros and not `MPI_Get_library_version()`.
2. Second, and much more important, advertising yourself with macros allow ANY third-party code to perform conditional compilation based on whether your MPI implementation is being used or not. This is very convenient for end users, this way you can avoid configure steps to detect your library, writing your logics right there in code with `#ifdef ...`.

**Comment by nariba-fj** [comment]
@dalcinl 
Sorry, Fujitsu MPI does not have macros that can identify the version.
It may be added in the future.

The latest Fujitsu MPI is based on Open MPI 4.0.1, which defines the following confusing macros.

```
OPEN_MPI
OMPI_MAJOR_VERSION
OMPI_MINOR_VERSION
OMPI_RELEASE_VERSION
```

I haven't actually tried it, but I think mpi4py will recognize Fujitsu MPI as Open MPI.

**Comment by dalcinl** [comment]
> I haven't actually tried it, but I think mpi4py will recognize Fujitsu MPI as Open MPI.

Yes, that's the case, indeed. mpi4py detects Fujitsu MPI as Open MPI. But that's not accurate, because it is not the "stock" Open MPI, and then it is not easy/obvious how to detect Fujitsu MPI at compile time. And that's why I'm requesting to Fujitsu MPI to somehow handle this better in the future by adding some macros that identify its name, and if possible, its version.

**Comment by nariba-fj** [comment]
Thanks for your advice.
We will consider implementing the macros.
However, it may take at least a couple of months, even if we can release the macros.

**Comment by dalcinl** [comment]
Thanks! No hurries, once you have news, please come back to me.

**Comment by dalcinl** [comment]
@nariba-fj Any update? Has Fujitsu implemented any new macros in `mpi.h`?

**Comment by nariba-fj** [comment]
@dalcinl Sorry for the long delay in updating.
Actually, I have already left the Fujitsu MPI development team and do not know what the original plan is now.
I have asked the Fujitsu MPI development team to let you know the current status.

**Comment by dalcinl** [comment]
@ggouaillardet Do you know anyone at Fujitsu that could come back to me about this issue?

**Comment by ggouaillardet** [comment]
I will try to contact some folks.

meanwhile, here are a few ideas to identify Fujitsu MPI:

`MPI_Get_library_version()` returns `FUJITSU MPI Library 4.0.0 (4.0.1fj4.0.0)`

```
$ mpiexec --version
mpiexec (Open MPI)
FUJITSU MPI Library 4.0.1 25880c2816
```

from `mpi-ext.h`, the following macros are defined
```
#define OMPI_HAVE_MPI_EXT_FJCOLLECTION 1
#define OMPI_HAVE_MPI_EXT_FJMSWK 1
#define OMPI_HAVE_MPI_EXT_FJPREQUEST 1
#define OMPI_HAVE_MPI_EXT_FJPROGRESS 1
#define OMPI_HAVE_MPI_EXT_FJRUNTIME 1
#define OMPI_HAVE_MPI_EXT_FJTOPOLOGY 1
```

`libmpi.so` contains the following symbols

```
FJMPI_Collection_clear
FJMPI_Collection_print
FJMPI_Collection_start
FJMPI_Collection_stop
FJMPI_Mswk_accept
FJMPI_Mswk_connect
FJMPI_Mswk_disconnect
FJMPI_Prequest_cid
FJMPI_Prequest_ctlcomm_recvpend_t_class
FJMPI_Prequest_finalize
FJMPI_Prequest_initialize
FJMPI_Prequest_initialized
FJMPI_Prequest_max_rdma_size
FJMPI_Prequest_nosync
FJMPI_Prequest_output_id
FJMPI_Prequest_recv_init
FJMPI_Prequest_req_t_class
FJMPI_Prequest_request_num
FJMPI_Prequest_send_init
FJMPI_Prequest_srreqs_list_t_class
FJMPI_Prequest_start
FJMPI_Prequest_startall
FJMPI_Prequest_tofu_is_not_initialized
FJMPI_Progress_start
FJMPI_Progress_stop
FJMPI_Runtime_finalize
FJMPI_Runtime_finalized
FJMPI_Runtime_init
FJMPI_Runtime_initialized
FJMPI_Runtime_progress
FJMPI_Topology_cart_reorder
FJMPI_Topology_get_coords
FJMPI_Topology_get_dimension
FJMPI_Topology_get_ranks
FJMPI_Topology_get_shape
```
