### ISSUE TITLE
Is `scatter` properly typed?

### ISSUE THREAD

**Issue by MaximilienLC** [mpi4py/mpi4py#434]
https://mpi4py.readthedocs.io/en/stable/tutorial.html indicates that `scatter` should allow `sendobj=None` however the definition is `def scatter(self, sendobj: Sequence[Any], root: int = 0) -> Any: ...`

**Comment by dalcinl** [comment]
You are definitely right. However, this has already been fixed in the master branch, see [latest](https://mpi4py.readthedocs.io/en/latest/reference/mpi4py.MPI.Comm.html#mpi4py.MPI.Comm.scatter) docs.
