### ISSUE TITLE
Update C API for Python 3.13

### ISSUE THREAD

**Issue by limburgher** [mpi4py/mpi4py#437]
src/mpi4py.MPI.c: In function ‘__pyx_f_6mpi4py_3MPI_pickle_dumpv’:
src/mpi4py.MPI.c:59975:15: error: implicit declaration of function ‘_PyBytes_Join’ [-Werror=implicit-function-declaration]
59975 |   __pyx_t_4 = _PyBytes_Join(__pyx_kp_b__12, __pyx_v_items); if (unlikely(!__pyx_t_4)) __PYX_ERR(8, 168, __pyx_L1_error)

https://bugzilla.redhat.com/show_bug.cgi?id=2250677

**Comment by dalcinl** [comment]
Could you please update the RPM spec file to apply this [patch](https://github.com/mpi4py/mpi4py/commit/978310e1f9b84d0df94bd309878a96707a176e78.patch)
You will also need to add Cython to build-requires and run `python conf/cythonize.py` to regenerate C sources. Cython 3 should work (although it has not been tested), you should ignore the warnings about deprecated syntax.

**Comment by limburgher** [comment]
Works perfectly, thank you!

**Comment by dalcinl** [comment]
Fixed via 978310e1f9b84d0df94bd309878a96707a176e78.
