### ISSUE TITLE
Install error on ubuntu , and how to install pyproject.toml-based projects?

### ISSUE THREAD

**Issue by vision1v1** [mpi4py/mpi4py#448]
`checking for MPI compile and link ...
      gcc -pthread -B /root/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/miniconda3/include/python3.8 -c _configtest.c -o _configtest.o
      _configtest.c:2:10: fatal error: mpi.h: No such file or directory
          2 | #include <mpi.h>
            |          ^~~~~~~
      compilation terminated.
      failure.
      removing: _configtest.c _configtest.o
      error: Cannot compile MPI programs. Check your configuration!!!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mpi4py
Failed to build mpi4py
ERROR: Could not build wheels for mpi4py, which is required to install pyproject.toml-based projects`

This error message means to install pyproject.toml-based projects. But I didn't find out how to install pyproject.toml-based

**Comment by dalcinl** [comment]
Looks like you are trying to install within a conda environment. Do you really need to install mpi4py from sources? Unless you need features from the in-development version, you can conda install mpi4py as per the following instructions:
https://mpi4py.readthedocs.io/en/latest/install.html#using-conda

**Comment by vision1v1** [comment]
thank you , the way of "pip install .. " is wrong in my enviroments, but conda install can work.
