### ISSUE TITLE
WSL2(Ubuntu) - ImportError: cannot import name 'MPI' from 'mpi4py' - installed with: apt install python3-mpi4py

### ISSUE THREAD

**Issue by patchie** [mpi4py/mpi4py#449]
I am using WSL2(Ubuntu).

I installed mpi4py by using the following command(since the pip install gave me a wheel error): `apt install python3-mpi4py`

I get the error message: 

> ImportError: cannot import name 'MPI' from 'mpi4py'

Any ideas what i did wrong? Or is this a bug?
 Tried lots of stuff i found online, but most answers was related to Conda, which i am not using.

**Full traceback below:**

> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> Cell In[1], line 92
>      86 # Initialize Trainer
>      87 trainer = Trainer(
>      88     model=model,
>      89     args=training_args,
>      90     train_dataset=tokenized_datasets
>      91 )
> ---> 92 trainer.train()
>      95 save_dir = "./model_save_directory"
>      96 model.save_pretrained(save_dir)
> 
> File /usr/local/lib/python3.11/dist-packages/transformers/trainer.py:1537, in Trainer.train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
>    1535         hf_hub_utils.enable_progress_bars()
>    1536 else:
> -> 1537     return inner_training_loop(
>    1538         args=args,
>    1539         resume_from_checkpoint=resume_from_checkpoint,
>    1540         trial=trial,
>    1541         ignore_keys_for_eval=ignore_keys_for_eval,
>    1542     )
> 
> File /usr/local/lib/python3.11/dist-packages/transformers/trainer.py:1675, in Trainer._inner_training_loop(self, batch_size, args, resume_from_checkpoint, trial, ignore_keys_for_eval)
>    1672             model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
>    1673     else:
>    1674         # to handle cases wherein we pass "DummyScheduler" such as when it is specified in DeepSpeed config.
> -> 1675         model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
>    1676             self.model, self.optimizer, self.lr_scheduler
>    1677         )
>    1679 if self.is_fsdp_enabled:
>    1680     self.model = self.model_wrapped = model
> 
> File ~/.local/lib/python3.11/site-packages/accelerate/accelerator.py:1209, in Accelerator.prepare(self, device_placement, *args)
>    1207         args = self._prepare_ipex(*args)
>    1208 if self.distributed_type == DistributedType.DEEPSPEED:
> -> 1209     result = self._prepare_deepspeed(*args)
>    1210 elif self.distributed_type == DistributedType.MEGATRON_LM:
>    1211     result = self._prepare_megatron_lm(*args)
> 
> File ~/.local/lib/python3.11/site-packages/accelerate/accelerator.py:1582, in Accelerator._prepare_deepspeed(self, *args)
>    1576             if (
>    1577                 isinstance(scheduler, LRScheduler)
>    1578                 or type(scheduler).__name__ in deepspeed.runtime.lr_schedules.VALID_LR_SCHEDULES
>    1579             ):
>    1580                 kwargs["lr_scheduler"] = scheduler
> -> 1582 engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
>    1583 if optimizer is not None:
>    1584     optimizer = DeepSpeedOptimizerWrapper(optimizer)
> 
> File ~/.local/lib/python3.11/site-packages/deepspeed/__init__.py:135, in initialize(args, model, optimizer, model_parameters, training_data, lr_scheduler, mpu, dist_init_required, collate_fn, config, config_params)
>     133 from deepspeed import comm as dist
>     134 dist_backend = get_accelerator().communication_backend_name()
> --> 135 dist.init_distributed(dist_backend=dist_backend, dist_init_required=dist_init_required)
>     137 # Set config using config_params for backwards compat
>     138 if config is None and config_params is not None:
> 
> File ~/.local/lib/python3.11/site-packages/deepspeed/comm/comm.py:658, in init_distributed(dist_backend, auto_mpi_discovery, distributed_port, verbose, timeout, init_method, dist_init_required, config, rank, world_size)
>     656         patch_aws_sm_env_for_torch_nccl_backend(verbose=verbose)
>     657     else:
> --> 658         mpi_discovery(distributed_port=distributed_port, verbose=verbose)
>     660 if cdb is not None and cdb.is_initialized():
>     661     if int(os.getenv('RANK', '0')) == 0:
> 
> File ~/.local/lib/python3.11/site-packages/deepspeed/comm/comm.py:677, in mpi_discovery(distributed_port, verbose)
>     673 def mpi_discovery(distributed_port=TORCH_DISTRIBUTED_DEFAULT_PORT, verbose=True):
>     674     '''
>     675     Discovery MPI environment via mpi4py and map to relevant dist state
>     676     '''
> --> 677     from mpi4py import MPI
>     678     import subprocess
>     679     comm = MPI.COMM_WORLD
> 
> ImportError: cannot import name 'MPI' from 'mpi4py' (/usr/lib/python3/dist-packages/mpi4py/__init__.py)

**Comment by dalcinl** [comment]
I'm not a WSL user. What you did is supposed to work out of the box with native Ubuntu.
What's the output of `ls -alt /usr/lib/python3/dist-packages/mpi4py`?

**Comment by patchie** [comment]
> I'm not a WSL user. What you did is supposed to work out of the box with native Ubuntu. What's the output of `ls -alt /usr/lib/python3/dist-packages/mpi4py`?

This is the output:

```
root@******:/etc/apt/apt.conf.d# ls -alt /usr/lib/python3/dist-packages/mpi4py
total 1612
drwxr-xr-x  7 root root    4096 Jan  4 22:02 .
drwxr-xr-x  2 root root    4096 Jan  4 15:12 __pycache__
drwxr-xr-x  3 root root    4096 Jan  4 15:12 futures
drwxr-xr-x  3 root root    4096 Jan  4 15:12 util
drwxr-xr-x 70 root root    4096 Jan  4 15:12 ..
drwxr-xr-x  2 root root    4096 Jan  4 15:12 lib-pmpi
drwxr-xr-x  3 root root    4096 Jan  4 15:12 include
-rw-r--r--  1 root root 1440424 Mar 16  2022 MPI.cpython-310-x86_64-linux-gnu.so
-rw-r--r--  1 root root   14848 Mar 16  2022 dl.cpython-310-x86_64-linux-gnu.so
-rw-r--r--  1 root root      55 Mar 16  2022 mpi.cfg
-rw-r--r--  1 root root    3964 Nov 25  2021 MPI.pxd
-rw-r--r--  1 root root   51995 Nov 25  2021 MPI.pyi
-rw-r--r--  1 root root      56 Nov 25  2021 __init__.pxd
-rw-r--r--  1 root root    5279 Nov 25  2021 __init__.py
-rw-r--r--  1 root root     793 Nov 25  2021 __init__.pyi
-rw-r--r--  1 root root     165 Nov 25  2021 __main__.py
-rw-r--r--  1 root root      22 Nov 25  2021 __main__.pyi
-rw-r--r--  1 root root    6316 Nov 25  2021 bench.py
-rw-r--r--  1 root root     351 Nov 25  2021 bench.pyi
-rw-r--r--  1 root root     774 Nov 25  2021 dl.pyi
-rw-r--r--  1 root root   44966 Nov 25  2021 libmpi.pxd
-rw-r--r--  1 root root      27 Nov 25  2021 py.typed
-rw-r--r--  1 root root    7689 Nov 25  2021 run.py
-rw-r--r--  1 root root     205 Nov 25  2021 run.pyi
root@*******:/etc/apt/apt.conf.d#
```

**Comment by dalcinl** [comment]
Now I see the problem. The mpi4py you are using is installed in `/usr/lib/python3/dist-packages/` and corresponds to a Python 3.10 version. However, from the output you sent, looks like you are using Python 3.11. I think you have managed to somehow mixup mpi4py installed with apt with some Python 3.11 you have installed around. You are probably setting the `PYTHONPATH` environment variable (or somehow manipulating Python's `sys.path`) to include `/usr/lib/python3/dist-packages/`. That's not right, your system Python installed in `/usr` seems to be Python 3.10, but you seem to be using Python 3.11 installed in `/usr/local`.

Unfortunately, you issue report has been incomplete. You did not mention you where using Python 3.11 or how did you installed it. You said that `pip install mpi4py` gave you errors, but you did not elaborate on the details. My recommendation is that you uninstall everything and cleanup your system of everything you may have installed manually, then you start fresh. Always submit proper issue report with information about how you installed the stuff you are using, otherwise it is impossible to even guess what's going on on messed up systems.
