### ISSUE TITLE
mpi4py error during getting results (in pare with SLURM)

### ISSUE THREAD

**Issue by byquip** [mpi4py/mpi4py#45]
ERROR:
Traceback (most recent call last):
  File "/opt/software/anaconda/3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/software/anaconda/3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vasko/.local/lib/python3.6/site-packages/mpi4py/futures/__main__.py", line 72, in <module>
    main()
  File "/home/vasko/.local/lib/python3.6/site-packages/mpi4py/futures/__main__.py", line 60, in main
    run_command_line()
  File "/home/vasko/.local/lib/python3.6/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/opt/software/anaconda/3/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/opt/software/anaconda/3/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/opt/software/anaconda/3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "cali_send_2.py", line 137, in <module>
    globals()[sys.argv[1]](sys.argv[2], sys.argv[3])
File "cali_send_2.py", line 94, in solve_on_cali
    sols = list(executor.map(solve_matrix, repeat(inputs), range(len(wls)), wls))
  File "/home/vasko/.local/lib/python3.6/site-packages/mpi4py/futures/pool.py", line 207, in result_iterator
    yield futures.pop().result()
  File "/opt/software/anaconda/3/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/opt/software/anaconda/3/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 5: invalid start byte

ENV 
CentOS release 6.5 (Final)
Python 3.6 anaconda
mpiexec (OpenRTE) 1.8.2
mpi4py 3.0.3

Piece of Code:

```
inputs = [der_mats, ref_ind_yee_grid, n_xy_sq, param_sweep_on, i_m, inv_eps, sol_params]
with MPIPoolExecutor(max_workers=int(nodes)) as executor:
   sols = list(executor.map(solve_matrix, repeat(inputs), range(len(wls)), wls))
   executor.shutdown(wait=True)  # wait for all complete
   zipobj = ZipFile(zp_fl_nm, 'w')

   for sol in sols:
      w, v, solnum, vq = sol
      print(w[0], solnum) # this line will shows if data have duplicates.
      w.tofile(f"w_sol_{solnum}.npy")
      v.tofile(f"v_sol_{solnum}.npy")
      vq.tofile(f"vq_sol_{solnum}.npy")
      zipobj.write(f"w_sol_{solnum}.npy")
      zipobj.write(f"v_sol_{solnum}.npy")
      zipobj.write(f"vq_sol_{solnum}.npy")
      os.remove(f"w_sol_{solnum}.npy")
      os.remove(f"v_sol_{solnum}.npy")
      os.remove(f"vq_sol_{solnum}.npy")
```
Call of method I do with sending command like this:
`f'srun --mpi=pmi2 -n ${{SLURM_NTASKS}} python -m mpi4py.futures cali_send_2.py solve_on_cali \"\"{name}\"\" {num_nodes}'`

Sometimes this error not appear if I use another range for `wls` with (`wls = np.arange(0.4e-6, 1.8e-6, 0.01e-6)`) it crush with this error or return duplicates of some solutions if step 0.1e-6.
If I use this range (`wls = np.arange(0.55e-6, 1.55e-6, 0.01e-6)`) with any step 0.1e-6 or 0.001e-6 it's NOT crush with mentioned error and returns good results without duplicates.

Could someone please explain me what is the origin of this error?
My suspicion is pointing on float numbers like 1.699999999999999999999e-6

**Comment by leofang** [comment]
Any chance you forgot to activate the same Python environment across all compute nodes?

**Comment by dalcinl** [comment]
This kind of questions is better suited for mpi4py's mailing list in Google Groups. I understand that shooting an issue in GitHub is very convenient for users, but this increases the load on core developers, and the community watching the mailing list is usually larger. Chaces of getting a good tip and advice are higher on the mailing list.

**Comment by byquip** [comment]
> 
> 
> Any chance you forgot to activate the same Python environment across all compute nodes?

Could be, I'm new in HPC. 
I just will show which submission sbatch script is generated (this is suppose to be one line):

cd scratch/def_sol_name;
module purge;
module load mpi/openmpi;
module load python/3.6-anaconda3;
chmod u+x cali_send_2.py;
sbatch 
--job-name=VASKO_FD_SOLVER_def_sol_name 
--nodes=6 
--ntasks=6 
--ntasks-per-node=1 
--cpus-per-task=16 
--time=48:00:00 
--partition=normal 
--qos=normal 
--mail-type=END 
--mail-user=email :)
--output=def_sol_name_out.log 
--wrap='echo "SLURM_PARTITION:         "$SLURM_JOB_PARTITION&&
echo "SLURM_NNODES:            "$SLURM_NNODES&&
echo "SLURM_CPUS_ON_NODE:      "$SLURM_CPUS_ON_NODE&&
echo "SLURM_JOB_CPUS_PER_NODE: "$SLURM_JOB_CPUS_PER_NODE&&
echo "SLURM_JOB_NUM_NODES:     "$SLURM_JOB_NUM_NODES&&
echo "SLURM_NTASKS:            "$SLURM_NTASKS&&
echo "SLURM_JOB_NODELIST:      "$SLURM_JOB_NODELIST&&
srun --mpi=pmi2 -n ${SLURM_NTASKS} python -m mpi4py.futures cali_send_2.py solve_on_cali ""def_sol_name"" 6' 

> 
> 
> @byquip You are using Python from a miniconda environment, however mpi4py is installed in `$HOME/.local`. That's suspicious, conda users should just `pip install` in the environment. Or perhaps the problem is what @leofang pointed out, the environment is not active in all the compute nodes.

I will check it ASAP.

Thank you very much for yours answers.

**Comment by byquip** [comment]
probably I need to move lines:
```
module load mpi/openmpi;
module load python/3.6-anaconda3;
```

to the `--wrap=''` before` srun`.

**Comment by dalcinl** [comment]
Or perhaps try `$(command -v python)` instead of just `python`.

**Comment by byquip** [comment]
@dalcinl Got the same results with both fixes as before.
@leofang mentioned activation of the same Python environment across all compute nodes. 
Could you please tell how to check it if I did not make it?

**Comment by dalcinl** [comment]
@byquip Can you uninstall mpi4py form `$HOME/.local` and install mpi4py on a new conda environment instead? If using conda environments (as opposed to use system Python or loading modules providing python), then having mpi4py installed in `~/.local` is a really bad idea. Unless you are 100 % sure mpi4py was built with the exact same Python as the environment you are using. 

What the output of `ldd ~/.local/lib/python3.6/site-packages/mpi4py/MPI.*.so` ?

**Comment by byquip** [comment]
@dalcinl  output is:
ldd ~/.local/lib/python3.6/site-packages/mpi4py/MPI.*.so
        linux-vdso.so.1 =>  (0x00007ffe3fd57000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fe676c73000)
        libpython3.6m.so.1.0 => /opt/software/anaconda/3/lib/libpython3.6m.so.1.0 (0x00007fe67672e000)
        libmpifort.so.12 => /opt/software/intel/impi_5.0.2/intel64/lib/libmpifort.so.12 (0x00007fe6764a5000)
        libmpi.so.12 => /opt/software/intel/impi_5.0.2/intel64/lib/release_mt/libmpi.so.12 (0x00007fe675d32000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fe675b29000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe67590d000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fe67554c000)
        /lib64/ld-linux-x86-64.so.2 (0x00000037b0200000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007fe675348000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fe675046000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fe674e30000)

**Comment by dalcinl** [comment]
There you have. You are loading some Open MPI module in your batch script, but mpi4py seems to be built with Intel MPI. So, do not load the Open MPI module.

If you use Intel MPI, please read the following:
https://software.intel.com/content/www/us/en/develop/articles/python-mpi4py-on-intel-true-scale-and-omni-path-clusters.html

If you go for the second option, I recommend that you manually edit `~/.local/lib/python3.6/site-packages/mpi4py/__init__.py`  and set `rc.recv_mprobe = False`, otherwise the trick will not work when using mpi4py.futures.
Executing the following command should do it:
```
echo rc.recv_mprobe=False >> ~/.local/lib/python3.6/site-packages/mpi4py/__init__.py
```

**Comment by byquip** [comment]
@dalcinl Tried without loading openmpi and set  `rc.recv_mprobe = False` then error kind of random but new one appears: 
```
Traceback (most recent call last):
  File "/opt/software/anaconda/3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/software/anaconda/3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vasko/.local/lib/python3.6/site-packages/mpi4py/futures/__main__.py", line 72, in <module>
    main()
  File "/home/vasko/.local/lib/python3.6/site-packages/mpi4py/futures/__main__.py", line 60, in main
    run_command_line()
  File "/home/vasko/.local/lib/python3.6/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/opt/software/anaconda/3/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/opt/software/anaconda/3/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/opt/software/anaconda/3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "cali_send_2.py", line 116, in <module>
    globals()[sys.argv[1]](sys.argv[2], sys.argv[3])
  File "cali_send_2.py", line 80, in solve_on_cali
    sols = list(executor.map(solve_matrix, repeat(inputs), *list(zip(*enumerate(wls)))))
  File "/home/vasko/.local/lib/python3.6/site-packages/mpi4py/futures/pool.py", line 207, in result_iterator
    yield futures.pop().result()
  File "/opt/software/anaconda/3/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/opt/software/anaconda/3/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
_pickle.UnpicklingError: invalid load key, '\x9e'.
```
There is two errors previous one and this (already was mentioned at first message)
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 1: invalid start byte`

Also I have another weird stuff as well somehow connected with input range.
I checking it with index of solution here:
```
w, v, solnum, vq = sol
print(w[0], solnum) # this line will shows if data have duplicates.
```

`solnum` in output suppose to be list of solutions id from 0 to `len(sols)-1`
But output looks like function returns duplicates. array
![image](https://user-images.githubusercontent.com/60094563/113984089-ff1ca000-984a-11eb-90c3-59a4ad2f17f8.png)
It's returns right solutions without duplicates if I put different values for `wls` 
![image](https://user-images.githubusercontent.com/60094563/113984793-c4ffce00-984b-11eb-9dca-ee8ed63fe7d4.png)

**Comment by byquip** [comment]
[This](https://github.com/Project-Platypus/Platypus/issues/94#issuecomment-481512283) looks connected.

**Comment by dalcinl** [comment]
What happens if you run your code locally, in a workstation or laptop? This really looks like your MPI implementation is messing with your messages and corrupting them. That's the reason you get these pickling errors. As this point I have to say I'm sorry, your MPI seems to be broken, and your issues do not look like being mpi4py's fault.

Can't you try creating a conda environment, getting rid or your current mpi4py install, and installing mpi4py in the conda environment using an MPI implementation your cluster supports by loading a module (e.g. Open MPI)?

**Comment by dalcinl** [comment]
> [This](https://github.com/Project-Platypus/Platypus/issues/94#issuecomment-481512283) looks connected.

Could be, but that would mean that your MPI implementation is somehow broken/buggy and cannot `isend()`.

**Comment by byquip** [comment]
I decide to change return and save data through `np.savez_compressed` instead of use return 
type `List[Union[np.ndarray, np.ndarray, int, np.ndarray]`. 
I think it's connected with some numpy decoding stuff. 
Thank you for your help.
