### ISSUE TITLE
Pi Calculation example

### ISSUE THREAD

**Issue by bkmgit** [mpi4py/mpi4py#46]
Might it be worth adding the following example code:

```Python
import numpy as np
import sys
import datetime
from mpi4py import MPI

def inside_circle(total_count):
  x = np.random.uniform(size=total_count)
  y = np.random.uniform(size=total_count)
  radii = np.sqrt(x*x + y*y)
  count = len (radii[np.where(radii<=1.0)])
  return count

def main():
  comm = MPI.COMM_WORLD
  n_cpus = comm.Get_size()
  rank = comm.Get_rank()
  n_samples = int(sys.argv[1])
  if rank == 0:
    my_samples = n_samples - ( n_cpus - 1 ) * np.int(np.floor(n_samples/n_cpus))
  else:
    my_samples = np.int(np.floor(n_samples/n_cpus))

  comm.Barrier()
  start_time = datetime.datetime.now()
  my_counts = inside_circle(my_samples)
  counts = comm.allreduce(my_counts,op=MPI.SUM)
  comm.Barrier()
  end_time = datetime.datetime.now()
  elapsed_time = (end_time - start_time).total_seconds()
  my_pi = 4.0 * counts / n_samples
  if rank == 0:
    print("Pi: {}, time: {} s".format(my_pi,elapsed_time))

if __name__ == '__main__':
  main()
```
There is a version of this used in [HPC-Carpentry](https://carpentries-incubator.github.io/hpc-intro/16-parallel/index.html), but some of the commands are not so well documented in the [tutorial](https://mpi4py.readthedocs.io/en/stable/tutorial.html)

**Comment by dalcinl** [comment]
The snippets in the tutorial are supposed to be small and have minimal dependencies. The objective is to feature the MPI API, not how to implement algorithms like this Monte Carlo example.

* Your code is simply too long for a tutorial snippet
* There is nothing new about MPI compared to the existing Compute Pi example
* You code uses datatime and not MPI's on way to do timing (`MPI.Wtime()`)
* Your coding and naming conventions for local variables do not follow the usual pattern elsewhere. For example, we do not use `n_cpus` but `size`.  Things like `np.int(np.floor(n_samples/n_cpus))` would read much better as simply `n_samples // n_cpus` (integer division).
* The only reason you use `Barrier()` is to somehow get better timings. But timing is not material for tutorial snippets, as that adds extra lines about non-MPI stuff.
* A balanced local number of samples `n` for a total of `N` is much simpler (and better balanced) to compute with `n = N // size + (N % size > rank)`, were `size` and `rank` are the number of processes and process id, respectively.

Note however that after some polishing, this Monte Carlo-based Compute Pi calculation would be a good addition for the `demo/compute-pi` directory.
