### ISSUE TITLE
Interactive Python Shell becomes unresponsive with Threads connected to mpi4py parallel processes

### ISSUE THREAD

**Issue by jan-janssen** [mpi4py/mpi4py#468]
I have one master python process, which is connected to four threads and each of those threads is connected to an mpi4py parallel python process. 

Here is a minimalistic example of the `mpi4py` parallel part, in this reduced example it is just replying the message: `server_mpi.py`
```
import zmq
import sys
from mpi4py import MPI


if __name__ == "__main__":
    mpi_rank_zero = MPI.COMM_WORLD.Get_rank() == 0
    if mpi_rank_zero:
        port = sys.argv[-1]
        context = zmq.Context()
        socket = context.socket(zmq.PAIR)
        socket.connect("tcp://localhost:" + str(port))
    else:
        context = None
        socket = None
    while True:
        if mpi_rank_zero:
            message = socket.recv()
        else:
            message = None 
        message = MPI.COMM_WORLD.bcast(message, root=0)
        if mpi_rank_zero:
            socket.send(message)
```

In an interactive python shell I run the following: 
```
>>> from concurrent.futures import Future
>>> from queue import Queue
>>> import zmq
>>> import cloudpickle
>>> import subprocess
>>> from threading import Thread
>>> def manager_thread(queue):
>>>     context = zmq.Context()
>>>     socket = context.socket(zmq.PAIR)
>>>     port = socket.bind_to_random_port("tcp://*")
>>>     process = subprocess.Popen(["mpiexec", "-n", "2", "python", "server_mpi.py", str(port)])
>>>     # process = subprocess.Popen(["python", "server_nompi.py", str(port)])
>>>     while True:
>>>         task_dict = queue.get()
>>>         f = task_dict["future"]
>>>         if f.set_running_or_notify_cancel():
>>>             socket.send(cloudpickle.dumps(task_dict["message"]))
>>>             f.set_result(cloudpickle.loads(socket.recv()))
>>>         queue.task_done()
>>> 
>>> queue = Queue()
>>> for i in range(4):
>>>      process = Thread(target=manager_thread, kwargs={"queue":queue})
>>>      process.start()
>>> task_dict = {"future": Future(), "message": "message to be executed"}
>>> queue.put(task_dict)
>>> print(task_dict["future"].result())
"message to be executed"
```

Once the four threads are started the interactive python shell becomes very unresponsive. To me this seems to be related to a thread deadlock, but I have a hard time to identify what is causing the interactive shell to become unresponsive. 

When I run the same example with a serial python function to return the message, I do not have the same issue: `server_nompi.py`
```
import zmq
import sys

if __name__ == "__main__":
    port = sys.argv[-1]
    context = zmq.Context()
    socket = context.socket(zmq.PAIR)
    socket.connect("tcp://localhost:" + str(port))
    while True:
        message = socket.recv()
        socket.send(message)
```

At the same time, I see that the mpi4py parallel processes have 100% CPU utilisation, which I guess is related to the processes waiting at the `MPI.COMM_WORLD.bcast()`. 

Can anybody help me how to debug this issue? I also tried to invert the connection, starting the `zmq` host on the MPI parallel process and connecting to it from the thread rather than the other way around, but that did not help either. Now I am out of ideas to try, so I look for suggestions.

**Comment by dalcinl** [comment]
Are you using MPICH with the (default) Hydra process manager, right? 
In any case, pass  `stdin=subprocess.DEVNULL` to your `subprocess.Popen` and your issue should be fixed.

**Comment by dalcinl** [comment]
The 100% CPU from MPI broadcast will persist, though. 
Before the broadcast call, you could insert a call to a custom barrier function:

```python
def barrier(comm)
        request = comm.Ibarrier()
        while not request.Test():
            time.sleep(1e-4)
```
You could improve latency using exponential backoff, search for it in the mpi4py.futures implementation. Or even better, you could just reuse the `barrier()` function from the `mpi4py.futures._core` module.

**Comment by jan-janssen** [comment]
> Are you using MPICH with the (default) Hydra process manager, right? In any case, pass `stdin=subprocess.DEVNULL` to your `subprocess.Popen` and your issue should be fixed.

@dalcinl Thanks a lot, this fixed the issue. Even though I was using `openmpi` (4.1.6) rather than `mpich` adding the `stdin=subprocess.DEVNULL` was the solution.
