### ISSUE TITLE
mpi4py.profile didn't generate logfile

### ISSUE THREAD

**Issue by TRSWNCA** [mpi4py/mpi4py#470]
I tried both `mpe` and `vt` method, but neigther generated logfile, and didn't show any log about how error occurs.

I printed the dylib, which shows `/home/cyc/.anaconda3/lib/python3.9/site-packages/mpi4py/lib-pmpi/libmpe.so`. It looks like everything is right except log generation.

I'm using Ubuntu 22.04.3 LTS, and installed mpi4py lib using `pip3 install mpi4py`. 

Here is my enviorment:
```bash
$ pip show mpi4py
Name: mpi4py
Version: 3.1.5
Summary: Python bindings for MPI
Home-page: https://github.com/mpi4py/mpi4py/
Author: Lisandro Dalcin
Author-email: dalcinl@gmail.com
License: BSD
Location: /home/cyc/.anaconda3/lib/python3.9/site-packages
Requires: 
Required-by: 
$ mpiexec --version
mpiexec (OpenRTE) 4.1.2
Report bugs to http://www.open-mpi.org/community/help/
```

Any idea for locating the problem? Looking for your reply. Thanks.

**Comment by dalcinl** [comment]
For logfiles to be generated you need additional libraries installed in your system, like [MPE](https://www.mpich.org/static/mpe/downloads/) or Vampir, at the time you build and install mpi4py. 
All this support explicit support within mpi4y for profiling is at this point legacy. Next mpi4py release will remove explicit support for MPE and Vampir, although keeping the `profile()` function there for backward compatibility. You would still be able to pass the name and path of a specific MPI profiling library to the `profile()` function and things should work, but where/how to get that profiling library would no longer be responsibility of mpi4py.

If you really need to do MPI profiling, then you should look elsewhere for any external tool/framework allowing the profiling of MPI applications, and then look at these third-party instructions on how to make things working.
