### ISSUE TITLE
[BLD] Better handling of MS-MPI version check at build time

### ISSUE THREAD

**Issue by leofang** [mpi4py/mpi4py#48]
See https://github.com/mpi4py/mpi4py/issues/19#issuecomment-826221898.

**Comment by leofang** [comment]
I have been thinking about this but I'm still unsure if there's a robust way for handling this. Specifically, how do I reliably tell if MS-MPI is from Conda or not? The only approach I come up --- which is no doubt silly --- is to check `msmpi.h`'s absolute path, look up the current env's path (if any) and see if it's in any conda env. This check is needed because we could have MS-MPI installed normally via a Windows installer and build mpi4py in a conda env.

**Comment by dalcinl** [comment]
Why would we care about the source? Now that the conda-forge package has `MSMPI_VER` forcibly `#define`'d in `mpi.h`, everything should be fine. The only reason mpi4py looks in the Windows registry is to define `MSMPI_VER` to the proper value. Am I missing something?

**Comment by leofang** [comment]
Yes, this is exactly what I was referring to. Don't we *always* look up from the Windows registry (by calling `msmpi_ver()`)?
https://github.com/mpi4py/mpi4py/blob/18f16da45eaaacfba4cc0293964e1a6548d4c6a6/conf/mpiconfig.py#L193-L198
It shouldn't be necessary to either look up or define the `MSMPI_VER` macro if we are using MS-MPI from conda-forge.

**Comment by dalcinl** [comment]
Do you agree that defining `MSMPI_VER` is ultimately harmless if building against the conda-forge package?

Perhaps a minor improvement in mpi4py could be to always lookup the registry, but only define `MSMPI_VER` if the the registry key is actually found.

**Comment by leofang** [comment]
> Do you agree that defining `MSMPI_VER` is ultimately harmless if building against the conda-forge package?

Well, apparently it's harmless only because we forgot to set `-Werror` in mpi4py-feedstock. See, there's a macro redefinition warning:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=343916&view=logs&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=1183ba29-a0b5-5324-8463-2a49ace9e213&l=671
Though I am a bit confused why mpi4py picked up the correct version instead of the wrong one from the cmdline:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=343916&view=logs&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=1183ba29-a0b5-5324-8463-2a49ace9e213&l=916

> Perhaps a minor improvement in mpi4py could be to always lookup the registry, but only define `MSMPI_VER` if the the registry key is actually found.

This could be unsafe if the user already has a local MS-MPI installed that has a different `MSMPI_VER` from Conda-Forge's.

**Comment by dalcinl** [comment]
> Well, apparently it's harmless only because we forgot to set `-Werror` in mpi4py-feedstock.

Yes, of course. But I would not say we "forgot" to add it. IMHO, `-Werror` is not something you would add in production. And `-Werror` is GCC-specific. 

> This could be unsafe if the user already has a local MS-MPI installed that has a different MSMPI_VER from Conda-Forge's.

In that case, I believe things are already broken. mpi4py will try to use the system MS-MPI, not sure which one will win in the include&library paths. 

The only robust think I can imagine is to somehow look for `CONDA_BUILD` in the environment and special-case the build. And this is not really detecting whether MS-MPI comes from the system or conda-forge, it is just a hack for the time we build the mpi4py conda-package. Not my favorite approach, but sometimes you are left with no options.

**Comment by leofang** [comment]
> Yes, of course. But I would not say we "forgot" to add it. IMHO, `-Werror` is not something you would add in production.

This I totally I agree. Though I also know some people care about it a lot...

> And `-Werror` is GCC-specific.

Sure, it's `/WX` for msvc. You know what I meant 😛
  
> In that case, I believe things are already broken. mpi4py will try to use the system MS-MPI, not sure which one will win in the include&library paths.
> 
> The only robust think I can imagine is to somehow look for `CONDA_BUILD` in the environment and special-case the build. And this is not really detecting whether MS-MPI comes from the system or conda-forge, it is just a hack for the time we build the mpi4py conda-package. Not my favorite approach, but sometimes you are left with no options.

This would only fix for the mpi4py-feedstock, not for general users who are building mpi4py locally without involving conda-build at all. This is my main concern, but given that no one comes to complain, I feel it's a rare case??

**Comment by dalcinl** [comment]
> Though I also know some people care about it a lot...

Yes, I do care a lot about it. But for my own code and standard development workflows, not for third-party code or non-standard use cases.

> Sure, it's /WX for msvc. You know what I meant :stuck_out_tongue:

No, it didn't. I had no idea of that flag for MSVC. I have not used Windows in the last 20 years, much less done software development with MSVC.

> This is my main concern, 

I understand, but...

> but given that no one comes to complain, I feel it's a rare case??

Most likely.

Do not get me wrong, if we can get a simple and robust fix, I'm all for it. But so far I do not have one to propose. Moreover, since MSMPI was opensourced, I got the feeling it will become abandonware.

**Comment by leofang** [comment]
What If we do this? We first look up MS-MPI's `mpi.h` (which on conda-forge has `MSMPI_VER` defined to 0xA01). If it's equal to the default (0x100) it means it's likely not from conda-forge, then we look up from the registry as is done now. The header check can be easily performed with the machinery
```python
ok = config_cmd.try_compile(ConfigTest, headers=headers) 
```
which already exists in `setup.py`.

**Comment by dalcinl** [comment]
Microsoft MPI has become abandonware. I recently got Intel MPI working mostly fine on Windows [[link]](https://github.com/mpi4py/mpi4py-testing/actions/workflows/intelmpi.yml) (modulo a bunch of issues that would require the involvement of Intel MPI dev team).

I'm tempted to close this issue as wontfix. @leofang?

**Comment by leofang** [comment]
Yeah I saw that, interesting that Intel MPI now works on Windows... is it new development?

**Comment by leofang** [comment]
(Yes let's close this one.)

**Comment by dalcinl** [comment]
> is it new development?

Probably not very new, but I'm not really sure.

**Comment by dalcinl** [comment]
Update: #395 improves the handling of `MSMPI_VER`. If `MSMPI_VER` is not found in the Windows registry, then as an environment variable (this is not standard practice for MSMPI), and if still not found, then MSMPI_VER is not defined at all. Building with the conda-forge package should be unaffected thanks to the patching of `mpi.h`, with the plus that the compiler warnings about the MSMPI_VER macro redefinition is now gone and @leofang can happily start passing `/WX` to `cl.exe`.
