### ISSUE TITLE
mpi4py.futures and COMM_WORLD.r(): Blocking calls 

### ISSUE THREAD

**Issue by blueskypac** [mpi4py/mpi4py#49]
I am trying to use mpi4py.futures with `MpiProcessPool`. When I do so, I aim to use the `.send()` and `.recv` methods of `COMM_WORLD` to send data from the master process to the worker processes. However, the workers never receive any message and block execution. Could you let me know whether `MpiProcessPool` is not meant to be used with `send()` and `recv()`?

**Comment by dalcinl** [comment]
> Could you let me know whether `MpiProcessPool` is not meant to be used with `send()` and `recv()`?

That's not the way you are supposed to use `mpi4py.futures`. The whole point of the `mpi4py.futures` package is to encapsulate and hide the complexities of MPI communication, providing an API that is very close to Python's stdlib `concurrent.futures` package. Please read the [mpi4py.futures](https://mpi4py.readthedocs.io/en/stable/mpi4py.futures.html) documentation, `send()` and `recv()` should not be used with `MPIProcessPool`.

**Comment by blueskypac** [comment]
Thank you for the answer. I read the documentation in `mpi4py.futures` and saw mentioned that is meant as a specific implementation of the `ExecutorPool` class. However, I found yesterday that `send()` and `recv()` does it indeed work with processes run as part of an `MpiProcessPool`. Do you see any downsides/risks of using those methods even though they were not originally meant to be used in this context?

**Comment by dalcinl** [comment]
In your original comment, you say that workers never receive any messages and block execution. And now you say that you found that send and recv do work. So I'm not really sure what you mean. In any case, I repeat it again: `mpi4py.futures` should be used as intended, without any MPI communication. If you break that rule, you are at your own. Anything that may seem to work in some scenario may stop working in a different scenario (e.g. a different MPI implementation), and it may break in subsequent mpi4py release.

**Comment by leofang** [comment]
@dalcinl Let me reopen this as a reminder for myself that I want to improve the doc for `mpi4py.futures`. Specifically, based on our offline chat when writing the paper and the above discussion, I want to add a big warning to say it out loud that none of the MPI primitives should be called when using `mpi4py.futures`.

**Comment by blueskypac** [comment]
Ok, thank you for the clarification - I understand now that no MPI primitives should be used. 

@dalcinl After I wrote my first issue and I worked on my logic for `send()` and `recv()` statements and made it work. But I will then turn away from that solution to avoid using something that is not meant to be done.

**Comment by blueskypac** [comment]
Sorry to ask one more questions here: Is it also not recommended to use `send()` and `recv()` with `mpi4py.futures.MPICommExecutor`? My goal of sending messages back and forth is basically to know on which node a task will be submitted once a slot becomes available after a future has completed. If three futures complete almost at the same time and a new task will then be submitted to the pool, how can I find out to which rank it will go and thus which node will be used in the cluster?

**Comment by dalcinl** [comment]
Why would you like to know that? If the rationale is debugging/logging/profiling purposes then I'll not object. However, if your algorithm/application will depend on that, then perhaps `mpi4py.futures` is not the right tool for you. 

Would it be enough to know the rank *post-mortem*, after the task completed? If that is the case, then you just need to make your task return `(MPI.COMM_WORLD.rank, task_result)`.

Could you describe what you are trying to achieve exactly?

With `MPICommExecutor` you may have a better chance. However, you should use a duplicated communicator to not interfere with the master-worker communication, something like this:

```python
comm = MPI.COMM_WORLD
dup_comm = comm.Dup()
with MPICommExecutor(comm) as executor:
    if executor:
        .... # your code here
```
