### ISSUE TITLE
How to obtain env vars using function os.envrion.get()?

### ISSUE THREAD

**Issue by Beck-127** [mpi4py/mpi4py#497]
I want to set some vars from environment variables, e.g.
`self.world_size = int(os.environ['OMPI_COMM_WORLD_SIZE'])
self.local_size = int(os.environ['OMPI_COMM_WORLD_LOCAL_SIZE'])
self.rank = int(os.environ['OMPI_COMM_WORLD_RANK'])
self.local_rank = int(os.environ['OMPI_COMM_WORLD_LOCAL_RANK'])`

But it did not work properly, and I printed the os.environ keys, it just has:
`['BROWSER', 'CLASSPATH', 'COLORTERM', 'CONDA_DEFAULT_ENV', 'CONDA_EXE', 'CONDA_PREFIX', 'CONDA_PROMPT_MODIFIER', 'CONDA_PYTHON_EXE', 'CONDA_ROOT', 'CONDA_SHLVL', 'DBUS_SESSION_BUS_ADDRESS', 'FI_PROVIDER_PATH', 'GFORTRAN_UNBUFFERED_PRECONNECTED', 'GIT_ASKPASS', 'GOROOT', 'GSETTINGS_SCHEMA_DIR', 'GSETTINGS_SCHEMA_DIR_CONDA_BACKUP', 'HOME', 'HYDRA_BSTRAP_DEBUG', 'HYDRA_BSTRAP_DOWNSTREAM_CONTROL', 'HYDRA_BSTRAP_DOWNSTREAM_HOSTS', 'HYDRA_BSTRAP_DOWNSTREAM_PID', 'HYDRA_BSTRAP_DOWNSTREAM_STDERR', 'HYDRA_BSTRAP_DOWNSTREAM_STDOUT', 'HYDRA_BSTRAP_LAUNCHER', 'HYDRA_BSTRAP_LOCALHOST', 'HYDRA_BSTRAP_NODE_ID', 'HYDRA_BSTRAP_NUM_DOWNSTREAM_PROXIES', 'HYDRA_BSTRAP_NUM_LAUNCHES', 'HYDRA_BSTRAP_PGID', 'HYDRA_BSTRAP_PROXY_ID', 'HYDRA_BSTRAP_SUBTREE_SIZE', 'HYDRA_BSTRAP_TREE_WIDTH', 'HYDRA_BSTRAP_UPSTREAM_FD', 'HYDRA_IP_VERSION', 'HYDRA_LAUNCH_TYPE', 'I_MPI_BIND_WIN_ALLOCATE', 'I_MPI_HYDRA_TOPOLIB', 'I_MPI_HYDRA_UUID', 'I_MPI_INFO_BRAND', 'I_MPI_INFO_CACHE1', 'I_MPI_INFO_CACHE2', 'I_MPI_INFO_CACHE3', 'I_MPI_INFO_CACHES', 'I_MPI_INFO_CACHE_SHARE', 'I_MPI_INFO_CACHE_SIZE', 'I_MPI_INFO_CORE', 'I_MPI_INFO_C_NAME', 'I_MPI_INFO_DESC', 'I_MPI_INFO_FLGB', 'I_MPI_INFO_FLGC', 'I_MPI_INFO_FLGCEXT', 'I_MPI_INFO_FLGD', 'I_MPI_INFO_FLGDEXT', 'I_MPI_INFO_LCPU', 'I_MPI_INFO_MODE', 'I_MPI_INFO_NC', 'I_MPI_INFO_NP', 'I_MPI_INFO_NUMA_NODE_MAP', 'I_MPI_INFO_NUMA_NODE_NUM', 'I_MPI_INFO_PACK', 'I_MPI_INFO_SERIAL', 'I_MPI_INFO_SIGN', 'I_MPI_INFO_STATE', 'I_MPI_INFO_THREAD', 'I_MPI_INFO_VEND', 'I_MPI_INTERNAL_MEM_POLICY', 'I_MPI_MPIRUN', 'I_MPI_PIN_INFO', 'I_MPI_PIN_MAPPING', 'I_MPI_RETURN_WIN_MEM_NUMA', 'I_MPI_ROOT', 'LANG', 'LANGUAGE', 'LD_LIBRARY_PATH', 'LESSCLOSE', 'LESSOPEN', 'LIBRARY_PATH', 'LOGNAME', 'LS_COLORS', 'MANPATH', 'MOTD_SHOWN', 'MPI_LOCALNRANKS', 'MPI_LOCALRANKID', 'OLDPWD', 'PATH', 'PMI_FD', 'PMI_RANK', 'PMI_SIZE', 'PS1', 'PWD', 'SHELL', 'SHLVL', 'SSH_CLIENT', 'SSH_CONNECTION', 'SSL_CERT_DIR', 'SSL_CERT_FILE', 'TERM', 'TERM_PROGRAM', 'TERM_PROGRAM_VERSION', 'USER', 'VSCODE_GIT_ASKPASS_EXTRA_ARGS', 'VSCODE_GIT_ASKPASS_MAIN', 'VSCODE_GIT_ASKPASS_NODE', 'VSCODE_GIT_IPC_HANDLE', 'VSCODE_IPC_HOOK_CLI', 'XDG_DATA_DIRS', 'XDG_RUNTIME_DIR', 'XDG_SESSION_CLASS', 'XDG_SESSION_ID', 'XDG_SESSION_TYPE', '_', '_CE_CONDA', '_CE_M']`
does not exist 4 env vars mentioned above.

MY environment:
`# This file may be used to create an environment using:
\# $ conda create --name <env> --file <this file>
\# platform: linux-64
_libgcc_mutex=0.1=conda_forge
_openmp_mutex=4.5=2_gnu
absl-py=2.1.0=pypi_0
accelerate=0.23.0=pypi_0
aiofiles=23.2.1=pypi_0
aliyun-python-sdk-core=2.15.1=pypi_0
aliyun-python-sdk-kms=2.16.2=pypi_0
altair=5.3.0=pypi_0
antlr4-python3-runtime=4.9.3=pypi_0
anyio=4.3.0=pypi_0
appdirs=1.4.4=pypi_0
argon2-cffi=21.3.0=pyhd3eb1b0_0
argon2-cffi-bindings=21.2.0=py39h7f8727e_0
asttokens=2.0.5=pyhd3eb1b0_0
async-lru=2.0.4=py39h06a4308_0
attrs=23.2.0=pypi_0
babel=2.11.0=py39h06a4308_0
backcall=0.2.0=pyhd3eb1b0_0
beautifulsoup4=4.12.2=py39h06a4308_0
black=21.4b2=pypi_0
blas=1.0=mkl
bleach=4.1.0=pyhd3eb1b0_0
brotli-python=1.0.9=py39h6a678d5_7
bzip2=1.0.8=h5eee18b_5
ca-certificates=2024.3.11=h06a4308_0
certifi=2024.2.2=py39h06a4308_0
cffi=1.16.0=py39h5eee18b_1
chardet=4.0.0=py39h06a4308_1003
charset-normalizer=3.3.2=pypi_0
cityscapesscripts=2.2.2=pypi_0
click=8.1.7=pypi_0
cloudpickle=3.0.0=pypi_0
coloredlogs=15.0.1=pypi_0
comm=0.2.1=py39h06a4308_0
contourpy=1.2.1=pypi_0
crcmod=1.7=pypi_0
cryptography=42.0.5=pypi_0
cuda-cudart=12.1.105=0
cuda-cupti=12.1.105=0
cuda-libraries=12.1.0=0
cuda-nvrtc=12.1.105=0
cuda-nvtx=12.1.105=0
cuda-opencl=12.4.127=0
cuda-runtime=12.1.0=0
cudatoolkit=10.1.243=h6bb024c_0
cudnn=7.6.5=cuda10.1_0
cupy=8.3.0=py39hcaf9a05_0
cycler=0.12.1=pypi_0
cyrus-sasl=2.1.28=h52b45da_1
cython=3.0.2=pypi_0
dbus=1.13.18=hb2f20db_0
debugpy=1.6.7=py39h6a678d5_0
decorator=5.1.1=pyhd3eb1b0_0
deepspeed=0.10.3=pypi_0
defusedxml=0.7.1=pyhd3eb1b0_0
detectron2=0.6=pypi_0
diffdist=0.1=pypi_0
docker-pycreds=0.4.0=pypi_0
einops=0.7.0=pypi_0
exceptiongroup=1.2.0=py39h06a4308_0
executing=0.8.3=pyhd3eb1b0_0
expat=2.6.2=h6a678d5_0
fastapi=0.110.1=pypi_0
fastrlock=0.6=py39h2531618_0
ffmpeg=4.3=hf484d3e_0
ffmpy=0.3.2=pypi_0
filelock=3.13.4=pypi_0
fontconfig=2.14.1=h4c34cd2_2
fonttools=4.51.0=pypi_0
freetype=2.12.1=h4a9f257_0
fsspec=2024.3.1=pypi_0
ftfy=6.1.1=pypi_0
future=1.0.0=pypi_0
fvcore=0.1.5.post20221221=pypi_0
gitdb=4.0.11=pypi_0
gitpython=3.1.43=pypi_0
glib=2.78.4=h6a678d5_0
glib-tools=2.78.4=h6a678d5_0
gmp=6.2.1=h295c915_3
gmpy2=2.1.2=py39heeb90bb_0
gnutls=3.6.15=he1e5248_0
gradio=3.42.0=pypi_0
gradio-client=0.5.0=pypi_0
grpcio=1.62.1=pypi_0
gst-plugins-base=1.14.1=h6a678d5_1
gstreamer=1.14.1=h5eee18b_1
h11=0.14.0=pypi_0
h5py=3.11.0=pypi_0
hjson=3.1.0=pypi_0
httpcore=1.0.5=pypi_0
httpx=0.27.0=pypi_0
huggingface-hub=0.17.3=pypi_0
humanfriendly=10.0=pypi_0
hydra-core=1.3.2=pypi_0
icu=73.1=h6a678d5_0
idna=3.7=pypi_0
imageio=2.34.0=pypi_0
importlib-metadata=7.1.0=pypi_0
importlib-resources=6.4.0=pypi_0
importlib_metadata=7.0.1=hd3eb1b0_0
infinibatch=0.1.1=pypi_0
intel-openmp=2023.1.0=hdb19cb5_46306
iopath=0.1.9=pypi_0
ipykernel=6.28.0=py39h06a4308_0
ipython=8.15.0=py39h06a4308_0
ipywidgets=8.1.2=py39h06a4308_0
jedi=0.18.1=py39h06a4308_1
jinja2=3.1.3=py39h06a4308_0
jmespath=0.10.0=pypi_0
joblib=1.4.0=pypi_0
jpeg=9e=h5eee18b_1
json-tricks=3.17.3=pypi_0
json5=0.9.6=pyhd3eb1b0_0
jsonschema=4.21.1=pypi_0
jsonschema-specifications=2023.12.1=pypi_0
jupyter=1.0.0=py39h06a4308_9
jupyter-lsp=2.2.0=py39h06a4308_0
jupyter_client=8.6.0=py39h06a4308_0
jupyter_console=6.6.3=py39h06a4308_0
jupyter_core=5.5.0=py39h06a4308_0
jupyter_events=0.8.0=py39h06a4308_0
jupyter_server=2.10.0=py39h06a4308_0
jupyter_server_terminals=0.4.4=py39h06a4308_1
jupyterlab=4.0.11=py39h06a4308_0
jupyterlab_pygments=0.1.2=py_0
jupyterlab_server=2.25.1=py39h06a4308_0
jupyterlab_widgets=3.0.10=py39h06a4308_0
kiwisolver=1.4.5=pypi_0
kornia=0.7.0=pypi_0
krb5=1.20.1=h143b758_1
lame=3.100=h7b6447c_0
lazy-loader=0.4=pypi_0
lcms2=2.12=h3be6417_0
ld_impl_linux-64=2.38=h1181459_1
lerc=3.0=h295c915_0
libclang=14.0.6=default_hc6dbbc7_1
libclang13=14.0.6=default_he11475f_1
libcublas=12.1.0.26=0
libcufft=11.0.2.4=0
libcufile=1.9.1.3=0
libcups=2.4.2=h2d74bed_1
libcurand=10.3.5.147=0
libcusolver=11.4.4.55=0
libcusparse=12.0.2.55=0
libdeflate=1.17=h5eee18b_1
libedit=3.1.20230828=h5eee18b_0
libffi=3.4.4=h6a678d5_0
libgcc-ng=13.2.0=h807b86a_5
libgfortran-ng=13.2.0=h69a702a_5
libgfortran5=13.2.0=ha4646dd_5
libglib=2.78.4=hdc74915_0
libgomp=13.2.0=h807b86a_5
libiconv=1.16=h7f8727e_2
libidn2=2.3.4=h5eee18b_0
libjpeg-turbo=2.0.0=h9bf148f_0
libllvm14=14.0.6=hdb19cb5_3
libnpp=12.0.2.50=0
libnvjitlink=12.1.105=0
libnvjpeg=12.1.1.14=0
libpng=1.6.39=h5eee18b_0
libpq=12.17=hdbd6064_0
libsodium=1.0.18=h7b6447c_0
libstdcxx-ng=13.2.0=h7e041cc_5
libtasn1=4.19.0=h5eee18b_0
libtiff=4.5.1=h6a678d5_0
libunistring=0.9.10=h27cfd23_0
libuuid=1.41.5=h5eee18b_0
libwebp-base=1.3.2=h5eee18b_0
libxcb=1.15=h7f8727e_0
libxkbcommon=1.0.1=h5eee18b_1
libxml2=2.10.4=hfdd30dd_2
llvm-openmp=14.0.6=h9e868ea_0
llvmlite=0.42.0=pypi_0
lz4-c=1.9.4=h6a678d5_0
markdown=3.6=pypi_0
markdown-it-py=3.0.0=pypi_0
markupsafe=2.1.5=pypi_0
matplotlib=3.8.4=pypi_0
matplotlib-inline=0.1.6=py39h06a4308_0
mdurl=0.1.2=pypi_0
mistune=2.0.4=py39h06a4308_0
mkl=2023.1.0=h213fc3f_46344
mkl-service=2.4.0=py39h5eee18b_1
mkl_fft=1.3.8=py39h5eee18b_0
mkl_random=1.2.4=py39hdb19cb5_0
more-itertools=10.2.0=pypi_0
mpc=1.1.0=h10f8cd9_1
mpfr=4.0.2=hb69a4c5_1
mpi=1.0=mpich
mpi4py=3.1.5=py39h6cbbaa3_1
mpich=4.2.1=h846660c_100
mpmath=1.3.0=py39h06a4308_0
multiscaledeformableattention=1.0=pypi_0
mup=1.0.0=pypi_0
mypy-extensions=1.0.0=pypi_0
mysql=5.7.24=h721c034_2
nbclient=0.8.0=py39h06a4308_0
nbconvert=7.10.0=py39h06a4308_0
nbformat=5.9.2=py39h06a4308_0
nccl=2.8.3.1=hcaf9a05_0
ncurses=6.4=h6a678d5_0
nest-asyncio=1.6.0=py39h06a4308_0
nettle=3.7.3=hbbd107a_1
networkx=3.2.1=pypi_0
ninja=1.11.1.1=pypi_0
nltk=3.8.1=pypi_0
notebook=7.0.8=py39h06a4308_0
notebook-shim=0.2.3=py39h06a4308_0
numba=0.59.1=pypi_0
numpy=1.23.1=pypi_0
numpy-base=1.26.4=py39hb5e798b_0
nvidia-cublas-cu12=12.1.3.1=pypi_0
nvidia-cuda-cupti-cu12=12.1.105=pypi_0
nvidia-cuda-nvrtc-cu12=12.1.105=pypi_0
nvidia-cuda-runtime-cu12=12.1.105=pypi_0
nvidia-cudnn-cu12=8.9.2.26=pypi_0
nvidia-cufft-cu12=11.0.2.54=pypi_0
nvidia-curand-cu12=10.3.2.106=pypi_0
nvidia-cusolver-cu12=11.4.5.107=pypi_0
nvidia-cusparse-cu12=12.1.0.106=pypi_0
nvidia-nccl-cu12=2.18.1=pypi_0
nvidia-nvjitlink-cu12=12.4.127=pypi_0
nvidia-nvtx-cu12=12.1.105=pypi_0
omegaconf=2.3.0=pypi_0
openai-whisper=20231117=pypi_0
opencv-python=4.8.1.78=pypi_0
openh264=2.1.1=h4ff587b_0
openjpeg=2.4.0=h3ad879b_0
openssl=3.2.1=hd590300_1
openxlab=0.0.38=pypi_0
orjson=3.10.0=pypi_0
oss2=2.17.0=pypi_0
overrides=7.4.0=py39h06a4308_0
packaging=24.0=pypi_0
pandas=2.0.3=pypi_0
pandocfilters=1.5.0=pyhd3eb1b0_0
panopticapi=0.1=pypi_0
parso=0.8.3=pyhd3eb1b0_0
pathspec=0.12.1=pypi_0
pathtools=0.1.2=pypi_0
pcre2=10.42=hebb0a14_1
pexpect=4.8.0=pyhd3eb1b0_3
pickleshare=0.7.5=pyhd3eb1b0_1003
pillow=9.4.0=pypi_0
pip=24.0=pypi_0
platformdirs=3.10.0=py39h06a4308_0
ply=3.11=py39h06a4308_0
portalocker=2.8.2=pypi_0
prometheus_client=0.14.1=py39h06a4308_0
prompt-toolkit=3.0.43=py39h06a4308_0
prompt_toolkit=3.0.43=hd3eb1b0_0
protobuf=4.25.3=pypi_0
psutil=5.9.8=pypi_0
ptyprocess=0.7.0=pyhd3eb1b0_2
pure_eval=0.2.2=pyhd3eb1b0_0
py-cpuinfo=9.0.0=pypi_0
pyarrow=13.0.0=pypi_0
pycocotools=2.0.7=pypi_0
pycparser=2.22=pypi_0
pycryptodome=3.20.0=pypi_0
pydantic=1.10.15=pypi_0
pydot=2.0.0=pypi_0
pydub=0.25.1=pypi_0
pygments=2.17.2=pypi_0
pyparsing=3.1.2=pypi_0
pyqt=5.15.10=py39h6a678d5_0
pyqt5-sip=12.13.0=py39h5eee18b_0
pyquaternion=0.9.9=pypi_0
pysocks=1.7.1=py39h06a4308_0
python=3.9.19=h955ad1f_0
python-dateutil=2.9.0.post0=pypi_0
python-fastjsonschema=2.16.2=py39h06a4308_0
python-json-logger=2.0.7=py39h06a4308_0
python-multipart=0.0.9=pypi_0
python_abi=3.9=2_cp39
pytorch=2.1.0=py3.9_cuda12.1_cudnn8.9.2_0
pytorch-cuda=12.1=ha16c6d3_5
pytorch-mutex=1.0=cuda
pytz=2023.4=pypi_0
pywavelets=1.6.0=pypi_0
pyyaml=6.0.1=py39h5eee18b_0
pyzmq=25.1.2=py39h6a678d5_0
qt-main=5.15.2=h53bd1ea_10
qtconsole=5.5.1=py39h06a4308_0
qtpy=2.4.1=py39h06a4308_0
readline=8.2=h5eee18b_0
referencing=0.34.0=pypi_0
regex=2023.10.3=pypi_0
requests=2.28.2=pypi_0
rfc3339-validator=0.1.4=py39h06a4308_0
rfc3986-validator=0.1.1=py39h06a4308_0
rich=13.4.2=pypi_0
rpds-py=0.18.0=pypi_0
safetensors=0.4.2=pypi_0
scikit-image=0.21.0=pypi_0
scikit-learn=1.3.1=pypi_0
scipy=1.13.0=pypi_0
seaborn=0.13.2=pypi_0
semantic-version=2.10.0=pypi_0
send2trash=1.8.2=py39h06a4308_0
sentencepiece=0.1.99=pypi_0
sentry-sdk=1.45.0=pypi_0
setproctitle=1.3.3=pypi_0
setuptools=60.2.0=pypi_0
shapely=1.8.0=pypi_0
sip=6.7.12=py39h6a678d5_0
six=1.16.0=pyhd3eb1b0_1
smmap=5.0.1=pypi_0
sniffio=1.3.1=pypi_0
soupsieve=2.5=py39h06a4308_0
sqlite=3.41.2=h5eee18b_0
stack_data=0.2.0=pyhd3eb1b0_0
starlette=0.37.2=pypi_0
submitit=1.5.1=pypi_0
sympy=1.12=py39h06a4308_0
tabulate=0.9.0=pypi_0
tbb=2021.8.0=hdb19cb5_0
tenacity=8.2.3=pypi_0
tensorboard=2.16.2=pypi_0
tensorboard-data-server=0.7.2=pypi_0
termcolor=2.4.0=pypi_0
terminado=0.17.1=py39h06a4308_0
threadpoolctl=3.4.0=pypi_0
tifffile=2024.2.12=pypi_0
tiktoken=0.6.0=pypi_0
timm=0.4.12=pypi_0
tinycss2=1.2.1=py39h06a4308_0
tk=8.6.12=h1ccaba5_0
tokenizers=0.14.1=pypi_0
toml=0.10.2=pypi_0
tomli=2.0.1=py39h06a4308_0
toolz=0.12.1=pypi_0
torch=2.1.0=pypi_0
torchaudio=2.1.0=py39_cu121
torchtriton=2.1.0=py39
torchvision=0.16.0=pypi_0
tornado=6.3.3=py39h5eee18b_0
tqdm=4.65.2=pypi_0
traitlets=5.7.1=py39h06a4308_0
transformers=4.34.0=pypi_0
triton=2.1.0=pypi_0
typing=3.7.4.3=pypi_0
typing-extensions=4.11.0=pypi_0
typing_extensions=4.9.0=py39h06a4308_1
tzdata=2024.1=pypi_0
urllib3=1.26.18=pypi_0
uvicorn=0.29.0=pypi_0
vision-datasets=0.2.2=pypi_0
wandb=0.15.12=pypi_0
wcwidth=0.2.13=pypi_0
webencodings=0.5.1=py39h06a4308_1
websocket-client=0.58.0=py39h06a4308_4
websockets=11.0.3=pypi_0
werkzeug=3.0.2=pypi_0
wheel=0.41.2=py39h06a4308_0
widgetsnbextension=4.0.10=py39h06a4308_0
xz=5.4.6=h5eee18b_0
yacs=0.1.8=pypi_0
yaml=0.2.5=h7b6447c_0
zeromq=4.3.5=h6a678d5_0
zipp=3.18.1=pypi_0
zlib=1.2.13=h5eee18b_0
zstd=1.5.5=hc292b87_0
`

**Comment by dalcinl** [comment]
Sorry, but I cannot make any sense of what you are saying or what you are trying to do.

**Comment by dalcinl** [comment]
First of all, looking up for `OMPI_COMM_WORLD_SIZE` in the environment is something end users should not typically do unless very specialized and somewhat hacky use cases. That being said, if you really know what you are doing, who am I to object?

If you are using Open MPI and the variable `OMPI_COMM_WORLD_SIZE` is not in the environment, then that probably means that you are NOT running under the control of the `mpiexec`/`mpirun` launcher, and just running your code like `python script.py`. To support that case too, that is, to run without `mpiexec`, you have to slightly modify your code:

```python
size = int(os.environ.get('OMPI_COMM_WORLD_SIZE', 1)) 
...
rank = int(os.environ.get('OMPI_COMM_WORLD_RANK', 0))
```

However, after a second look, it seems that something is messed up in your side. In the environment dump that you pasted I see variables like `I_MPI_ROOT`. That means that somehow your are using Intel MPI or you have the Intel MPI environment active, therefore your `mpiexec` launcher corresponds to Intel MPI. Therefore the  `OMPI_COMM_WORLD_SIZE` variables and other related will simply not be available, as these are an Open MPI thing.
This is a classic case of mixed up MPI implementations, you seem to be expecting Open MPI, but Intel MPI stuff is around.
