### ISSUE TITLE
Allreduce floating point issue again

### ISSUE THREAD

**Issue by dizcza** [mpi4py/mpi4py#5]
Dear all,
I stumbled upon `1.7e-3` floating-point tolerance error when using MPI Allreduce:

```python
import numpy as np
from mpi4py import MPI
from tqdm import tqdm

comm = MPI.COMM_WORLD
size = comm.Get_size()
rank = comm.Get_rank()


def compute_P_total():
    logP_rows = np.genfromtxt('logP_hist.txt')  # 1d array
    P_total = np.zeros(1, dtype=np.float32)
    for i, logP in enumerate(tqdm(logP_rows, disable=rank != 0)):
        if i % size == rank:
            P_total += np.exp(logP)
    # the correct P_total value is 0.94590753

    if size != 1:
        # MPI Allreduce
        totals = np.zeros_like(P_total)
        mpi_float_type = MPI.FLOAT if P_total.dtype == np.float32 else MPI.DOUBLE
        comm.Allreduce(
            [P_total, mpi_float_type],
            [totals, mpi_float_type],
            op=MPI.SUM)
        P_total = totals

    return P_total


print(compute_P_total())
```

Without MPI: `0.94590753`
With MPI:  `0.9476357` (ran with `mpiexec -n 4 python -m script.py`)

Link to the 'logP_hist.txt' file: https://www.dropbox.com/s/8nqs85yf6ycg0um/logP_hist.txt?dl=1

I'm wondering, is it a purely floating-point associative issue that the order of adding floats impacts the result or I'm wrongly reducing the result with MPI? If I change the data type to double (`np.float64`), the difference becomes negligible (1e-6).

Thanks.

**Comment by dizcza** [comment]
Yes, you're right.
Thank you for the test, it's obvious now.

**Comment by dalcinl** [comment]
I'm not sure what are the exact requirements of your code, but the fact that your input is a double precision array, but the accumulator variable only single precision looks a bit weird. Of course, I understand this maybe just an artifact of you generating that file such that we were able to reproduce the issue. I guess in your actual code all arrays are single precision? Even in that case, maybe you can afford doing the reduction on a double precision accumulator variable?

**Comment by dizcza** [comment]
This is a symptom of a bug in our code: we do generate double-precision values but store the exp of them and reduce in a single-precision value. I was thinking that maybe MPI adds an extra overhead in terms of the additional error accumulation and wanted to make sure that this is not the case. Your test code showed that.
And yes, we should stick to double-precision values at least for the resulting array and the reduce operation.
