### ISSUE TITLE
"error:  ‘MPI_Session’ does not name a type" with mpi4py 4.0

### ISSUE THREAD

**Issue by paugier** [mpi4py/mpi4py#534]
I just realized that with mpi4py 4.0, we cannot compile the fluidfft plugins using MPI since we get 

```
error:  ‘MPI_Session’ does not name a type
 2215 |   MPI_Session ob_mpi;
```

I guess it is not really a bug in mpi4py but it compiles well with mpi4py<4.0.

The error is triggered from the Cython extension produced by this code https://foss.heptapod.net/fluiddyn/fluidfft/-/tree/branch/default/plugins/fluidfft-builder/fluidfft_builder?ref_type=heads

I don't understand this issue so any suggestion would be greatly appreciated. Is there a change in mpi4py 4.0 that could lead to this error?

**Comment by dalcinl** [comment]
You are using an MPI implementation that does not yet support MPI 4.0.
For a relatively simple workaround please see https://github.com/mpi4py/mpi4py/issues/525#issuecomment-2256633404.

**Comment by paugier** [comment]
Thank you for the quick response!

Note that I wouldn't have bother you with this issue if this was mentioned in https://github.com/mpi4py/mpi4py/blob/master/CHANGES.rst. A short note would be useful.
