### ISSUE TITLE
test_util_pool test_apply failing build-time tests

### ISSUE THREAD

**Issue by drew-parsons** [mpi4py/mpi4py#545]
test_apply (test_util_pool.TestProcessPool.test_apply) from mpi4py 4.0.0 is failing often (but not always) on debian unstable during build-time tests while building packages.

Build logs can be found at https://buildd.debian.org/status/package.php?p=mpi4py
The error occured on [arm64](https://buildd.debian.org/status/fetch.php?pkg=mpi4py&arch=arm64&ver=4.0.0-2&stamp=1726015735&raw=0), [mips64el](https://buildd.debian.org/status/fetch.php?pkg=mpi4py&arch=mips64el&ver=4.0.0-2&stamp=1726029463&raw=0), [s390x](https://buildd.debian.org/status/fetch.php?pkg=mpi4py&arch=s390x&ver=4.0.0-2&stamp=1726028533&raw=0) (all using OpenMPI 4.1.6).

Strangely, all tests passed during the build of [arch-dependent](https://buildd.debian.org/status/fetch.php?pkg=mpi4py&arch=amd64&ver=4.0.0-2&stamp=1726006863&raw=0) packages on amd64, but failed building [arch-independent](https://buildd.debian.org/status/fetch.php?pkg=mpi4py&arch=all&ver=4.0.0-2&stamp=1726016076&raw=0) packages (docs).  The build environment is more or less the same (different specific build machine), so there must be some randomness in the failure, some deadlock.

The error message (from arm64) is
```
testTestAll (test_util_pkl5.TestPKL5World.testTestAll) ... ok
testWaitAll (test_util_pkl5.TestPKL5World.testWaitAll) ... ok
test_apply (test_util_pool.TestProcessPool.test_apply) ... [sbuild:00243] 1 more process has sent help message help-mca-bml-r2.txt / unreachable proc
[sbuild:00483] [[13078,42],0] ORTE_ERROR_LOG: Unreachable in file ../../../ompi/dpm/dpm.c at line 493
[sbuild:00242] [[13078,1],0] ORTE_ERROR_LOG: Unreachable in file ../../../ompi/dpm/dpm.c at line 493
Exception in thread Thread-6 (_manager_spawn):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.12/build/mpi4py/futures/_core.py", line 350, in _manager_spawn
    comm = serialized(client_spawn)(pyexe, pyargs, nprocs, info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.12/build/mpi4py/futures/_core.py", line 1058, in client_spawn
    comm = MPI.COMM_SELF.Spawn(python_exe, args, max_workers, info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/mpi4py/MPI.src/Comm.pyx", line 2544, in mpi4py.MPI.Intracomm.Spawn
    with nogil: CHKERR( MPI_Comm_spawn(
mpi4py.MPI.Exception: MPI_ERR_INTERN: internal error
[sbuild:00243] 1 more process has sent help message help-mca-bml-r2.txt / unreachable proc
[sbuild:00243] 1 more process has sent help message help-mpi-runtime.txt / mpi_init:startup:internal-failure
[sbuild:00243] 1 more process has sent help message help-mpi-errors.txt / mpi_errors_are_fatal unknown handle
E: Build killed with signal TERM after 150 minutes of inactivity
```

**Comment by dalcinl** [comment]
Once again, this most likely  due to the unreliability of `MPI_Comm_spawn`.  Under Open MPI, you should consider spawn irremediably broken in every release except the latest v5.0.5. With `export MPI4PY_TEST_SPAWN=false` you should make the test suite skip anything that requires spawn. In fact, I've added that env var months ago to help the Open MPI team pin down all the issues in their v5.0.x branch.

**Comment by dalcinl** [comment]
Oh, sorry, my bad. If you want to skip the spawn stuff with Open MPI v4.1.x, then you have "pretend" you are running on GitHub Actions, therefore you also need `export GITHUB_ACTIONS=true`. Sorry, not very clean looking. If you prefer, I can suggest a patch (basically, replace the `github()` function call with `skip_spawn()`).

**Comment by drew-parsons** [comment]
No problem, I can just add the extra env variable and blame upstream :)
We have OpenMPI 5 ready in experimental. I guess we'll make the transition before too long.

**Comment by drew-parsons** [comment]
GITHUB_ACTIONS gets the tests skipping successfully, packages are completing build now
https://buildd.debian.org/status/package.php?p=mpi4py
