### ISSUE TITLE
pyMPI

### ISSUE THREAD

**Issue by patmiller** [mpi4py/mpi4py#551]
in docs/source/intro the text states that pyMPI does not support numeric arrays.

That is incorrect... it in fact transports numeric arrays using native MPI types. So, for instance, a numpy array will cross the wires as raw bytes instead of requiring a pickle/unpickle step.

So, if you could please just change the text from 

General (picklable) Python objects can be messaged between processors. There is not support for numeric arrays.

to

General (picklable) Python objects can be messaged between processors. There is native support for numeric arrays.

I would also add the caveat that it only supports Python 2.x

Best,
Pat Miller
(pyMPI's author)

**Comment by dalcinl** [comment]
Sorry for the incorrect statement. That text is almost 20 years old. I do not recall whether pyMPI did not yet support numeric arrays, or whether I was young and dumb enough to not realize the feature was indeed supported. 
In any case, #552 contains a fix as per your request.

**Comment by patmiller** [comment]
Awesome!  Just noticed it and it is nice to be correct for historical
reasons :-)  PyMPI was already old when the page was crafted; and it isn't
like there is a huge community shunning you over a minor thing.
Best!
Pat
