### ISSUE TITLE
libiconv.so.2 ImportError

### ISSUE THREAD

**Issue by JSLJ23** [mpi4py/mpi4py#569]
I am trying to install and run a large job with the help of mpi4py on the [Setonix supercomputer](https://pawsey.org.au/systems/setonix/) and everything is installed through conda/mamba. That installation works fine but when I try to import MPI from mpi4py, I run into an import error for libiconv.so.2.

```
(/scratch/pawsey0799/joshua_soon/mamba_envs/psi4_py311) joshua_soon@setonix-02:~> python
Python 3.11.10 | packaged by conda-forge | (main, Sep 30 2024, 18:08:57) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mpi4py import MPI
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libiconv.so.2: cannot open shared object file: No such file or directory
```

Searching the conda prefix lib paths, `libiconv.so.2` and `libiconv.so` are both present so I am not sure what could be causing this. Appreciate any help I could get on this matter.

```
(/scratch/pawsey0799/joshua_soon/mamba_envs/psi4_py311) joshua_soon@setonix-02:~> find $CONDA_PREFIX -name "libiconv.so*"

/scratch/pawsey0799/joshua_soon/mamba_envs/psi4_py311/lib/libiconv.so
/scratch/pawsey0799/joshua_soon/mamba_envs/psi4_py311/lib/libiconv.so.2
```

**Comment by dalcinl** [comment]
You did not tell how you created your environment, so it is very hard for me recreate what's installed on your side and have a closer look at the possible issue. You did not even tell what MPI implementation you installed. That being said, my guess is you have installed Open MPI installed. I'm not sure why the conda-forge Open MPI package is linked to `libiconv.so` to produce such error, it is probably an indirect dependency of the `libxml2` package. Moreover, you seem to have `libiconv` properly installed in the conda environment, so I'm not sure why the library does not load properly.
What's the output of the following command?
```console
ldd /scratch/pawsey0799/joshua_soon/mamba_envs/psi4_py311/lib/libxml2.so
```
In any case, this is not an mpi4py issue. Looks like that any other MPI binary would fail with a similar error. In that case, this is not the proper place to discuss it, further comments and questions should be directed to:
https://github.com/conda-forge/openmpi-feedstock/issues

All that being said, as you are running on a HPE Cray system, my recommendation is to use the Cray MPICH (that is, load it via modules if not  loaded by default) as an "external" MPI implementation as explained here:
https://conda-forge.org/docs/user/tipsandtricks/#using-external-message-passing-interface-mpi-libraries
```console
mamba install "mpich=x.y.z=external_*"
```
