### ISSUE TITLE
mpi4py version compatible with Python > 3.9.0

### ISSUE THREAD

**Issue by Valdes-Tresanco-MS** [mpi4py/mpi4py#57]
Hi 
Recently a user of one of my programs had difficulty installing `mpi4py`. Doing a careful review I realized that the problem is about compatibility. In the conda environment, many packages update the base version of `python` from `3.8.5` to `3.9.5` which is the latest. This conflicts with the current version of `mpi4py` (`3.0.3`) which is only compatible with `python < 3.9.0a`.
If installed directly from Github it works fine.
Although it is an alpha version, is it possible for you to release this update to the PyPi and anaconda repositories?

Thanks in advance

Mario S.

**Comment by dalcinl** [comment]
I cannot reproduce any of these issues and you provided so little information that I cannot even guess. Are you on Linux? Is your Python 3.9 installed from the conda-forge channel? What's the exact "difficulty" you ran into? Did you upgrade the `conda` package in your base environment? Can you show us some output and the exact commands that you are executing and fail on your side?

The 3.0.3 release tarball at PyPI does build fine with Python 3.9. I just checked by downloading the tarball from PyPI and running `python -m pip wheel mpi4py-3.0.3.tar.gz`. 

Regarding the conda-forge packages, everything seems to working fine on my side, no problem installing Python 3.9 and mpi4py (both from the conda-forge channel, of course) in a scratch environment, I just tried.

**Comment by Valdes-Tresanco-MS** [comment]
I am very sorry to have incurred in reporting an incomplete error.

After doing many tests on different Linux-based operating systems, I realized that the error is related to a conda package as I explain below:

**Ubuntu 18.04 / Linux Mint 19.1**
_Miniconda (https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64.sh)_
- Upgrading conda from v4.9.2 to v4.10.1
- I create a virtual environment and activate it
- Install the package `ambertools21`
- If I install the `compilers` package
    - If I install `mpi4py` (`python -m pip install mpi4py`) I get the error shown in [log1.log](https://github.com/mpi4py/mpi4py/files/6682069/log1.log). (I speculate that this is an incompatibility between the compilers (use `mpicc` from the path) and the include folder (included in conda))
    - If I install it by conda (`conda install -c anaconda mpi4py`) I get the error shown in [log2.log](https://github.com/mpi4py/mpi4py/files/6682073/log2.log) (I thought this was the official repository)
    - Installation from conda-forge works
- If I don't install `compilers` then I can install `mpi4py` using pip without problems, however, I get the same error using conda

**Ubuntu 20.04 / Linux Mint 20.1**
_Miniconda (https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64.sh)_
- Upgrading conda from v4.9.2 to v4.10.1
- I create a virtual environment and activate it
- Install the package `ambertools21`
- If I install the `compilers` package
    - If I install `mpi4py` (`python -m pip install mpi4py`) I get the error shown in the attached file (log1).
    - Installation from conda works (from both repositories: anaconda and conda-forge)
- If I don't install `compilers` then I can install `mpi4py` without problems using pip and conda

Since I have already identified the possible causes of the error, I consider that it is now resolved. Any consideration from you is welcome and thank you very much for your response.

Best regards
Mario S.

**Comment by dalcinl** [comment]
- The package name is `ambertools`, not `ambertools21`, so I guess your `21` in the name actually refers to the version number. You did not mention how you installed `ambertools`, but this package can be installed with conda.
-  The official mpi4py conda channel is `conda-forge`. I name it _official_ just because is the one I have access and maintain. Issues with mpi4py from the `anaconda` channel are not my responsibility, I'm not an employee of Continuum Analytics. 
- Issues with installing mpi4py with pip inside a conda-forge environment alongside the `compilers` package are expected. We have an [old issue open](https://bitbucket.org/mpi4py/mpi4py/issues/143/build-failure-with-python-installed-from
), with a [workaround](https://bitbucket.org/mpi4py/mpi4py/issues/143/build-failure-with-python-installed-from#comment-54165726) of mine. This issues needs someone to take action. Lecturing me about "user needs" or "issue tracker management" will not solve the root problem. So, you can either pip install mpi4py without the compilers package or try my workaround. However, if you can, don't use pip at all, just use conda.

**Comment by Valdes-Tresanco-MS** [comment]
Thank you very much for your considerations.
- Yes, the installation of ambertools is carried out from conda-forge and does not generate incompatibility, so I only mentioned it as part of the flow of steps that I followed. (`conda install -c conda-forge ambertools=21`)
- I just studied about this. Since I have not worked much with conda packages, it was not entirely clear which packages correspond to the official developer, excuse my ignorance
- Although I looked to see if a similar error had been reported, I did not reach the Bitbucket repository. Here on Github, said error is not reported so I thought it had never been reported. I'm very sorry if I made such an impression on you, but it wouldn't occur to me at all to tell you what to do or not do about what you're saying. In my particular case, since AmberTools has two ways of installation (from conda and compiling it directly) then `mpi4py` is a dependency of my package (only available from PyPI) in order to standardize the installation process. Since I was completely unaware of the incompatibility of `mpi4py` and `compilers` (using PyPI), I could not take action. I will add to my package documentation this possible error and how to fix it (installing `mpi4py` from `conda-forge`).

I apologize again, if I gave you the wrong impression, it was not my intention at all. Thank you very much for your reply and for your work with mpi4py.
Best regards
Mario S.

**Comment by dalcinl** [comment]
> * I'm very sorry if I made such an impression on you, but it wouldn't occur to me at all to tell you what to do or not do about what you're saying.

Oh, no, no... I was not referring to you, not at all! I was just expressing my frustration with that old issue I linked. You probably did not read the full discussion (don't, you will just waste you time). It is in that issue that I'm being _lectured_ about how to do things, and there you have, no one moved a finger towards an actual solution, and now another user (you) gets bitten by the issue. In any case, now that you solved your issues and got an idea about what's going on, forget about my rants, I'm just burned out.
