### ISSUE TITLE
undefined symbol: ompi_mpi_errors_abort error

### ISSUE THREAD

**Issue by kanseiishikawa** [mpi4py/mpi4py#570]
I couldn't solve this error.
```
Traceback (most recent call last):
  File "/home/Athena/sekitoba/last_passing_rank/main.py", line 75, in <module>
    main()
  File "/home/Athena/sekitoba/last_passing_rank/main.py", line 26, in main
    from mpi4py import MPI
ImportError: /home/Athena/.pyenv/versions/3.10.1/lib/python3.10/site-packages/mpi4py/MPI.cpython-310-x86_64-linux-gnu.so: undefined symbol: ompi_mpi_errors_abort
```

I've also tried different openMPI versions but the error remained the same.
The environment is as follows
```
OS: rocky9.4
Python: 3.10.1
mpi4py: 4.0.1
openMPI: 4.1.1
```

**Comment by kusnezoff-alexander** [comment]
Hey! I assume you closed the issue because you have found a solution.
As a matter of fact I am currently getting the exact same error, could you please share how you solved the problem?

**Comment by dalcinl** [comment]
@kusnezoff-alexander If you are experiencing the same issue, the most likely reason is the mpi4py you have installed was built with Open MPI 5.x, but you are using mpi4py 4.x at runtime. I would suggest to rebuild and reinstall mpi4py, but first make sure to run `pip cache remove mpi4py` to avoid installing a prebuilt, cached wheel.
