### ISSUE TITLE
nvidia HPC-X not supported

### ISSUE THREAD

**Issue by karna48** [mpi4py/mpi4py#572]
I have tried to install mpi4py with HPC-X MPI (in NVIDIA HPC SDK container).

Problem is their compiler does not support commandline switches: 
  nvc-Error-Unknown switch: -Wno-unused-result
  nvc-Error-Unknown switch: -fwrapv

the compilers are nvc and nvc++, version 24.9-0

Is -fwrapv really necessary?

I have managed to build with cmake, however not being able to install it into python as a workaround yet.

**Comment by dalcinl** [comment]
1. Bogus compiler switches are not mpi4py's fault. They come from Python/sysconfig/setuptools.
2. mpi4py should not be built with `nvc`. There is no CUDA code in mpi4py. CUDA support comes from the MPI library and the implementation of the CUDA array interface and DLPack. Doing `export OMPI_CC=cc` may solve the problem.
3. If cmake seems to be working, then you can try [[docs]]( https://mpi4py.readthedocs.io/en/stable/install.html#envvar-MPI4PY_BUILD_BACKEND):
```console
export MPI4PY_BUILD_BACKEND=scikit-build-core
pip install mpi4py
```
4. Alternatively, you could try installing a pre-built binary wheel from [here](https://anaconda.org/mpi4py/mpi4py):
```console
pip install -i https://pypi.anaconda.org/mpi4py/simple mpi4py
```

cc @leofang Any additional tips?

**Comment by karna48** [comment]
1. ok, I get that, just if you know is I can change them easily somehow
2. nvidia is confusing thigs, but the "nvc" and "nvc++" are their "HPC" compilers and not to be confused with "nvcc" which actually is the CUDA compiler; HPC-X is a combination of libraries including their own MPI implementation and when I activate it, it sets mpicc and mpicxx to nvc and nvc++.
3. I will try it, thanks.
4. not sure if the prebuild version will interact with HPC-X's MPI

**Comment by dalcinl** [comment]
> 1. ok, I get that, just if you know is I can change them easily somehow

Where the Python you are using comes from?  One obvious fix is to remove the offending flags from relevant files in your Python installation. Another way is to to write a custom nvc-py.sh shell script that filters out the offending flags from the argument list and then `export OMPI_CC=/path/to/nvc-py.sh`.

> 2. nvidia is confusing thigs, but the "nvc" and "nvc++" are their "HPC" compilers and not to be confused with "nvcc" which actually is the CUDA compiler; HPC-X is a combination of libraries including their own MPI implementation and when I activate it, it sets mpicc and mpicxx to nvc and nvc++.

Sorry, I misread "nvc"  at "nvcc".

> 4. not sure if the prebuild version will be compatibile with HPC-X's MPI

Give it a try. I'm hopeful. Of course, make sure LD_LIBRARY_PATH contains the directory with the MPI shared library.

**Comment by dalcinl** [comment]
@karna48 Any updates?

**Comment by karna48** [comment]
Changing the MPI4PY_BUILD_BACKEND worked.
Also the prebuild anaconda package worked.

 (I just tried simple gather example on CPU, don't know if the GPU stuff works).

Thank you very much for help!

**Comment by dalcinl** [comment]
> (I just tried simple gather example on CPU, don't know if the GPU stuff works).

It should work. All what mpi4py does is forwarding buffers to MPI.

> EDIT: btw I found out now the compiler has -noswitcherror flag which ignores unknown switches; that could also make life easier.

Great to know, thanks for the tip. I'm sure this issue will pop up again.

**Comment by leofang** [comment]
> > EDIT: btw I found out now the compiler has -noswitcherror flag which ignores unknown switches; that could also make life easier.
> 
> Great to know, thanks for the tip. I'm sure this issue will pop up again.

Yes, assuming things haven't changed much on the NVHPC side since 2021, then it should still work: https://github.com/mpi4py/mpi4py/issues/114#issuecomment-939309419

**Comment by dalcinl** [comment]
@leofang I envy your memory... :man_facepalming:

**Comment by karna48** [comment]
sorry, I haven't found the previous issue
