### ISSUE TITLE
Error when use multinode mpi4py with anaconda environment

### ISSUE THREAD

**Issue by zhuo121** [mpi4py/mpi4py#573]
## Description
I am trying to use mpi4py on multiple nodes for collective communication. I have created the same account name ’mpi‘ on both nodes gpu1 and gpu2 . Then, I created python3.9 environment with annconda and successfully installed mpi4py.
```
conda create -n mpi python=3.9
conda activate mpi
conda install -c conda-forge mpi4py openmpi
```
I run the simple code (’test.py‘) below successfully on both nodes,
```
# test.py
from mpi4py import MPI

comm = MPI.COMM_WORLD
size = comm.Get_size()
rank = comm.Get_rank()
node_name = MPI.Get_processor_name() # get the name of the node
print ('Hello world from process %d at %s.' % (rank, node_name))
```
However, when I try to run ’test.py‘ with two nodes，
```
mpiexec -n 2 \
        -H gpu1,gpu2\
        python /home/mpi/mpi_programme/test.py
```
Error occurs
```
--------------------------------------------------------------------------
prterun was unable to find the specified executable file, and therefore did
not launch the job.  This error was first reported for process rank
1; it may have occurred for other processes as well.

NOTE: A common cause for this error is misspelling a prterun command
   line parameter option (remember that prterun interprets the first
   unrecognized command line token as the executable).

Node:       gpu2 Executable: /home/mpi/.conda/envs/mpi/bin/python
--------------------------------------------------------------------------
```
**I wonder what happens and how to correctly use mpi4py on multinodes. Thanks a lot and looking forward to your reply.**

## Environment
cuda: 12.4
openmpi: 4.1.6
conda environment: python 3.9.20, openmpi 5.0.5, mpi4py 4.0.1, mpi 1.0

## Addition
I have done ssh free between nodes and made sure gpu1 and gpu2 can connect properly. I can run the following code correctly in the conda environment:
```
mpiexec -np 2 \
        -H gpu1,gpu2\
        -pernode \
        bash -c 'echo "Hello from process $OMPI_COMM_WORLD_RANK of $OMPI_COMM_WORLD_SIZE on $(hostname)"'
```
the result：
```
Hello from process 0 of 2 on gpu2
bash: /home/mpi/.conda/envs/mpi/lib/libtinfo.so.6: no version information available (required by bash)
Hello from process 1 of 2 on gpu1
```

**Comment by dalcinl** [comment]
I believe this is simply a bad setup of computer nodes. Did you replicate the Python environment in the `gpu2` node? If not, then you have to create the exact same environment you have in the  `gpu1` node, and you have to do it in the same path. Otherwise files in `gpu2` will be missing, and then you get the kind of errors you are getting. 
Look at `conda env export/import` to ease the replication of environments.

PS: Perhaps you should look at how to use a shared filesystem mount point between gpu1 and gpu2, this way you can create environments in the mount point, and they will be immediately available in both compute nodes.

**Comment by zhuo121** [comment]
Thanks for your reply and advice, however ,I'm pretty sure the gpu2 node has the same environment as the gpu1 node, and the path is exactly the same. `conda env export` of gpu1 and gpu2 show as below:
```
(mpi) mpi@gpu1:~$ conda env export
name: mpi
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.9.24=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libevent=2.1.12=hf998b51_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - libhwloc=2.11.2=default_he43201b_1000
  - libiconv=1.17=hd590300_2
  - libnl=3.10.0=h4bc722e_0
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.45.2=h2797004_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.4=h064dc61_0
  - libzlib=1.3.1=hb9d3cd8_2
  - mpi=1.0=openmpi
  - mpi4py=4.0.1=py39h86f8d4e_0
  - ncurses=6.4=h6a678d5_0
  - openmpi=5.0.5=h6ae21d5_103
  - openssl=3.3.2=hb9d3cd8_0
  - pip=24.2=py39h06a4308_0
  - python=3.9.18=h0755675_1_cpython
  - python_abi=3.9=5_cp39
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py39h06a4308_0
  - sqlite=3.45.2=h2c6b66d_0
  - tk=8.6.13=noxft_h4845f30_101
  - tzdata=2024b=h04d1e81_0
  - wheel=0.44.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.3.1=hb9d3cd8_2
prefix: /home/mpi/.conda/envs/mpi
```
```
(mpi) mpi@gpu2:~$ conda env export
name: mpi
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.9.24=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libevent=2.1.12=hf998b51_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - libhwloc=2.11.2=default_he43201b_1000
  - libiconv=1.17=hd590300_2
  - libnl=3.10.0=h4bc722e_0
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.45.2=h2797004_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.4=h064dc61_0
  - libzlib=1.3.1=hb9d3cd8_2
  - mpi=1.0=openmpi
  - mpi4py=4.0.1=py39h86f8d4e_0
  - ncurses=6.4=h6a678d5_0
  - openmpi=5.0.5=h6ae21d5_103
  - openssl=3.3.2=hb9d3cd8_0
  - pip=24.2=py39h06a4308_0
  - python=3.9.18=h0755675_1_cpython
  - python_abi=3.9=5_cp39
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py39h06a4308_0
  - sqlite=3.45.2=h2c6b66d_0
  - tk=8.6.13=noxft_h4845f30_101
  - tzdata=2024b=h04d1e81_0
  - wheel=0.44.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.3.1=hb9d3cd8_2
prefix: /home/mpi/.conda/envs/mpi
```
I will try to use a shared filesystem mount point between gpu1 and gpu2. 
By the way, can mpi4py work on InfiniBand（IB）？

**Comment by dalcinl** [comment]
OK, I see... I'm not sure what's going on. Maybe you should ask for advice to the Open MPI folks. Please understand that this is not an mpi4py issue, it does not even look like a Python issue, your mpiexec invocation is failing straight way to find the executable to launch in one of the nodes.

> I will try to use a shared filesystem mount point between gpu1 and gpu2.

At this point I'm not sure that would help, I think something else may be going on. Anyway, a shared filesystem is ultimately helpful for other purposes, such as being sure that the binaries and code you run are exactly the same at all times, particularly while you are editing your main script and code.

> By the way, can mpi4py work on InfiniBand（IB）？

mpi4py is really agnostic to these details. mpi4py implicitly supports whatever the backend MPI supports.

**Comment by zhuo121** [comment]
I seem to figure out why the previous environment was reporting errors. The reason is that I have `openmpi 4.1.6` installed in the main environment, and I have `openmpi 5.0.5` installed in the conda environment. This seems to create a conflict after gpu1 connects to gpu2. I haven't figured out why this happened, but when I rolled back the version of `openmpi` in conda from `5.0.5` to `4.1.6`, everything started to work.
Thanks again for your patience, this is true a bad setup of computer nodes.

**Comment by dalcinl** [comment]
If possible, I would suggest you rather upgrade to 5.0.5 if you can. In my experience, things are more stable with the openmpi 5.0.x releases.

**Comment by zhuo121** [comment]
OK, thank you for your advice and I will upgrade to openmpi5.0.5.
