### ISSUE TITLE
Examples in https://github.com/mpi4py/mpi4py/tree/master/demo/cuda-aware-mpi fail 

### ISSUE THREAD

**Issue by jjlow** [mpi4py/mpi4py#58]
To whom it may concern,

I built mpi4py from source with gcc-9.3, openmpi-4.1.1 and cuda-11.0 on a DGX A100 server.

When I try to run cuda-aware-mpi demos in the mpi4py repository I get the following error.

"TypeError: message: expecting buffer or list/tuple" from "mpi4py/MPI/msgbuffer.pxi", line 149, in mpi4py.MPI.message_simple when called from comm.Allreduce(sendbuf, recvbuf) on line 19 in use_cupy.py.

I get the same error when I install mpi4py from conda with the command shown below.

conda create -n mpi4py-conda mpi4py cupy numba cudatoolkit=11.0.

Does anyone know why I get this error and how to correct it?

I have attached the errors from my test of mpi4py installed from conda for reference.

John Low
Argonne National Laboratory
[mpi4py cupy demo error.zip](https://github.com/mpi4py/mpi4py/files/6720206/mpi4py.cupy.demo.error.zip)

**Comment by leofang** [comment]
@jjlow This is odd. If you really built mpi4py from source (which source? GitHub? PyPI?), you shouldn't see the same error. The error you saw from conda is expected. Neither the Anaconda channel nor the Conda-Forge channel provides the latest support that we have implemented, and we are working on it (the delay is mainly my bad, sorry!) 

If you haven't done so already, could you try building mpi4py by cloning the GitHub source please?

**Comment by jjlow** [comment]
@leofang I built the source I downloaded from https://github.com/mpi4py/mpi4py/releases/download/3.0.3/mpi4py-3.0.3.tar.gz

Following your suggetion, I built from source from a "git clone https://github.com/mpi4py/mpi4py.git"

Now the cupy and numba demos work without errrors with mpi4py built from the github source.  

Thanks for the help and quick response!

John J. Low
Argonne National Laboratory

**Comment by leofang** [comment]
Ah yes, I should have been clearer. I meant to build from the master branch. Glad it worked for you.
