### ISSUE TITLE
mpi4py.futures.MPIPoolExecutor : add "initializer" argument?

### ISSUE THREAD

**Issue by dstndstn** [mpi4py/mpi4py#7]
Hi,

I'm trying to adapt my python multiprocessing code to use mpi4py, and it would be convenient if the MPIPoolExecutor had `initializer` and `initializer_args` arguments, like multiprocessing.pool.Pool, to allow global initialization steps.  (In my case, I just realized that all my logging messages were probably not appearing because the logging module in the workers was not initialized.)  I don't think there is an obvious way to achieve this same result by, say, calling a `pool.map(initializer, [init_args]*pool_size)`, because you'd like it to run exactly once per worker.

https://docs.python.org/3/library/multiprocessing.html#multiprocessing.pool.Pool

Thanks for your work on mpi4py -- I've just begun using it but it looks really great!  I was (more-or-less) able to convert my single-node multiprocessing code into a multi-node MPI app with only a small wrapper script.  That's pretty impressive (on your part!).

**Comment by dalcinl** [comment]
Let me clarify that `mpi4py.futures` follows `concurrent.futures` API and not `multiprocessing.pool`. That being said, your feature request is already in master, see commit 868867a3ccf2780dc2f21952d64f4887eff9fcc9. You can pass `intializer` and `initargs` to [`MPIPoolExecutor`](https://mpi4py.readthedocs.io/en/latest/mpi4py.futures.html#mpi4py.futures.MPIPoolExecutor).

**Comment by dstndstn** [comment]
Oh, that's awesome!  Thank you for your reply, and sorry for taking up your time.

**Comment by dalcinl** [comment]
I warn you that if you are executing script with `python -m mpi4py.futures` as described in the docs, then only things things do not work so well, only the first initializer will run, subsequent ones will error. Implementing this feature was way trickier than you may think. Also, this feature has likely not been used to much out in the wild, so in case of issues please report them back.
