### ISSUE TITLE
Can't transmit large numpy array between nodes on hpc 

### ISSUE THREAD

**Issue by applejwjcat** [mpi4py/mpi4py#75]
I test my code use only one node on hpc, it works well, but when I use two nodes 48 cores to run the code(```test.py```), it went wrong, it seems that the data can't be transmitted successfully and the program hung up with nothing to show.
```
from mpi4py import MPI
import sys
import numpy as np

def print_hello(rank, size, name):
  msg = "Hello World! I am process {0} of {1} on {2}.\n"
  sys.stdout.write(msg.format(rank, size, name))

if __name__ == "__main__":
    comm = MPI.COMM_WORLD
    size = MPI.COMM_WORLD.Get_size()
    rank = MPI.COMM_WORLD.Get_rank()
    name = MPI.Get_processor_name()
    if rank == 0:
        data = np.random.random((48,36000))
        print(data.shape)
    else:
        data = None

    data = comm.scatter(data,root=0)
    print(data.shape)

    print_hello(rank, size, name)
```
However, if I changed the the number from 36000 to 3600, it works well and output is correct as I expected:
```
(3600,)
Hello World! I am process 8 of 48 on cn7783.
(3600,)
Hello World! I am process 9 of 48 on cn7783.
(3600,)
Hello World! I am process 10 of 48 on cn7783.
(3600,)
Hello World! I am process 2 of 48 on cn7783.
(3600,)
Hello World! I am process 11 of 48 on cn7783.
(3600,)
Hello World! I am process 3 of 48 on cn7783.
(3600,)
Hello World! I am process 1 of 48 on cn7783.
(3600,)
Hello World! I am process 12 of 48 on cn7783.
...
...
Hello World! I am process 40 of 48 on cn7784.
(3600,)
Hello World! I am process 46 of 48 on cn7784.
(48, 3600)
(3600,)
Hello World! I am process 0 of 48 on cn7783.
(3600,)
Hello World! I am process 47 of 48 on cn7784.
```
Is there a limitation when transmitting data? Is there anything else to avoid it?

**Comment by applejwjcat** [comment]
By the way, If I use the number 36000 and run my code on only one node, it works well !

**Comment by dalcinl** [comment]
On Wed, 4 Aug 2021 at 18:15, appledog ***@***.***> wrote:

> By the way, If I use the number 36000 and run my code on only one node, it
> works well !
>
>
Yes, it works well in my workstation, too. These arrays are quite small.
The problem seems to be in your MPI backend, an not mpi4py.


-- 
Lisandro Dalcin
============
Senior Research Scientist
Extreme Computing Research Center (ECRC)
King Abdullah University of Science and Technology (KAUST)
http://ecrc.kaust.edu.sa/

**Comment by applejwjcat** [comment]
Yes, You are right!
