### ISSUE TITLE
Typo in setup.py causes error when installing with pipenv

### ISSUE THREAD

**Issue by michaelbuehlmann** [mpi4py/mpi4py#78]
Currently, installing version 3.1.0 of mpi4py with pipenv (Pipfile) leads to the following error:
```
TypeError: 'LegacySpecifier' object is not iterable
```
while solving for dependencies. The `python_requires` item in `setup.py` has an additional `'` at the end of the line, making it an invalid requirement string.

https://github.com/mpi4py/mpi4py/blob/7296a19c4ddb2ab8956c62ffa1bf8a71164174a1/setup.py#L473

**Comment by dalcinl** [comment]
Looks like we need a patch release to fix this issue.

**Comment by cslominski** [comment]
I'm also experiencing this problem. Is there an ETA for when this will be fixed? Thanks all.

**Comment by dalcinl** [comment]
https://github.com/mpi4py/mpi4py/releases/tag/3.1.1
