### ISSUE TITLE
KeyError in win.Get when fetching a buffer of structured numpy arrays.

### ISSUE THREAD

**Issue by JBlaschke** [mpi4py/mpi4py#81]
When I try:
```python
win = MPI.Win.Allocate(...)

buf = array([(0, 0), (0, 0), (0, 0)], dtype=[('a', '<u8'), ('b', '<u8')])
win.Get(buf, target_rank=0)
```
I get:
```
Traceback (most recent call last):
  File "test3.py", line 56, in <module>
    win.Get(buf, target_rank=0)
  File "mpi4py/MPI/Win.pyx", line 398, in mpi4py.MPI.Win.Get
  File "mpi4py/MPI/msgbuffer.pxi", line 1037, in mpi4py.MPI._p_msg_rma.for_get
  File "mpi4py/MPI/msgbuffer.pxi", line 995, in mpi4py.MPI._p_msg_rma.for_rma
  File "mpi4py/MPI/msgbuffer.pxi", line 203, in mpi4py.MPI.message_simple
  File "mpi4py/MPI/msgbuffer.pxi", line 145, in mpi4py.MPI.message_basic
KeyError: 'T{L:a:L:b:}'
```

However this works:
```python
buf = array([(0, 0), (0, 0), (0, 0)], dtype=np.unint64)
win.Get(buf, target_rank=0)
```
(except that the structure information is lost -- and would have to be re-assembled after `win.Get`)

**Comment by dalcinl** [comment]
mpi4py converts `numpy.dtype` -> `MPI.Datatype` automatically only for basic numpy datatypes, but not for compound array/struct numpy datatypes. 

However, the latest mpi4py release do have a solution for this, although it is manual:

```python
import numpy as np
from mpi4py import MPI
from mpi4py.util.dtlib import from_numpy_dtype

win = MPI.Win.Allocate()

buf = np.empty(3, dtype=[('a', '<u8'), ('b', '<u8')])  # use *numpy.empty*

mpitype = from_numpy_dtype(buf.dtype)  # Convert numpy.dtype -> MPI.Datatype()
mpitype.Commit()  # commit the datatype before using it in communication calls

...
win.Get([buf, dtype], target_rank=0)
...

mpitype.Free()  # mpi4py does not free MPI handles, do it yourself or you'll have a leak.
```

**Comment by JBlaschke** [comment]
Thanks @dalcinl this works. In case anyone else is reading this, I had to make one change to the `win.Get` call above: you need to pass the `mpitype` instead of the `dtype`:
```python
win.Get([buf, mpitype], target_rank=0)
```

Is there a place to document some of these more advanced use cases -- I would be happy to put in some examples via PR :)

Cheers,
Johannes

**Comment by dalcinl** [comment]
I guess adding some examples in `mpi4py.util.dtlib.rst` in a `.. rubric:: Examples` section after the function descriptions would be OK. We should have a good example, preferably a struct datatype (with nested substructs if possible), to make it more interesting. At least something like as an `Element` (as in the periodic table) datatype, with symbol (char[2]), atomic number(int), weight (float).
